### ISSUE TITLE
[Requires Documentation ] Thin obstacles. Fluid leaking through obstacles.

### ISSUE THREAD

**Issue by niklassjogren** [rlguy/Blender-FLIP-Fluids#148]
These are maybe my mistakes, probably more a questions than a issue, but I have problems with an animated can (obstacle) that leaks fluid! What are the important settings to get it tight, not leaking? Resolution and Frame Substeps I suppose play a big part, maybe size/scale to? Is it possible to say what a high and low Frame Substep setting is, is there anything else I miss?
/Niklas

**Comment by TripleDots** [comment]
When you click on an obstacle object, in the settings you can thicken the mesh with "Expand."
Also turning "export animated mesh" (when required) helped this issue for me.

If possible could you upload your blend file or create a video of this happening?

**Comment by jcobreros** [comment]
I'm having the same problem.

[vase.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1756571/vase.zip)

**Comment by niklassjogren** [comment]
Hi! My problem was that the liquid went through the can when there were fast movements, perhaps to thin walls! I've done some new tests and it seems to work better at higher frame rate (60), I've also lowered CFL Condition Number to 1 and increased Frame Substeps a bit!
In this simulation I forgot to enable "Adaptive Time Stepping for Obstacles", which might help?
![image](https://user-images.githubusercontent.com/7673361/36647615-b5a9f19a-1a88-11e8-92c0-16f9f5d400dd.png)
[Blender_Fluid_Leaks_01.zip](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/files/1756849/Blender_Fluid_Leaks_01.zip)

Except that I probably have to learn and understand the plugin, I think it works really well so far, great work!
/Niklas

**Comment by niklassjogren** [comment]
I noticed that if you can use a closed mesh as a inverted obstacle, you can use much lower settings!
![image](https://user-images.githubusercontent.com/7673361/36666372-af451fde-1aea-11e8-864d-08bb32e4ba27.png)
/niklas

**Comment by niklassjogren** [comment]
I noticed that if you can use a closed mesh as a inverted obstacle, you can use much lower settings!
![image](https://user-images.githubusercontent.com/7673361/36666372-af451fde-1aea-11e8-864d-08bb32e4ba27.png)
/niklas

**Comment by guilliamPL** [comment]
Hi niklassjogren,

I will check this technique with my case. That's interesting. But the question is: It is a proper way to avoid leaks?

**Comment by rlguy** [comment]
Hey, this may be an issue of using thin obstacles in your simulation. This is a common issue with FLIP simulations. The simulator uses particles to track where the fluid is. If particles are moving quickly, they may clip through the walls of a thin obstacles and a collision won't be detected. 

This requires documentation on the wiki. I'll be adding this topic to a 'Scene Troubleshooting' page.

Some additional notes here:

>You may have trouble using an obstacle this thin in your simulation. The simulation works on a grid, and if the obstacle is too thin, it may not show up effectively on the simulation grid. This will cause fluid to slip through the obstacle. Some fixes for this include:
>1. **Increase domain resolution** - This will increase grid detail to help the object show up better in the simulation
>2. **Increase obstacle thickness** - A thicker obstacle will show up better on the simulation grid
>3. **If possible, use a thick object for simulation and the thin object for rendering** - This depends on what kind of animation you are trying to achieve
>4. **Reduce the CFL Safety Factor number in the ([Advanced Panel](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Advanced-Settings))** - This will limit how far fluid can move in a time step and may prevent fluid from passing through the obstacle

**Comment by GuyJan** [comment]
In my case, increasing the minimum number of "frame substeps" ( Domain/Advances settings) from the default value of 1 to 2 or higher solved all my thin obstacles problems
![2018-03-05_08-21-34](https://user-images.githubusercontent.com/15571136/36962110-861b4f98-204e-11e8-8c3f-2d6e697b8b73.png)

**Comment by Blaast** [comment]
Same issue here BTW : https://drive.google.com/drive/folders/1U7W0kkjMnZoihr6ADZfPI5reRxhPZfnw

**Comment by rlguy** [comment]
Finally got around to adding this to a [Scene Troubleshooting](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#thin-obstacles-leaking-fluid) document. I will be closing this issue.
