### ISSUE TITLE
[Feature Request] Variable Viscosity (temperature control, heat sources, inflow viscosity)

### ISSUE THREAD

**Issue by guilliamPL** [rlguy/Blender-FLIP-Fluids#189]
Hi,

It will be great to have the option to control viscosity via temperature. Higher temperature - lower viscosity per particle. Temperature is going down over the time and influenced by temperature sources.

Best,
Chris

**Comment by rlguy** [comment]
This is a feature that I have thought about a lot and think it would be great for creating interesting simulations. The viscosity solver is able to solve simulations with variable viscosity throughout the domain, there just is not a user interface to control variable viscosity yet. I have thought about having heat sources with a simple heat simulation to drive temperature/viscosity values. This feature will require some large changes and will take some time to implement, but it is one I have been very excited about.

**Comment by rlguy** [comment]
I'll be adding these variable viscosity features (issue #205) into this issue

> k1ff:
> 
> I see the viscosity parameter is on the domain, acting as a global parameter. Would it be possible to have the viscosity parameter on the emitter itself so that you could have say 3 emitters, each with their own viscosity values, interacting with one another? So a melted chocolate, topped with a thicker chocolate and lastly a thick syrup. https://vimeo.com/89847246  
> 
> Another thing would be variable viscosity. https://vimeo.com/102554547 
So being able to control the viscosity of an object with textures or ramps. 
To handle effects like [melting](https://vimeo.com/206120889) and [lava.](https://vimeo.com/124184280)
> 
> Amazing work guys! I am having such a blast using this addon! I know this is no easy feat! These are just ideas after using Houdini and what would amazing to have inside of Blender

**Comment by rlguy** [comment]
My apologies for the ping on this issue thread, just cleaning up the FLIP Fluids GitHub issue tracker. 

The purpose of the FLIP Fluids GitHub issue tracker is for issues and bugs only. Feature development and requests are handled internally and requests can be made through alternative channels. See: [Guidelines for Feature Requests](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests).

Note: a very basic implementation of variable viscosity has been added and details/info on this feature can be found here: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-World-Settings#viscosity
