### ISSUE TITLE
[Feature request] Inflow - control attributes with animated textures.

### ISSUE THREAD

**Issue by guilliamPL** [rlguy/Blender-FLIP-Fluids#190]
It will be very handy to control inflow **velocity** (maybe even **temperature** for viscosity purposes in the future) with animated textures.

Best,
Chris

**Comment by rlguy** [comment]
Hey, this has been discussed a bit as a feature that we could implement. I don't have much experience with how textures work in Blender, so it will take some research to get an idea of how to implement this. I have a few questions about this feature that could help me understand the request better:

- What would be the desired workflow for adding a texture to an inflow? What kind of interface features would be useful for this?
- I assume the animated textures would be 3D? If so, is there a way to create 3D textures in Blender or import these textures?
- How should the texture affect the velocity? Would it be used to control velocity direction? Velocity strength? Both?

**Comment by guilliamPL** [comment]
Hi,

A think the interface for this should be simplest as possible.  Simple to say. I supposed it can be very hard and time-consuming to code.

Step 1. Click a button '**Add Texture**'.
Step 2. **Choose texture** (from the file or implemented in the addon like 3D noise, cloud or voronoi). I am not a specialist behind the code of the blender and not sure is it possible. The texture should be B&W or converted to grayscale be the default. It will be very helpful to have **multiple** value option and **gradient ramp** to have more control over the texture. Also, something like **time** parameter to animate texture.
Step 3. Choose parameters (via checkboxes???) which should be influenced by the texture (like strength, temperature, maybe velocity direction).  So we can use one texture for multiple parameters.

Option to add next texture (step 1-3). So we can use multiple textures to control parameters separately.

Best,
Chris

**Comment by rlguy** [comment]
My apologies for the ping on this issue thread, just cleaning up the FLIP Fluids GitHub issue tracker. 

The purpose of the FLIP Fluids GitHub issue tracker is for issues and bugs only. Feature development and requests are handled internally and requests can be made through alternative channels. See: [Guidelines for Feature Requests](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests).
