### ISSUE TITLE
[Feature Request] Reset cache to arbitrary frame

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids#195]
Hi,

Similar to previous idea

Rather than just a reset cache functionality - how about a reset to frame function?   The default would be frame 1 however if you are happy with first 150 frames then it would just remove frames after that point

Thanks

**Comment by rlguy** [comment]
This feature will be a prerequisite to the following feature (from issue #194):

> RevDR
>
> Hi,
> As well as move, rename and copy I was wondering if it might be possible to have something along the lines of a 'virtual' append operator (not sure that is the correct frame) - which would function as a precached pre roll.
>
> Why would this be helpful?  Take a case with a sim which will be 250 frames.  You are happy with with the first 150 frames but are working on obstacle movement from frame 150 onwards.   
>
> Rather than keep redoing the whole sim - with this functionality it would be possible to cache first 150 frames into path ..\SimPathA and then append to that into ..\SimPathB.   When playing back frames 0 to 150 could use SimPathA and frome 150 on SimPathB.
>
> Whilst tweaking animation resetting the cache would only delete frames from SimPathB and then baking would bake from (in this case) frame 150.
>
> Now I realise this is kind of possible already using the Copy cache operator and then using the copied cache and continuing to bake.  However, in the case when you might want multiple different sims to all start with the same first 150 it would be more economical for disk space not to require 150 frames of duplicated data.

The implementation of the above feature will be quite related to this feature so I have merged these two features into this issue.

**Comment by rlguy** [comment]
I just realized that I accidentally closed this issue and didn't notice until now.

Test k1ff has also expressed interest in this feature:

> Hey guys,
>
> Would it be possible instead of Resume Baking from the frame you stop baking, could it also be possible to enter in a frame where you want to resume baking from. For example, I like the first half of the simulation, but then I go for a coffee and come back and I don't like the middle but it's already near the end. So I stop baking the simulation and it only allows you to resume from the frame you stopped the simulation. Would be great to be able to choose a frame to resume the baking form earlier in the timeline.

Some notes on this feature after thinking about this a bit:

The ability to reset the cache to any previous frame will require saving 'savestate' or 'checkpoint' data for each frame into the cache. The size of savestate data depend on how many fluid particles and whitewater particles are in the simulation and these files can get quite large (24 bytes per fluid particle, 30 bytes per whitewater particle). Right now, savestate data is only saved for the latest frame.

I think a good implementation  would allow the user set a value to create savestates every **_n_** frames (ex: every 10 frames), or to only create savestates for the current frame. If the user has enough storage to spare, they will be free to save on every frame. After running the simulation, the user would be able to reset the bake to the nearest savestate frame.

**Comment by RevDr** [comment]
Hi,

That all sounds a good plan.  Would it also be feasible to save  'savestate' or 'checkpoint' data for a specific frame as well a current frame? - that would keep storage down in those case.

Thanks

**Comment by rlguy** [comment]
Just an update: this type of feature has been requested quite a bit lately and I plan to begin implementing this shortly. I have created a feature request containing this functionality here and will be closing this issue: #296.
