### ISSUE TITLE
Increase in Scene Preparation time on continues render.

### ISSUE THREAD

**Issue by Mitsuma** [rlguy/Blender-FLIP-Fluids#233]
So I'm currently in the process of rendering a quite big thing, I'm not sure if this is related to Blender collecting some form of Junk or if this is caused by FLIP.

![chrome_2018-04-03_20-11-40](https://user-images.githubusercontent.com/8568089/38268475-78d87148-377e-11e8-8d25-cb10ba12eb74.png)
![cmd_2018-04-03_20-19-41](https://user-images.githubusercontent.com/8568089/38268478-79ebf654-377e-11e8-85a6-fd93ee552edf.png)

First picture is the render time of Frame 229, it is already at 7min.
This is actually not caused by the added complexity, for some odd reason each frame takes longer and longer to prepare and built (synchronizing objects, building BVH etc.)

Second picture shows Frame 231. (230 was skipped due to empty placeholder)
The actual render part was about the same but the scene was done preparing in about 2min earlier.

1min increase after about frame 100, another after frame 140, 190, 220.
Those frames are rough values when the time increased by about a min, it creeps up slowly between those, they are just about the times where I can see a min extra difference in the creation times in windows.

I noticed before in Blender that just skipping through the frames will slowly build up the RAM and never clear any of the past frame data but I'm not sure if this is related.
I'm not sure because I'm currently rendering in console, there is no UI or viewport that could slowly add RAM. 
If somebody has any idea let me know, my current work around would be to restart Blender every 50 frames or so, maybe I ask a friend to make a small program that kills Blender, deletes the bad placeholder and restarts it for me.

There is also an awful 50s+ time spend on "saving the image". Its written as fast as it says in the log but takes ages to be fully done and continue.
I will actually test it again with the UI, see if it crashes or shows the same unnatural time increase. Will take a few hours for proper results though, currently with 3 frames it looks normal.

**Comment by Mitsuma** [comment]
Yea, after some time, around 40+ frames here, there is a ever so slightly increase in time just because of increased preparation time.  
A Blender restart can knock ~1min again.

I have still no clue what this is caused by, so this doesn't really help much I guess.

**Comment by rlguy** [comment]
Thanks for all of this research into the problem! This is quite odd, I'll have to keep an eye on this and find some time to do some testing.

**Comment by Mitsuma** [comment]
![blender_2018-04-06_02-43-44](https://user-images.githubusercontent.com/8568089/38398498-78f3b8dc-3944-11e8-881a-c6a0c664fee8.png)

Just had this pop up when I just tabbed back into Blender. Not sure if it is related. Blender did not crash or anything, I stopped render after this and restarted.
The 8min render times are currently normal as Im at the peak of the simulation.
Overall the timecreep still exists, so I still restart Blender every 50-100 frames to bring the render times downs.

**Comment by rlguy** [comment]
Hey,

The _**Writing to ID classes in this in this context is not allowed**_ type of errors seem to happen when the addon is running code that alters Blender's internal data while it is drawing the viewport/menus. Blender doesn't allow you to alter internal data while it is drawing and it ends up throwing out those errors.

The thing is that Blender chooses when to run this section of addon code and Blender shouldn't be running this code while it is drawing. My assumption is that when you tabbed back into Blender, a draw was forced and also the addon code just happened to be running which triggered an error. These errors just seem to happen rarely and I think it is a bug within Blender. Since they are unpredictable, occur so rarely, and are not very reproducible, it makes it difficult to report this type of error to Blender.

ANYWAYS, I have not had time to test this issue yet. I am wondering if you are using addon version **0.1.3b** or **0.1.2b**? There was some render code changed between versions and perhaps that could be the cause of the problem.

**Comment by Mitsuma** [comment]
![excel_2018-04-06_05-38-41](https://user-images.githubusercontent.com/8568089/38402496-f9422b3c-395c-11e8-96d5-08c3e5bcfb9c.png)
Not sure if this is helpful at all but here is a crude chart of frame render times in seconds (blue line) with overlay of time between frame finish/creation (orange line)

The big orange spikes were basically pauses I did, from most of them you can see that I restarted Blender there (marked by red lines).  
The first big drop is when I noticed it the first time. 
Now I say this is crude because there are a few parts where I had to edit the data, was a bit weird to get these values, excel being a dick to format some parts.

On another note, going to the end where I am now, frame 800 ish you can see a quite dramatic increase in time difference between frame finishing and starting (creation) of a new frame. 
This is the other problem I mentioned, where a frame seemingly takes too much time to start to the next one.
![excel_2018-04-06_05-46-20](https://user-images.githubusercontent.com/8568089/38402653-f925b74e-395d-11e8-9b95-9961fc1fb49b.png)
Ignore the spikes as those are manual pauses.
It basically grows with how complex the scene is.
![excel_2018-04-05_04-02-55](https://user-images.githubusercontent.com/8568089/38402692-50768226-395e-11e8-9f3f-11022285e9fb.png)
It pretty much fits the mesh_surface complexity.

**Comment by Mitsuma** [comment]
I could actually just solve the problem with increasing time between each frames (the "2nd problem").
It is simply a case of not having enough RAM.

![dllhost_2018-04-06_06-10-40](https://user-images.githubusercontent.com/8568089/38403108-55e40dac-3961-11e8-91fe-0acc37e01698.png)
Red line is when a frame hits 100%. Then Blender unloads the RAM but due to most of the data being in the pagefile it has to load and unload that first before it can continue the next frame, thus causing increasing times between a frame which as the graph shows are equivalent to the scene complexity.

This only leaves us with the first and main problem, the increasing preparation/render times. So far I can't say it is a cause of having to rely on the pagefile since similar complex frames magically go up in times and can be "reset" to normal times with a Blender restart.

**Comment by rlguy** [comment]
Haven't heard anymore about this issue, so I'll close this to clean up the issue tracker.
