### ISSUE TITLE
[Feature Request] Tracer Particles (whitewater emitters)

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#262]
Is it planned to add particles to Tracers?
They can be useful for creating inclusions in the liquid.
For example:
https://youtu.be/3xjsAL0zB-I?t=19
Inside the jam there are pieces of berries.

**Comment by rlguy** [comment]
This is planned to be implemented using whitewater emitters. A whitewater emitter feature would allow inflows to emit whitewater particles such as foam/bubble/spray into the simulation domain.

An effect such in your video would be achieved by emitting bubbles into the fluid, setting the bouyancy to 0 so they don't float up, and setting the bubble particle object to a seed model.

**Comment by rlguy** [comment]
Added an official feature request for this here: #334. Will be closing this issue.
