### ISSUE TITLE
[Feature Request] Adaptive Domain Size

### ISSUE THREAD

**Issue by Tungee** [rlguy/Blender-FLIP-Fluids#268]
Would it be possible to add an adaptive domain feature to flip?
The resolution of the of the Domain will stay constant but the size of the domain varies.
The smoke simulator in Blender uses the adaptive domain feature therefore it is is faster with adaptive domain.
https://www.youtube.com/watch?v=v4NJGF_XpQM

Here is something interesting for you if adaptable:
https://www.miikahweb.com/en/blog the third post might be interesting with the subframe und fullsample chapters. Best Regards

**Comment by Mitsuma** [comment]
Also amazing for when you have no clue how big your simulation will end up being, for big things you have to sometimes make a generous domain which comes with obvious downsides.

**Comment by klausbussekw** [comment]
I'm wondering if the approach that Taichi http://taichi.graphics takes would address this…

**Comment by rlguy** [comment]
My apologies for the ping on this issue thread, just cleaning up the FLIP Fluids GitHub issue tracker. 

The purpose of the FLIP Fluids GitHub issue tracker is for issues and bugs only. Feature development and requests are handled internally and requests can be made through alternative channels. See: [Guidelines for Feature Requests](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests).

Just adding a note: adaptive and fully sparse domain features are currently in development as a part of our next simulation engine project.
