### ISSUE TITLE
[Feature Request] Fluid Control Tools, Fluid Forces

### ISSUE THREAD

**Issue by jhowe-3d** [rlguy/Blender-FLIP-Fluids#269]
Is there a plan to add a control to the system to influence the flow of fluids? I would think that a mesh-based tool might provide the most capability and flexibility. Something similar to Blender's current control settings might be a good starting point:

[https://docs.blender.org/manual/en/dev/physics/fluid/types/control.html](https://docs.blender.org/manual/en/dev/physics/fluid/types/control.html)

Physics force fields might be another option or an additional option. This feature would open up a LOT of different special effects. Think of all of the water-bending we could do!

**Comment by rlguy** [comment]
We do plan to add fluid control features and to integrate Blender force field objects into the simulator! This is one I've been thinking about a lot on how to implement. The implementation for both control features and force fields will be similar.

**Comment by jhowe-3d** [comment]
Great! I think at that point the tool will have full feature parity with Blender's tools (and then some). Looking forward to seeing what you come up with for a control scheme.

**Comment by virtushda** [comment]
Is there a rough ETA on this feature?

**Comment by rlguy** [comment]
Hi virtushda,

It is still to early to give an estimate for when this feature will be ready. Recently work has started on this feature, and soon it will become a high priority due to many requests. This will be the next large feature to be added to the addon.

\- Ryan

**Comment by virtushda** [comment]
I'm sure you have too many feature requests all the time. I'm glad to hear that this one is on the roadmap and I eagerly await it! 😄

**Comment by virtushda** [comment]
Hello again, are there any updates on this feature? 😃

**Comment by rlguy** [comment]
Hi virtushda,

This set of features is currently my primary focus during every day development. I hope to get a few of these force field features ready for testing around the end of August or early September.

We'll be starting with a few basic force field modes:
- **Point Forces** - Force fields that pull fluid towards a point. [Example Animation](https://youtu.be/dgqC7zqKFQs)
- **Surface Forces** - Force fields that pull fluids towards the normal of a surface. [Example Animation](https://youtu.be/fbwSav5HQIs)
- **Control/Suction Forces** - Force fields that pull fluid into the shape of an object. Similar to Blender's 'Control' fluid feature. We will be implementing this feature similar to [Houdini's suction fluid](https://www.sidefx.com/docs/houdini/shelf/suctionfluid.html)

After we get these basic forces out for testing, we will start adding other force modes such as vortex fields, fluids that flow along curves, turbulence fields, and others.

\- Ryan

**Comment by virtushda** [comment]
Thank you for this update! I'm pumped!

**Comment by rlguy** [comment]
Another quick update: I've had some delays in the past month and am behind schedule. I have also wanted to expand the initial release to include a [debugging/visualization feature](https://twitter.com/FlipFluids/status/1166120593168752640) which has added more time for development. The new target is a release by the end of this month.

Here's a simulation test with a strong point force: https://twitter.com/FlipFluids/status/1166454860209745920

Looking forward to getting this released for testing!

**Comment by rlguy** [comment]
Update: development of this force fields feature is being put on hold for a bit. The addon needs to be updated to fix a render crashing issue and to support Blender 2.81, which will take priority over development of this feature. More information in issues #403.

At this moment I do not have a projected date when this feature will be released for testing. I will update this thread when I am back to developing this feature. Thank you for your patience!

\- Ryan

**Comment by rlguy** [comment]
Closing this issue now that 'control' forces have been added in FLIP Fluids Version 1.0.9 (Nov 26 2020). An example for how to use our _Volume Force_ mode as a _Control_ force, we have an [example scene here](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Example-Scene-Descriptions#volume_force_control_objectblend).
