### ISSUE TITLE
[Requires Documentation] Fluid presets

### ISSUE THREAD

**Issue by ShadowMakerSdR** [rlguy/Blender-FLIP-Fluids#278]
I have no idea how to operate the presets i.e. since there is a picture of a result, first I thought it was just a material setting, but on further inspection it seems to be a complete setting for all the parameters of the simulation. Which brings me back to my previous post: if it's part of the simulation, then I think it should be higher up in the panels. But right now, it's really difficult - for me - to understand the difference between 'adding a preset to the stack' and 'applying the preset'. This defintely needs some documentation before releasing it into the wild.

**Comment by rlguy** [comment]
Agreed, this feature requires documentation! There's quite a lot of functionality/menus that need explanation.

The preset stack works similar to Blender's modifier stack in that presets can be added without permanently overriding the domain settings. When you add a preset to the stack, the addon will 'remember' your previous settings. So if you remove the preset from the stack, your domain settings will be reverted to what their values were before the preset was added. If multiple presets are added and have conflicting values, presets higher in the stack will override those lower in the stack.

Applying a preset in the stack also works similarly to the modifier stack. When a preset is applied, it will commit it's changes to the domain and can no longer be removed.

Also, from your comment on issue: https://github.com/rlguy/Blender-FLIP-Fluids-Beta/issues/279#issuecomment-383359025

> I did flip back and forth through the presets, but I didn't 'add them to stack' or 'applied' them.
So just looking at the presets by cycling through them, changes the values of the simulation.
Wow. I don't know about the rest of you, but that's unwanted behavior as far as I'm concerned.
If you have the options to make 'stacks' or 'apply settings' they shouldn't apply by themselves. One inadvertent click will then mess up carefully crafted settings. At the very least this should be documented behavior.

I agree that is is unexpected behaviour for presets to be applied automatically. Presets now need to be added to the stack to be applied. This change will be included in the release version.

**Comment by Takis2017** [comment]
What are the presets for? I see that in the moment so that it has no function, if I render with wax, water or caramel preset always the same result.
![test1](https://user-images.githubusercontent.com/43229632/46580293-4cd2aa80-ca4c-11e8-8ff1-654df7f0e704.png)
![test2](https://user-images.githubusercontent.com/43229632/46580295-50663180-ca4c-11e8-9f46-5c9d2c3e8dbb.png)
![test3](https://user-images.githubusercontent.com/43229632/46580296-52c88b80-ca4c-11e8-98d8-1830d2bb0baf.png)

**Comment by Takis2017** [comment]
and now with material. All test redered with a resolution form 130
![test1a](https://user-images.githubusercontent.com/43229632/46580423-ec913800-ca4e-11e8-9841-1436a6b20d65.png)
![test2a](https://user-images.githubusercontent.com/43229632/46580424-ec913800-ca4e-11e8-9b8e-09f7ef364ddb.png)
![test3a](https://user-images.githubusercontent.com/43229632/46580425-ed29ce80-ca4e-11e8-93c4-9c058231a2ab.png)

**Comment by Takis2017** [comment]
Although a material is defined in the presets, the material is ignored during rendering. Where can set in the viscosity in the preset definition?

**Comment by rlguy** [comment]
Hello Takis2017,

The selected preset needs to be added to the preset stack to be applied to the domain settings. See this comment earlier in this thread for details on how the preset system works: https://github.com/rlguy/Blender-FLIP-Fluids/issues/278#issuecomment-383718224

Are the materials being applied correctly after adding the selected preset to the preset stack?

![add_to_stack](https://user-images.githubusercontent.com/4285191/46587493-23148600-ca42-11e8-82ce-e4aadbf30570.jpg)

The viscosity attributes are located in the [World Settings](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-World-Settings#viscosity).

\- Ryan

**Comment by Takis2017** [comment]
Thanks Ryan I have to admit that I did't read it properly. Unfortunately I have a few notes. I can set the world values in the presets but the values are not taken over. That may be a mistake. I assume that the unit of viscosity is the same as in Blender. Here it will be more as useful to specify some values to the user.

**Comment by rlguy** [comment]
Closing this issue now that the FLIP Fluids [Preset System has been deprecated](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Preset-Settings) as a feature.
