### ISSUE TITLE
[Feature Request] Allow loaded cache meshes to be rotated

### ISSUE THREAD

**Issue by enzyme69** [rlguy/Blender-FLIP-Fluids#286]
Dear RLGUY, supposed I have fluid that is good working in one blend, and I would like to use it in different blend, perhaps making multiple Domain object, could I just load the fluid cache and manipulate the transformation, rotation, etc and render it out? 

I tried, but rotation does not seem to work, I tried applying rotation and still does not work as the cached fluid keep resetting its rotation.

Any trick to use?

Thanks!

**Comment by rlguy** [comment]
Hey enzyme69,

You can load the cache within a new Domain inside of a new .blend scene. As of now, rotation is not allowed. I'll add this as a feature request.

Also, just a note: if you load a cache into a new domain and the cache contains whitewater meshes, you will need to enable the whitewater setting in the domain for the particles to be displayed.

**Comment by enzyme69** [comment]
![prtscr capture_6](https://user-images.githubusercontent.com/3952687/39624186-b2a6cf58-4fdb-11e8-8327-98b28d62007b.png)

Thanks for acknowledge-ing the feature request.

In the meantime, I am using Sverchok Add-On to Offset Tranform the fluid surface. There is a funky -1,-1,-1 transform on the surface, but I can fix this using SV also.

Cheers!

**Comment by enzyme69** [comment]
I re-open just in case people asking for similar features.

**Comment by enzyme69** [comment]
![prtscr capture_5](https://user-images.githubusercontent.com/3952687/39624297-2363638c-4fdc-11e8-90d3-0139f561f03c.png)
Rotating also works using this method.

I supposed, Alembic export can also work, but Alembic cache also has this limitation of difficulty to offset transform.

**Comment by enzyme69** [comment]
UPDATE:
We can also do this without Sverchok Add-On, simply apply Displacement to the fluid_surface shape, with zero strength, then export Alembic Cache. Should force it to bake fluid :)

**Comment by enzyme69** [comment]
But would still be nice to be able to simply rotate the surface directly without another baking / caching.

**Comment by rlguy** [comment]
My apologies for the ping on this issue thread, just cleaning up the FLIP Fluids GitHub issue tracker. 

The purpose of the FLIP Fluids GitHub issue tracker is for issues and bugs only. Feature development and requests are handled internally and requests can be made through alternative channels. See: [Guidelines for Feature Requests](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests).
