### ISSUE TITLE
Cache-Error when saving into a new file

### ISSUE THREAD

**Issue by dafassi** [rlguy/Blender-FLIP-Fluids#294]
Whe saving a scene with a new filename and try to clear the cache or rebake- an error pops up.
Can the addon detect, when the filname will change and ask the user to move the cache-folder?

**Comment by rlguy** [comment]
Hey, what error is being displayed? Would you be able to provide exact steps to reproduce this issue?

**Comment by dafassi** [comment]
You can reproduce this issue:
1- save any prepared scene
2- Bake some fluids
3- After baking save the blend with another filename
4- click on reset bake

**Comment by rlguy** [comment]
This should be fixed now and will be included in the next version update (**1.0.3**)!
