### ISSUE TITLE
Baking flexiblity

### ISSUE THREAD

**Issue by dafassi** [rlguy/Blender-FLIP-Fluids#295]
The idea came on me as i extended my simulation after it has been finished.
I´ve baked 250 frames and thougt 50 frames more would be good.
So i set my sceneframes to 300 frames and clicked on resume (force).
But i did a mistake - meanwhile i put an edgesplit modifier on an obstacle.
That means from frame 250 to 300 the simulation went wrong, because the edgesplit modifier.
Now i have 300 frames baked, and the last 50 frames are wrong.
We would need to be able to repeat baking in every timerange to fix mistakes like i did here.
I know, my mistake was also to use "force". If this is not possible a hint "Attention, make sure your scene objects have not been changed" would be a good idea. What do you think?

**Comment by rlguy** [comment]
Hey Dennis, this type of thing has been requested by many users lately, so you're not the only one who wants this implemented! I have created this feature request that will add this functionality: #296
