### ISSUE TITLE
[Feature Request] Decoupled Baking (bake fluid, mesh, whitewater separately)

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids#296]
This is a feature that has gotten a lot of requests during the beta and many more since the release on May 1st! 

This feature would separate the fluid simulation stages into separate baking operations:
- **Fluid Particle Simulation** - Simulate just the fluid particles. The user would also be able to re-simulate the particles starting at any frame during the simulation.
- **Mesh Generation** - Generate the surface mesh from the fluid particles. This stage would require the _Fluid Particle Simulation_ stage to be simulated as a prerequisite. The user would be able to select any frame range to mesh/remesh.
- **Whitewater Generation** - Simulate just the whitewater particles. This stage would require the _Fluid Particle Simulation_ stage to be simulated as a prerequisite. The user would also be able to re-simulate the whitewater particles starting at any frame in the simulation.
- **Bake Everything** -  This will be the same as how the addon bakes now. The user would be able to go back and remesh and resimulate whitewater if needed. Or rebake starting from any frame.

This is a feature that I have been putting a lot of thought into and am quite excited to get this implemented into the addon. This is quite a large feature to add, but I think that addon is currently in a state where this is the right time to begin work on adding this feature. It will be much easier to add this feature now, rather than later after other planned features are added.

### Notes
- Decoupled baking will require much more data to be saved to the cache. For large simulations, the caches will become very large. The largest piece of extra data will be saving the fluid simulation particles. Extra data will also need to be saved for the whitewater particles. 
- Due to the larger cache requirements, decoupled baking should be optional. If decoupled baking is disabled, the addon will bake how it does now and will not save extra data to the cache.
- There should be a cache operator to delete all extra data. Once the user is satisfied with the entire simulation, this operator can be used to free data that will no longer be needed.
- Decoupled baking will require better control over how simulation settings/meshes are exported/re-exported. The way these settings/meshes are exported should be redesigned for a better workflow. There should be separate options/operators for re-exporting domain settings (fast), and re-exporting animated meshes (slow for complex meshes). Exporting settings and meshes should be decoupled so that when a simple simulation setting is updated, animated mesh export does not need to be re-run.
- Consider adding options/operators for compressing the simulation cache (#325). 

If you have any thoughts on this feature, feel free to comment!

**Comment by PavelBlend** [comment]
I would like to be able to render FLIP particles. For FLIP particles to be on par with White Water particles. This will allow rendering such videos with particles:
https://vimeo.com/102554547
That is, you need to make sure that each stage of baking can be rendered.

**Comment by rlguy** [comment]
It will be possible to render all stages of simulation when this feature is finished. The plan is to implement the FLIP particles similar to the whitewater particles with a percentage slider for the amount to display and settings for particle object/icosphere and scale.

**Comment by rlguy** [comment]
My apologies for the ping on this issue thread, just cleaning up the FLIP Fluids GitHub issue tracker. 

The purpose of the FLIP Fluids GitHub issue tracker is for issues and bugs only. Feature development and requests are handled internally and requests can be made through alternative channels. See: [Guidelines for Feature Requests](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests).

Just adding a note: this feature has been moved to a new simulation engine project that will eventually replace the FLIP Fluids addon as a free upgrade.
