### ISSUE TITLE
Request: Gravity control

### ISSUE THREAD

**Issue by dafassi** [rlguy/Blender-FLIP-Fluids#297]
This is a feature request for gravity-control.
Id like to simulate fluids with zero gravity. Like seen in spaceship-films where drops can fly around and will be touched by humans. Or let inflows fly along a path (using pathanimations) like known from some cola-commercials ;).
Beeing able to animate a gravity-value would be great, too!

**Comment by rlguy** [comment]
Hey, the value of gravity can be set/keyframed in the FLIP Fluids World panel. Inflows following along curve objects will be implemented when support for Blender forces is added.

**Comment by dafassi** [comment]
Oh my fail - didn´t look there. Thank you!
