### ISSUE TITLE
Rotated domain doesn’t work

### ISSUE THREAD

**Issue by BlenderPete** [rlguy/Blender-FLIP-Fluids#302]
I added a cube and rotated it 55 degrees on the z-axis. I also moved it in x- and y-direction. I then applied rotation, scale and location. When I use this cube as a domain it acts in such a way that it uses the original size, location and scale. Am I doing something wrong or is it a bug?
I‘m using Blender 2.79b and downloaded the flipfluid addon today.

**Comment by rlguy** [comment]
Hello BlenderPete,

A requirement of the domain object is that it must be aligned to the Blender x/y/z axis' before baking. I have just added a note on this to the [Domain Documentation](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Object-Settings).

There is a feature request to allow the domain cache meshes to be rotated after the simulation. here: #286

**Comment by BlenderPete** [comment]
Hey rlguy,
Thanks for replying and adding my comment to the feature request.
I’m really excited to test the addon and see what’s possible.
Cheers, Pete
