### ISSUE TITLE
Particles Upscaled at Render Time

### ISSUE THREAD

**Issue by Jandals** [rlguy/Blender-FLIP-Fluids#308]
I don't have a lot of info on this issue, so I can't expect much help, but it happens so I'd at least like to see the information here.

A number of particles seem to be scaled much larger than others at render time.
It doesn't appear to be all of the particles of any type, it seems to be individual particles which are affected.
It doesn't happen on every frame; random frames are affected and it looks like it can be different frames each render.
It doesn't show up in the viewport.

Python reports "internal state bug.  This should not happen."

![waterfall r0086](https://user-images.githubusercontent.com/5439245/40221340-1015fe2a-5a31-11e8-9445-956e8530c98f.jpg)

**Comment by rlguy** [comment]
Hey Jandals,

I have actually seen this before. It seems to be an issue with Blender/Cycles not applying transformations properly before rendering. I tested this by removing the simulator and copying the meshes into a scene and repeatedly rendering and this issue still occurred. It seems to be dependent on the system for me. This happens on my laptop, but not my desktop.

I am wondering how frequent this happens for you? About how many frames does this occur in a render. For me this happens very infrequently. I would like to report this to Blender but it is difficult to reproduce.

**Comment by Jandals** [comment]
I rendered out this animation and had 8 "defective" frames out of 120. I stopped another render after 35 frames and it had 6 errors in it. 

I started a new file with a much simpler collider and rendered with no errors. I thought it might be connected to large memory use on bigger files since the file that gave me the picture I posted is about 300 MB. And I have gotten a few "Error: EXCEPTION_ACCESS_VIOLATION" messages from the system console when Blender crashes during rendering...

It DOES seem like transforms aren't being properly applied, but I can't reproduce it either so why it's happening is a mystery.

**Comment by rlguy** [comment]
Thanks for the update,

Here is a tip that has seemed to help others with render crashes and keep the render more stable:

Setting the render display to _Full Screen_:
![full_screen](https://user-images.githubusercontent.com/4285191/40271981-7429cf3e-5b5a-11e8-9b3f-51f38d4a37c1.jpg)
 
This tip was recommended by a Blender developer as a workaround to an unstable 3d viewport.

**Comment by rlguy** [comment]
Good to know! I have added this tip to a [Scene Troubleshooting](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#blender-often-crashes-suddenly-or-does-not-apply-transforms-while-rendering) document.
