### ISSUE TITLE
[Feature Request] Network baking

### ISSUE THREAD

**Issue by rslittle** [rlguy/Blender-FLIP-Fluids#309]
IF this can be done would love to know how. (still blender newb.)  If not, network sims would be really nice if its possible (Houdini does it for just $4420 more :-) )

**Comment by rlguy** [comment]
This is not implemented in the simulator and likely will not be implemented. This is a quite a massive feature and we do not have the resources to add something like this.

**Comment by rslittle** [comment]
All good Ryan. I did put the demo on my LInked in page and about every
major studio and a whole bunch of others have looked at this work.  Its
pretty amazing work sir.


Randy S. Little
2017 Emmy Award Outstanding VFX for Gotham.
http://www.rslittle.com/
*http://www.imdb.me/randylittle <http://www.imdb.me/randylittle>*

**Comment by rlguy** [comment]
Thanks for the kind words and for the exposure! And that's an amazing portfolio you have.
