### ISSUE TITLE
CPU utilization when GPU off very low?

### ISSUE THREAD

**Issue by rslittle** [rlguy/Blender-FLIP-Fluids#310]
Ok Im sure im just newbing all this so some help would be great.  Im owning this for all of 20 min now :-)

I'm just playing with baking the viscous_net.  the only thing I have changed is GPU off and resolution set to 100.  I am getting 10-15% CPU utilization. (GPU on or off)  Windows 10 Pro with latest updates.  (1806?)  Dual XEON e5 2680's with 64Gig RAM.  Geforce 970 but its off in flip settings.  

Any help would be great

What is the expected (averageish) sim time for people with this file?

![image](https://user-images.githubusercontent.com/248002/40243184-9970d512-5a8d-11e8-8402-f9077e8d3afa.png)

**Comment by rlguy** [comment]
This this document on CPU/GPU usage:

https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Frequently-Asked-Questions#my-cpu-is-running-under-100-usage-while-simulating-is-this-normal

There is a note in there for users with many cores such as Xeon hardware.

There was a beta tester using a XEON e5 2680 and they ran the Viscous Net demo without any settings modifications at 65 resolution in 35 minutes.

**Comment by rslittle** [comment]
The solution was to put in a way faster SSD or other superfast solid state
drive.  even a crappy old ocz at 250 MBs sent my cpus up 20% (dual 2680 V2)
So maybe the issues is to much data for slower drives bottleneck.

Randy S. Little
http://www.rslittle.com/
*http://www.imdb.me/randylittle <http://www.imdb.me/randylittle>*

**Comment by rlguy** [comment]
This is some great info, thanks for the update! Perhaps there could be some optimizations to make for slower storage mediums, this will be something to think about.
