### ISSUE TITLE
Feature request: Particle Obstacles

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids#312]
Hi,

At the moment there does not appear to be a way (or at least I don't know it) to have a particles system which uses dupi objects (and I am also guessing groups) which are obstacles.

For example I set up a simple scene where particles (as sphere dupli objects) fall on to the fluid but it does not do anything.  I also tried caching the sim but this did not help.

I had a little success using the particle instance modifier however, this still requires unborn and dead particles to remain on at all times makes it practically not usable.

Having this feature would be quite helpful I think.

**Comment by rlguy** [comment]
Hey RevDr,

This was a planned feature early in development, but unfortunately it was not possible to add. There does not seem to be a way to retrieve the mesh geometry after dupli objects are applied to a particle system (or mesh vertex system) using an addon.

**Comment by RevDr** [comment]
I am probably being too simplistic here (so excuse my ignorance)...

Rather than trying to access the each dupliobject mesh - is it possilble to grab the dupli object and also the particle positions, rotations and scales and then apply those transforms to the mesh verticies?

...just a thought

**Comment by rlguy** [comment]
Blender's interface to access particle systems using an addon is quite lacking so we don't have a way to grab all of the required data. I hope in the future Blender adds more functionality for particle system scripting because it would make many things simpler to implement within the addon.
