### ISSUE TITLE
DAG Zero error

### ISSUE THREAD

**Issue by RevDr** [rlguy/Blender-FLIP-Fluids#313]
Hi,

Just noticed a "DAG zero....  not allowed to happen error" in system console.

To repeat....
1. Start blender
2. From physics tab press Flip Fluid
3. Change type to domain
4. Error should appear

**Comment by rlguy** [comment]
Hey RevDr,

This is a bug within Blender's dependency graph and seems to happen occasionally whether or not the FLIP Fluids addon is installed. I don't seem to get the error when initializing the domain, and it is usually on startup. This will also often happen for me when I have multiple Blender windows/instances open. It seems to be harmless.

- Ryan
