### ISSUE TITLE
[bug] fluid object misaligned with obstacle objects

### ISSUE THREAD

**Issue by guitartom47** [rlguy/Blender-FLIP-Fluids#315]
Earlier with the beta builds, I never noticed this slight misalignment of the obstacles with the fluids - now it's really bothering me.

Also, I've been trying lately to make good looking tall waterfalls over uneven surface - but failing. The fluid seems to be wild and stringy even though I've switched completely to PIC - and used many substeps and increased resolution. Perhaps you might have some helpful hints as to settings? I'm still experimenting.
[edit: I would also observe that white water objects are misaligned as well.]

Included is a file that I hope will show the misalignment along all three axes:

https://1drv.ms/u/s!AuL_h2DNeOJch-AWeqCbqByl4WxtJA

**Comment by rlguy** [comment]
Hey guitartom47,

Thanks for reporting this! I just had a chance to look at the .blend file. There was a bug that was causing meshes to be misaligned when world scaling was enabled. This bug has been fixed and will be included in the next version update (**1.0.3**, hopefully available next week). Until that version is available a workaround is to either translate the domain or obstacles to manually align the meshes for rendering. Sorry for the inconvenience!

To create a waterfall sim like this I would suggest creating some realistic terrain/obstacle conditions for a waterfall. Right now, fluid is dropping ~10m directly onto a flat surface which can cause some harsh pressures/velocities that can fling particles around. Here are some notes that I suggested to another user interested in waterfall simulation:

> For waterfalls, I would create some good starting conditions for whitewater generation. I would start by creating a turbulent flow to generate bubbles and interesting velocities before the waterfall begins. Such as pouring fluid into a rocky basin before it falls over the edge. Having objects for the waterfall to hit on the way down could create interesting splashes and opportunities for the simulator to create whitewater. I would also use the World Scaling option to create a realistic waterfall size.

For each level of the waterfall, I would create a basin of fluid for the falling water to collect into before falling over to the next level. Another suggestion I would make is to increase the size of the inflow object to generate more fluid. After some of these changes you may find the fluid is less chaotic, so lowering the PIC to FLIP ratio back down to 0.05 - 0.3 for a more accurate simulation might be good.

Here is an animation of a similar scenario except that the flow is more horizontal than vertical: https://gfycat.com/UniformQuarterlyKid

Hope this helps!

- Ryan

**Comment by guitartom47** [comment]
Thanks for your attention in this, Ryan! I've got some other possible world scaling problems to share with you now. I'm only testing for this last night and today- and I wish I'd done it earlier during Beta. For my rapids, I wasn't familiar enough with the addon so I just scaled everything up and it all worked great. However, I think that ther are some other problems with world scaling.

I'm including a link to my test files so you can decide for yourself if what I'm seeing is real.

Here's what I'm seeing. With just scaling all the objects (I applied scale - don't know if that makes a difference) everything seems to work as expected.

When using world scale, I see differences in white water particle numbers (much less), proportional differences in the fluid as far as distance traveled, and I think that the FLIP/PIC ratio becomes much less useful as far as stabilizing the simulation. In the world scaling, the fluid becomes explosive - I've been fighting this issue with a waterfall scene I've been working on - so much that I tried adding miniscule amounts of viscosity - which makes everything ropey.

link: https://1drv.ms/f/s!AuL_h2DNeOJch-AXT0TLMvPCwjOBtQ

**Comment by rlguy** [comment]
guitartom47,

I just checked out the .blend files. There is a difference in size between the two setups:

The .blend with world scaling enabled will be a size of 40m:
![world_scaling](https://user-images.githubusercontent.com/4285191/40567727-787173aa-602b-11e8-8a7e-59fbc1e79a30.jpg)

The .blend without world scaling will take on the size in the viewport (80m). Note: the world size menu will display the viewport size here:
![no_world_scaling](https://user-images.githubusercontent.com/4285191/40567752-90ede5ee-602b-11e8-959d-babf8c4bb009.jpg)

A note on whitewater: the size of the domain will generally affect the amount of whitewater. The 
[Min/Max Energy Speed](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Whitewater-Settings#whitewater-emission-settings) settings in the Whitewater panel will control at what fluid speeds (m/s) whitewater will be generated. For larger domains, fluid generally moves faster and will generate more whitewater than small domains where fluid generally moves slower and generates less whitewater.
