### ISSUE TITLE
CPU Usage only at 40%

### ISSUE THREAD

**Issue by k1ff** [rlguy/Blender-FLIP-Fluids#319]
Hi Ryan,

So I never noticed this before because I never opened the Task Manager while simulating, but my CPU is only sitting at 35-45% while simulating. Surely I am missing something... I could be simulating so much faster if it was at 100%!

**Comment by rlguy** [comment]
Hey k1ff,

The short answer is that fluid simulation is a difficult problem for computers to utilize 100% of the CPU. Some more detailed explanation here: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Frequently-Asked-Questions#my-cpu-is-running-under-100-usage-while-simulating-is-this-normal
