### ISSUE TITLE
[bug] Blender Crashes When I try to render the fluid

### ISSUE THREAD

**Issue by filmicAndSons** [rlguy/Blender-FLIP-Fluids#323]
I've bought the blender add-on "Flip Fluid" and am working with it since a few days. It works correctly most of the time, but I've run into a crash and I have no clue where it comes from.

Sometimes, after my fluid is baked, I try to render and the whole program just closes at the "initialization" phase. It only does so if there is a liquid in the scene. As soon as I delete the mesh the render works fine.

I've tried several things, made sure that there was no accent (éèà...) in the file path (a bug I had with elbeem), tried on several machines (on OSX and on W10) but nothing seems to work.

The only solution I found was to re-bake everything. But it's quite long, and doesen't guarantee me to never run in this problem again.

Does any one know how to avoid my blend to crash with flip fluid?

thank's !

PS: this is a repost from my question on [stackexchange](https://blender.stackexchange.com/questions/109791/flip-fluids-add-on-blender-crashes-when-i-try-to-render-the-fluid)

EDIT : that only happens with cycles, not with blender internal.

**Comment by rlguy** [comment]
Hello filmicAndSons,

Would you be able to let me know if this workaround helps prevent render crashes:  [Scene Troubleshooting: Blender often crashes suddenly or does not apply transforms while rendering](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#blender-often-crashes-suddenly-or-does-not-apply-transforms-while-rendering)

>> ### Blender often crashes suddenly or does not apply transforms while rendering
>>
>> This can be caused by instability handling large meshes in the 3D viewport. At the moment the cause is unknown, but a workaround that commonly fixes the issue is to set the _Render Display_ to _Full Screen_ ([**Blender Render Properties Documentation**](https://docs.blender.org/manual/en/dev/render/output/render_panel.html#display)).

![render_display](https://user-images.githubusercontent.com/4285191/40790736-8560ac7e-64aa-11e8-81b7-07cce85c3b21.jpg)

\- Ryan

**Comment by filmicAndSons** [comment]
My renders seem to work fine with that trick. Thank you !

**Comment by rlguy** [comment]
Great to hear the trick worked for you! This trick has worked for everyone so far, so it seems like the issue is related to the Blender viewport display being open during render.
