### ISSUE TITLE
Compress fluid cache?

### ISSUE THREAD

**Issue by philstopford** [rlguy/Blender-FLIP-Fluids#325]
It looks like there's a good amount of slack space in the cache files - I could compress some basic examples to roughly 10% of the size on-disk. Is compression something that could be considered?

**Comment by rlguy** [comment]
Hey philstopford,

In general, lower resolution caches will compress quite a bit. Higher resolution simulations will compress less (80%-90%) of original size.

The addon actually used to lightly compress cache files, but it led to user experience issues and compression was removed. Some of the reasons why cache files are no longer compressed:
- Large increase in bake time. For large meshes, the compression process took a very long time and added too much time to the bake.
- Drastically increased simulation playback time. Decompressing large meshes could add 10+ seconds to frame loading.
- Interference with whitewater simulation playback optimizations. The whitewater particles are stored in a 'streaming' format, meaning that if previewing whitewater or setting display % less than 100, only a portion of the whitewater mesh file needs to be read from the cache. If compressing whitewater, the entire file would need to be decoded before reading which increases time for whitewater playback.

**Comment by philstopford** [comment]
Might it be useful as an option for rendering stages, particularly to ease load on file servers and similar?

**Comment by rlguy** [comment]
The simulation cache is currently undergoing some major changes due to a 'Decoupled Baking' feature (#296), so I'll consider this while implementing the feature. A note about this functionality has been added to the feature issue.
