### ISSUE TITLE
ImportError: cannot import name 'MappingProxyType' Bug that doesn't allow me to extrude

### ISSUE THREAD

**Issue by pembyy** [rlguy/Blender-FLIP-Fluids#327]
This error pops every time I extrude something in Blender. This happened once installed Flip onto Blender.
I need some help to fix this problem.
![30540fcdbee7c8057e0502850fc1f4f4](https://user-images.githubusercontent.com/31707004/41001675-7e9ee890-68c6-11e8-989a-d8597f13d57a.png)

**Comment by rlguy** [comment]
Hello pembyy,

Does this error still happen if you uninstall the addon? This error looks like a problem with the Blender installation. Would you be able to attach your Blender system info file for me to check out (**Blender > Help > Save System Info**)?

**Comment by pembyy** [comment]
Yes I did uninstall it, but it still exists within Blenders files.
For some reason, when I save my system info, it leads to another error message.
![2676a234cf1d5d4813e4af02aebaceaa](https://user-images.githubusercontent.com/31707004/41054026-140ad834-6972-11e8-934f-ae5cdba8d9b7.png)
But I do have the System Console log as a txt file
[SystemConsole.txt](https://github.com/rlguy/Blender-FLIP-Fluids/files/2077382/SystemConsole.txt)

**Comment by rlguy** [comment]
Thanks for attaching the error message!

Since the error is not occurring when the addon is uninstalled, this issue will be unrelated to the FLIP Fluids addon. The addon does not alter any of Blender's internal files and is not able to affect files after it has been uninstalled.

The full error message shows that the error is originating from an addon called **archimesh**:

> File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_u
> tils.py", line 331, in enable
>     mod = \_\_import\_\_(module_name)
>   File "C:\Program Files\Blender Foundation\Blender\\**2.79\scripts\addons\archimesh**\__init__.py", line 63, in <module>

\- Ryan

**Comment by pembyy** [comment]
Oh okay! Thanks for the information!

**Comment by rlguy** [comment]
No problem, hope you're able to sort out the issue without too much trouble.
