### ISSUE TITLE
[Feature Request] Whitewater Emitters: Add functionality for objects to emit whitewater particles

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids#334]
Add the ability to have objects emit whitewater particles. This feature will likely be implemented into the UI as additional setting in the Fluid/Inflow object parameters.

Example Effects:
- Dissolving pill in a glass of water
- Bubble 'tracer' particles in a viscous honey pour
- Fluid flow visualizations
- Carbonated drinks

**Comment by PavelBlend** [comment]
I would like to be able to get random particle sizes. Like here:
https://vimeo.com/130118827
Is it realizable?

**Comment by rlguy** [comment]
That's a nice looking effect! I will take this into account when I implement this feature.

Random particle sizes will only be possible if we implement whitewater as a particle system. We do plan to add an option to convert whitewater into a particle system and we have done some testing with this. There are particle system performance problems if there are a large number of particles (millions), but it should be fine for simulations with a small number of particles such as this one.

Note: For Blender 2.80, there have been major performance improvements for large particle systems.

**Comment by rlguy** [comment]
My apologies for the ping on this issue thread, just cleaning up the FLIP Fluids GitHub issue tracker. 

The purpose of the FLIP Fluids GitHub issue tracker is for issues and bugs only. Feature development and requests are handled internally and requests can be made through alternative channels. See: [Guidelines for Feature Requests](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests).
