### ISSUE TITLE
Addon Install

### ISSUE THREAD

**Issue by pierreee1** [rlguy/Blender-FLIP-Fluids#336]
Hello, I've tried to install the addon by all the possible ways I know. I'm using Blender 2.79b, the latest version I think. Once I click on the .zip file, Blender says "Modules installed..." as a normal installation but then it won't appear on the Add-ons tab to enable it. Am I missing something?
![blender user preferences 14_06_2018 11_08_23 p m](https://user-images.githubusercontent.com/19770567/41449644-db07aece-7027-11e8-9946-9d5196cf8964.png)

**Comment by pierreee1** [comment]
Hello, thanks for replying. If I download the repo I get the usual .zip file:
![captura](https://user-images.githubusercontent.com/19770567/41476378-fffde1f8-7086-11e8-84fb-ba8255e7fa61.PNG)
When I unzip it I get a folder with all the stuff:
![2](https://user-images.githubusercontent.com/19770567/41476404-1555ccd2-7087-11e8-84f2-8b712ac711e9.PNG)
Do I have to zip a folder inside that one?

**Comment by rlguy** [comment]
Hello, the FLIP Fluids addon is not installable through the repository source. This repository only contains the source code for the addon.

See the **Getting the FLIP Fluids Addon** section of the readme, or visit the product page here: https://blendermarket.com/products/flipfluids

**Comment by KFFTFUFTUR** [comment]
but isn't it possible to build the addon from source?
