### ISSUE TITLE
Addon installation issues

### ISSUE THREAD

**Issue by vvittalasm** [rlguy/Blender-FLIP-Fluids#338]
please tell how to install the addon. i am struggling.

**Comment by rlguy** [comment]
Hello, please let me know what you are struggling with. Instructions for installing the addon can be found here: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Addon-Installation-and-Uninstallation

**Comment by leandr-o** [comment]
I follow the instructions in the installation page, but nothing happens. I see the addon folder gets placed in the scripts folder inside AppData, but it wont appear in the addon list inside blender.
I also tried place the unzipped folder inside Scripts folder located in 'Program Files' and wont work either. Not even the Demo .zip file work.

![add-on](https://user-images.githubusercontent.com/40670949/42048940-950b1284-7ad2-11e8-8ba7-3b62006fa468.jpg)

**Comment by vvittalasm** [comment]
Same happening with me..

**Comment by rlguy** [comment]
Hello,

Are you receiving any error messages when you install the addon? You can view error messages with **Blender > Window > Toggle System Console**.

Also, are you using the GitHub version of the addon, or the Blender Market product?

**Comment by leandr-o** [comment]
I toggled the Console ON and the only message was this below:
`Modules Installed () from 'C:\\Users\\Leandro\\Desktop\\Blender-FLIP-Fluids-master.zip' into 'C:\\Users\\Leandro\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons'`

> Also, are you using the GitHub version of the addon, or the Blender Market product?

And tried both versions, this one here and the Market one. The same message gets diplayed.

**Comment by rlguy** [comment]
Thanks for the update. The GitHub version is not installable without first compiling the program. Only the Blender Market version will install 'out of the box'. This is odd that the demo version is also not working for you.

Would you be able to try something:
1. Delete all files in your addons folder related to FLIP Fluids
2. Attempt to reinstall the Blender Market version
3. Attach your Blender System Info file for me to check out (**Blender > Help > Save System Info**)

And also verify that the addon installed correctly. If the addon installed correctly, you should have the following file:

```
C:\\Users\\Leandro\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\flip_fluids_addon\\__init__.py
```

**Comment by kshackleton** [comment]
Having the same issue, using the GitHub version, gone through the installation guide, looked at the console and getting to the same point of the script were it ends at "scripts\\addons". what more needs doing to this version to get it to install the same as the market version

**Comment by rlguy** [comment]
Hello kshackleton,

This issue thread is regarding installation of the Blender Market version of the addon, not the GitHub version. The installation guide states that the instructions are only for the Blender Market version.

We are only able to offer technical support for the Blender Market version of the product. See our [CONTRIBUTING.md](https://github.com/rlguy/Blender-FLIP-Fluids/blob/master/CONTRIBUTING.md#using-the-issue-tracker) file.

\- Ryan

**Comment by rlguy** [comment]
This issue has seemed to have gone stale, so I will be closing this. 

If anyone is having trouble with installation of the Blender Market product, do not hesitate to contact us through the Blender Market messaging system and we would be glad to help!
