### ISSUE TITLE
The fluid seems to not recognize the path of my character with collision!

### ISSUE THREAD

**Issue by EmigeDaniel** [rlguy/Blender-FLIP-Fluids#345]
The fluid of my scene is having a calculation delay in the obstacle of the object, my character is animated and already tried in many ways to solve this but I nothing works...There are also other problems
![helpx](https://user-images.githubusercontent.com/39391046/41825275-e6936052-77f3-11e8-8298-3fb1107374ca.gif)

**Comment by rlguy** [comment]
Hello EmigeDaniel,

Is the **Export Animated Mesh** option enabled on the obstacle object? ([Documentation Here](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Obstacle-Object-Settings#parameters))

Also, is your obstacle mesh Manifold? Results can be unpredictable when using non-manifold meshes. Tip: you can highlight non-manifold parts in 'Edit Mode' with **ctrl + alt + shift + m**. ([Documentation Here](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Manifold-Meshes))

\- Ryan

**Comment by EmigeDaniel** [comment]
Thank you! I didn't know that, it's all working now.

**Comment by EmigeDaniel** [comment]
You should add fluids to the particle system I think would be more optimized the collision system would be on account of the particles, the fluid would just follow the ride of the particles.

**Comment by rlguy** [comment]
Great to hear that this is working! 

Our fluid engine works independently and does not communicate with Blender while running a simulation. This means that we do not have access to Blender for fluid particles. We use our own particle and collision system within the fluid engine to handle fluid physics and this is what makes this simulator a FLIP-based solver.
