### ISSUE TITLE
[Feature Request] openVDB Nodes 

### ISSUE THREAD

**Issue by ruchitinfushion** [rlguy/Blender-FLIP-Fluids#347]
integrate **openVDB** in Blender Flip Fluids like in Houdini

Nodes List

1. **vdb_From_Polygons** : Convert polygon surfaces into VDB volume
2. **vdb_From_Points** : Convert pointCloud or Particles into VDB volume
3. **vdb_Smooth** : Smooth out the values in a VDB volume
4. **vdb_Smooth_SDF** : Smooths out signed distance fields values in a VDB volume primitive.
5. **vdb_Advect_Points** : Moves points in the input geometry along a VDB velocity field
6. **vdb_Activate** : Activates voxel regions of a VDB for further processing
7. **vdb_Activate_SDF** : Expand or contract signed distance fields stored on VDB volume primitives
8. **vdb_Advect_SDF** : Moves signed distance fields VDBs in the input geometry along a VDB velocity field
9. **vdb_Analysis** : Computes an analytic property of a VDB volumes, such as gradient or curvature.
10. **vdb_Clip** : Clips VDB volume primitives using a bounding box or another VDB as a mask
11. **vdb_Combine** : Combines the values of two aligned VDB volumes in various ways
12. **vdb_Resample** : Re-samples a VDB volume primitive into a new orientation and/or voxel size.

[openVDB official Site](http://www.openvdb.org/)

**Comment by rlguy** [comment]
Hello ruchitinfushion,

Thank you for your suggestion. However, we will likely not be adding support for OpenVDB features. We're a small team and do not have the necessary resources/time to implement a large feature such as this. Issue here: #168 

Best Regards,
Ryan
