### ISSUE TITLE
[Feature Request] Custom Force Field & buoyancy using openVDB

### ISSUE THREAD

**Issue by ruchitinfushion** [rlguy/Blender-FLIP-Fluids#348]
Many times user need more control over motion of fluid.

For example:
1. Fluids moving on nurbs curve  (vector field using tangent of nurbs curve)
2. crown Splash  (vector field using double crossProduct of surface normal of splash model )
3. Tornado  (vector field using twisted quaternion + perpendicular to ground)
4. Impact Dust  (vector field using reverse of impact vector)
5. etc.

Using openVDB we can make velocity vector field grid which can be use as custom force field & buoyancy to inject in your FLIP solver.

[openVDB official Site](http://www.openvdb.org/)

**Comment by rlguy** [comment]
Hello ruchitinfushion,

Thank you for your suggestion. However, we will likely not be adding support for OpenVDB features. We're a small team and do not have the necessary resources/time to implement a large feature such as this. Issue here: #168 

We do have plans to add our own fluid forces as this is a popular request: #269

Best Regards,
Ryan
