### ISSUE TITLE
[Feature Request] Render Liquid surface directly at Rendertime without meshing

### ISSUE THREAD

**Issue by ruchitinfushion** [rlguy/Blender-FLIP-Fluids#349]
Houdini and many renderer support rendering signed distance fields/openVDB level
set as a surface directly at rendertime without meshing or converting openVDB to polygon.

So it will be great if Blender FLIP solver gives this feature. will save lot of time.

**Comment by rlguy** [comment]
Hello ruchitinfushion,

Thank you for your suggestion. However, we will likely not be adding support for OpenVDB features. We're a small team and do not have the necessary resources/time to implement a large feature such as this. Issue here: #168 

Also, I am wondering if you know of a method to render a signed distance field within Blender Cycles? The simulator already calculates a signed distance field internally, so it could be a useful feature if possible.

Best Regards,
Ryan
