### ISSUE TITLE
No fluid mesh showing

### ISSUE THREAD

**Issue by Esimacio** [rlguy/Blender-FLIP-Fluids#351]
I have baked a 400 Frames, with the resolution 300. when trying the animation in preview, i cant see any fluid mesh, just the white water particles. the preview resolution is set to 32. this is very frustrating. I might use the 30 day satisfaction garanty.

**Comment by rlguy** [comment]
Depending on the type of simulation, a low preview value may not be enough to capture any detail of the final fluid mesh, especially fine details of the 300 resolution final mesh. Contact me on the Blender Market and we can discuss this.

**Comment by Esimacio** [comment]
yeah okay. sounds perfect
