### ISSUE TITLE
[Feature Request] Add functionality to set weight map for obstacle surface characteristics (friction, etc.)

### ISSUE THREAD

**Issue by philstopford** [rlguy/Blender-FLIP-Fluids#360]
I couldn't see this in the UI, so it doesn't appear to be possible right now. I'd like to be able to use weight maps to define surface characteristics on collision objects (e.g. friction), allowing for more artistic control of the simulation.

**Comment by rlguy** [comment]
Hello philstopford,

There is not a way to do this in the UI at the moment, but this does sound useful so I'll add this as a feature request!

For next time, please read our [Technical Support Guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines) and [Feature Request Guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests). These documents have recently been added and help us manage requests.

Best Regards,
Ryan

**Comment by rlguy** [comment]
My apologies for the ping on this issue thread, just cleaning up the FLIP Fluids GitHub issue tracker. 

The purpose of the FLIP Fluids GitHub issue tracker is for issues and bugs only. Feature development and requests are handled internally and requests can be made through alternative channels. See: [Guidelines for Feature Requests](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests).
