### ISSUE TITLE
[Feature Request] Blender 2.8 testing

### ISSUE THREAD

**Issue by JulianNorton** [rlguy/Blender-FLIP-Fluids#362]
Hey there,
I just bought FLIP and was disappointed to see I couldn't test it out in 2.8. Is there anyway I can give you my email address to help test it?

**Comment by rlguy** [comment]
Hello JulianNorton,

Sorry to hear about the disappointment. The System requirements on the product page states that the addon only supports 2.79 at the moment.

As for 2.80 support, see the FAQ page here: [FAQ: Do you plan to support Blender 2.8?](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Frequently-Asked-Questions#do-you-plan-to-support-blender-28). We do plan to support Blender 2.8, but 2.8 is still too unstable for us to make all the changes necessary for support. Blender will not be finalizing the Python API for addons until September 19th 2018 and will not be releasing an official candidate until October 20th 2018.

When we have a build ready for 2.8 support, we will add it to the Blender Market downloads page.

For next time, please read our [Technical Support Guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines) document for how to request features and how to use the issue tracker.

\- Ryan

**Comment by JulianNorton** [comment]
I understand, I'm having fun with it in 2.79 :) Thanks for making this awesome plugin!

**Comment by schroef** [comment]
Disappointed that its not ready for not released product.... Thats is weird hahaha
