### ISSUE TITLE
Just curious: Mesh Generator

### ISSUE THREAD

**Issue by enzyme69** [rlguy/Blender-FLIP-Fluids#363]
I am curious with "Mesh Generator" part, is there a plan for Blender FLIP Fluid to allow mesh generation from Blender Particles, or perhaps from users provided point data, volumetric etc?

**Comment by rlguy** [comment]
Hey enzyme69,

We do not have plans to create a general-use particle mesher that is separate from the fluid simulator. I haven't tried it myself, but I've heard good things about the [Cube Surfer Addon](http://pyroevil.com/cubesurfer-addon-download/).

For next time, check out our [Technical Support Guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines) or [CONTRIBUTING.md](https://github.com/rlguy/Blender-FLIP-Fluids/blob/master/CONTRIBUTING.md) file for proper use of the issue tracker.

\- Ryan
