### ISSUE TITLE
[Feature Request] Add dust whitewater particles

### ISSUE THREAD

**Issue by lmoschcau** [rlguy/Blender-FLIP-Fluids#364]
Often when a wave breaks on a sandy beach the water picks up some sand. I would love to see the possibility to generate dust particles when the fluid is moving quick enough over a surface.

This would allow much more realistic ocean waves etc. to be generated. Here are two examples:
![breaking waves seen from top](https://ak8.picdn.net/shutterstock/videos/16911700/thumb/1.jpg)
![breaking wave seen from the front](http://i.dailymail.co.uk/i/pix/2014/03/11/article-2578228-1C2F7A7500000578-582_964x641.jpg)

It is possible to create very realistic simulations with the flip fluid addon. But especially in ocean / beach scenes extra realism could be gained by simulating interaction with the environment.

This feature could be achieved by adding a new whitewater particle type to render and display the particles. In addition as a control object a new FLIP fluid object type could be added or just referenced in the FLIP fluid settings. The particles should have a weight and should move accordingly. In addition it would be a major advantage to control the generation of particles with a texture. If this is not possible, would it be possible to let the flip fluid act like a force field? This way it could affect particles and also other objects.

**Comment by vmxeo** [comment]
Just to tag onto this part:

>  If this is not possible, would it be possible to let the flip fluid act like a force field? This way it could affect particles and also other objects.

Blender has the [Smoke Flow](https://docs.blender.org/manual/en/dev/physics/force_fields/types/smoke_flow.html) force field that uses a specified smoke domain as a source. Being able to specify in fluid domain as a force field would be a more versatile solution than creating another particle instance within FLIP Fluids. Depending on how the force field reads in the data from the domain, it might be easier too.

**Comment by guitartom47** [comment]
Here is an attempt to add dust and mist to the FLIP simulation:

https://youtu.be/N_Bx62UX7ME

To make the sand particles, I ran two different simulations - one with normal white water, and the other with just bubble particles with negative bouyancy. Each sim had its own cache name so I was able to export the 'sand' object as an alembic file and then import it back again into the normal white water sim.

In effect, the final sim had four types of white water! (I suspect both sims are not identical, but they were very close)

I think that this might be a possible though complicated solution to having ww particles of different size and mass.

Sadly, the 'sand' particles appear wherever there's turbulance. I tried making the beach object have much more white water effect - just for the sand, but that didn't seem to work well. In the end, I masked all sand particles except those closest to shore. IMO it doesn't look too bad and you can see the sand mixing with the waves a bit as they flow up the beach.

The mist was derived from a smoke simulation from a very short lived particle system emitting from the spray particles.

**Comment by rlguy** [comment]
Thanks for sharing! The result is VERY cool and helps give me ideas for how this feature could be implemented.

A dust/sand particle type could be implemented similar to the bubble particles. The particles could be generated based on turbulence and proximity to obstacles that have been marked as a 'dust/sand' generator.

**Comment by MoschcauL** [comment]
ok so i made a very rough implementation in the addon.
[https://youtu.be/Yplyo8ukfTs](https://youtu.be/Yplyo8ukfTs)
it works rather good. The simulation looks a bit basic but this is all my computer could do in a reasonable amount of time.

**Comment by rlguy** [comment]
Looks great! It's a nice coincidence that I was working on an area of the addon earlier today that will make this easier and cleaner to implement.

I have actually been taking a break from developing a large 'Force Fields' feature for this week and next week to set aside some time for maintaining other areas of the addon as well as adding small feature requests. I really like the idea of this feature. I'll make this a priority for tomorrow and next week's development.

**Comment by rlguy** [comment]
Here's an update on the feature! The implementation is near complete and my goal is to have this released in a new stable release before the end of November.

There are some new settings in the Whitewater Panel to configure dust generation:

![dust_whitewater_ui](https://user-images.githubusercontent.com/4285191/69103194-9c3e2500-0a19-11ea-8773-dc13f697a624.jpg)

Obstacle objects have a new setting for whether they will emit dust (default = True). This setting is also available in the Whitewater Panel near the bottom.

![dust_obstacle_ui](https://user-images.githubusercontent.com/4285191/69103252-c263c500-0a19-11ea-9b52-8ffbdb295a47.jpg)

Display Settings Panel has been updated to include the new dust particle type:

![dust_display_ui](https://user-images.githubusercontent.com/4285191/69103295-dc9da300-0a19-11ea-867b-939e9fc827bb.jpg)

Stats Panel has been updated to include data for the new dust particle type:

![dust_stats_ui](https://user-images.githubusercontent.com/4285191/69103325-f63eea80-0a19-11ea-9234-e1c8e1c24c0e.jpg)

**TODO:**
- Test feature and find suitable default values (both UI values and internal simulation values)
- Update Material Panel to include new dust mesh
- Produce test renders

**Comment by MoschcauL** [comment]
This looks amazing. I'm really excited to finally see this feature in an official release.
In the rough implementation I did, the dust emission on an object is controlled trough an emission strength parameter. From this a dust emission strength influence grid is generated (based on proximity to the surface of obstacles)

I'm quite new to c++ programming so the method i chose is probably not the most effective one. But I thought this would allow the user to have more control over the simulation. I don't know if it's really necessary and how difficult it would be to implement it in the new version.
![Screenshot from 2019-11-19 10-04-35](https://user-images.githubusercontent.com/35405331/69132296-1a4f0a00-0ab4-11ea-90ab-008d5dc8f030.png)

@rlguy have you thought about using a strength parameter? If so why have you decided against it? Just curious

**Comment by rlguy** [comment]
Thanks for the input! It sounds like our implementations are similar. A difference is that I am just using an on/off checkbox for the objects dust emission strength. This means the emission strength can only be 0.0 or 1.0. The amount of dust generated can be controlled globally using the _Dust Emission Rate_ parameter in the whitewater settings.

I like your system of using a _Dust Emission Strength_ parameter much better since it does allow for more control scaling a different emission strength for each object. It is also more consistent with the other Obstacle Property values in the UI. I've updated the implementation to use a strength value rather than an on/off checkbox.

Here's a test of a fluid flow against an dust generating obstacle: https://gfycat.com/unequaledglumkoi

And one using two obstacles with the strength parameters set at 0.25 and 1.0: https://gfycat.com/dimwittedquestionableallosaurus

**Comment by MoschcauL** [comment]
This looks extremely promising. I'm looking forward to the release.

**Comment by rlguy** [comment]
My apologies for the ping on this issue thread, just cleaning up the FLIP Fluids GitHub issue tracker. 

This feature had been added in an earlier version to the whitewater simulation feature: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Whitewater-Settings
