### ISSUE TITLE
Materials and presets missing?

### ISSUE THREAD

**Issue by superE03** [rlguy/Blender-FLIP-Fluids#366]
System Information

**Blender Version (including hash):**
Blender 2.79
**FLIP Fluids Version:**
1.0.2
**Operating System:**
Debian Testing "Buster"
**CPU:**
i5-7500 @ 3.8 GHz
**GFX:**
RX 480 8 GB
**RAM:**
16 GB DDR4 @ 2666 MHz
#### Describe the bug
I've compiled FLIP Fluids from source, and it runs perfectly, besides the material and presets sections being nonexistent. Is this intended behaviour? 

#### To Reproduce
Build from source with the latest AMD OpenCL, and standard versions of all other required libraries.

#### Expected Behaviour

I expected the options to be available.

#### Actual Behaviour

They were not.

#### Screenshots

![image](https://user-images.githubusercontent.com/26074452/43438756-5ae31284-947f-11e8-83e4-04a019ea853f.png)

**Comment by rlguy** [comment]
Hey superE03,

This is working as intended. From the [README.md](https://github.com/rlguy/Blender-FLIP-Fluids#license) file licensing section:

> ## License
> 
> This program uses multiple licenses. See the files ```LICENSE_GPLv3.md```, ```LICENSE_MIT.md```, and ```LICENSE_Standard_Royalty_Free.md``` for license details. In General:
> 
> - The Blender addon code is licensed under the GPL.
> - The fluid engine is licensed under the MIT license.
> - **Some addon content will be using a Standard Royalty Free license. This license may cover content such as media (images/textures/videos), Blend files, materials, presets. This content will only be included within the paid addon and will not be available on the GitHub project page.**

\- Ryan
