### ISSUE TITLE
multiple domains per blend file

### ISSUE THREAD

**Issue by lumpynose** [rlguy/Blender-FLIP-Fluids#368]
#### System Information

**Blender Version (including hash): 2.79b f4dc9f9d68b**
**FLIP Fluids Version: 1.03**
**Operating System: windows 10**
**CPU: intel**
**GFX: nvidia 1170**
**RAM: 16gb**

#### Describe the bug

The documentation states that there can be 1 domain object per scene but creating a second scene and adding a domain object to it doesn't work.

#### To Reproduce

Create a domain object in the first scene, adjust its settings.  Click on the + on the scene thing at the top in the info bar to create a New scene.  Create a domain object in the new scene.  Check the first scene and its domain object has been changed.  I also got a fluid_surface object magically appearing in the second scene, but not a child of the domain object, and I hadn't done any baking in either scene.

#### Expected Behaviour

A description of what you expected to happen.

#### Actual Behaviour

A description of what actually happened.

**Comment by rlguy** [comment]
Sorry about that, the documentation was unclear. What is meant is that there can be only one domain per Blend file. I have updated the documentation.

**Comment by lumpynose** [comment]
Thanks.  One per blend file is what I was guessing as well.
