### ISSUE TITLE
Error Baking Fluid Simulation

### ISSUE THREAD

**Issue by juanleonistico** [rlguy/Blender-FLIP-Fluids#369]
#### System Information

**Blender Version 2.79:**
**FLIP Fluids Version 1.0.3:**
**Operating System windows 10:**
**CPU intel 8 cores 2.67 ghz:**
**GFX quadro fx 580:**
**RAM 4:**

#### Describe the bug

Hi, i have a intel computer with 8 cores of 2.67 and a quadro fx 580 graphics card, i insalled direct x, the driver of the card, mega codec pack and netframeworks, but when i try to bake simulation, a message shows, Error Baking Fluid Simulation  "Unable to load fluid engine library <libblpyfluid.dll>. Try updating /reinstalling your system graphic drivers and try again" See system console for error info, 

#### To Reproduce

Provide descriptive instructions for how to reproduce the issue or how to use your .blend file.

#### Expected Behaviour

bake the simulation normally

#### Actual Behaviour

i dont know what driver should i install, because i try to install cuda and it says its not compattible with your graphics card.       thanks a lot, it doesnt bake

#### Screenshots

[system-info.txt](https://github.com/rlguy/Blender-FLIP-Fluids/files/2263864/system-info.txt)
![when search for gpu](https://user-images.githubusercontent.com/40776232/43737152-eef31d7e-9985-11e8-8cb3-5e644276f491.jpg)

**Comment by rlguy** [comment]
Hello juanleonistico,

Could you attach your Blender System Info file? This file can be save in Blender: **Blender > Help > Save System Info**.

\- Ryan

**Comment by juanleonistico** [comment]
thanks for reply, i have uploaded it in the first comment, the scene work perfect in other pc with amd 8 cores and a radeon graphics card, the fact is i need the 2 pcs for render the same simulation, i hope it can be fixed

**Comment by rlguy** [comment]
Thanks for the update!

The addon requires your graphics card to have OpenCL 1.1. But it looks like the Quadro FX 580 graphics card only has up to OpenCL 1.0. According to NVidia, the latest drivers should update your card for OpenCL 1.1.

From your system info, it looks like Blender is not able to detect OpenCL capabilities on your card, and our addon also cannot detect this. I am not sure how to update your card for this.

BUT there is good news: We have actually removed OpenCL from our addon entirely in the next update which will be available on August 11th. So you should be able to use the fluid simulator on this system in the next update.

Until the update is available, if all you need to use this system for is rendering a simulation from your other PC, you will be able to do that. OpenCL is only needed to run/bake a simulation. You will be able to playback and render a simulation cache without problems.

\- Ryan

**Comment by juanleonistico** [comment]
yeah, i am doing it now, thanks for helping me, i really appreciate it.
bye
