### ISSUE TITLE
Parented/linked obstacles don't have the correct position

### ISSUE THREAD

**Issue by Calvin1602** [rlguy/Blender-FLIP-Fluids#371]
#### System Information

Blender 2017-09-11 5bd8ac9
FLIP Fluids 1.0.3
Win10 64b
I7 6820HK
GTX980
16Go

#### Describe the bug

When an obstacle moves because its parent is animated, the simulation does not take its position into account.

[animationbug.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2280136/animationbug.zip)

#### To Reproduce

In the attached .blend, just run the simulation on the "Domain" object.

A similar issue is present when using constraints instead of parenting.

#### Expected Behaviour

The "Obstacle" cube should interact with the fluid.

#### Actual Behaviour

It doesn't, because FLIP doesn't update its internal position. It just uses whatever position the object had when the simulation began.

#### Screenshots

![ezgif-1-b70dbbcc01](https://user-images.githubusercontent.com/826277/43991022-69925658-9d64-11e8-84bf-b8745bbe60a0.gif)

**Comment by philstopford** [comment]
I think you need to set the export animated mesh option on the obstacle. This makes it work for me.

**Comment by rlguy** [comment]
Yes, the **Export Animated Mesh** option needs to be enabled. From the [Obstacle Documentation](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Obstacle-Object-Settings#parameters):

> **Export Animated Mesh**
> Export the obstacle object mesh as an animated one.
> TIP: Animated objects can be slower to export, so use this option only if necessary, such as for armatures or **parented objects**. Objects with keyframed position/rotation/scale do not require this option to be enabled.

This is a common issue and is also listed in the Scene Troubleshooting document: [Scene Troubleshooting: Animated Obstacle is Static When Running the Simulation](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#animated-obstacle-is-static-when-running-the-simulation)
