### ISSUE TITLE
[Feature Request] Air outlet and Wave-Maker

### ISSUE THREAD

**Issue by MarkOude** [rlguy/Blender-FLIP-Fluids#374]
It would be nice if there is a type of outlet that emits air bubbles as whitewater bubble. So that you can simulate a whirlpool etc.

And a Wave-maker. So, you add like a box and when you then enable the Wave-maker it moves and makes waves. sorry for this bad description...

Hope this can help you to make this plugin better...

**Comment by rlguy** [comment]
Hello MarkOude,

At this moment, we are not accepting further feature requests until we finish implementing some of the current feature requests.

From the [Feature Request Guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests) document:

> _Notice: As of August 7th, 2018 there will be a hold placed on proposing feature requests. This hold will be lifted once we finish working through some of the current popular feature requests. Feature requests at this time will not be accepted. Thank you for your patience._

We do plan to add whitewater emitters however. See the feature request here: #334
