### ISSUE TITLE
Fluid stuck in inflows mesh volume

### ISSUE THREAD

**Issue by pskl** [rlguy/Blender-FLIP-Fluids#375]
#### System Information

**Blender Version (including hash):**
**FLIP Fluids Version:** 1.0.4
**Operating System:** Windows 8
**CPU:** Intel i5
**GFX:** GTX 275
**RAM:** 8 Gigs

#### Describe the bug

Fluid inflows don't emit fluid but the fluid is doesn't go paste the volume of the emitter and just wobbles and stays put. This usually doesnt happen straight away but after some time manipulating scene elements.

#### To Reproduce

Try setting a fluid inflow and bake the fluid with a domain.

#### Expected Behaviour

Fluids flows based on according parameters.

#### Actual Behaviour

Fluid gets stuck in the volume of the emitter.

**Comment by rlguy** [comment]
Hello pskl,

Would you be able to attach a .blend file that reproduces this issue? Check out our [Bug Reporting Guidelines here](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Reporting-Bugs-and-Issues).

\- Ryan

**Comment by pskl** [comment]
I upgraded my setup recently with a new GPU and this seems to have solved the issue for me. Closing this unless someone bumps into this again. It was really weird.
