### ISSUE TITLE
Whitewater particles are huge

### ISSUE THREAD

**Issue by Haukii** [rlguy/Blender-FLIP-Fluids#378]
#### System Information

**Blender 2.79b**
**Flip fluids version 1.0.4a**
**Windows 10**
**Intel Coffee Lake i5-8400, LGA1151, 2.8 GHz, 9MB, Boxed**
**KFA2 GeForce GTX 1060 OC 6GB GDDR5**
**2x G.skill 8 GB Ripjaws V, DDR4 3200MHz, CL16**

#### Describe the bug
When I enable the whitewater generation and change nothing the particles will be huge and there is just few of them. I can't find a way to fix this.

#### To Reproduce
I don't know can you reproduce this with other computers

#### Expected Behaviour

I expected it to work normally

#### Actual Behaviour

the particles were huge and there were few of them. It didn't look like whitewater at all

#### Screenshots
![flipbug](https://user-images.githubusercontent.com/42744324/44668325-c034d580-aa25-11e8-99ff-4f9e66b26cd9.PNG)
![flpbug](https://user-images.githubusercontent.com/42744324/44668421-0db14280-aa26-11e8-9e8f-402941e04860.PNG)
![panel](https://user-images.githubusercontent.com/42744324/44668425-10139c80-aa26-11e8-95bc-10905898bf33.PNG)
[vesikuutio (2).zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2324513/vesikuutio.2.zip)

**Comment by rlguy** [comment]
Hello, see these documentation topics:

[Scene Troubleshooting: Whitewater particles are too large/small when rendered](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#whitewater-particles-are-too-largesmall-when-rendered)

[Scene Troubleshooting: Simulation not generating enough whitewater (foam/bubble/spray)](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#simulation-not-generating-enough-whitewater-foambubblespray) - Tip 2 should help

\- Ryan
