### ISSUE TITLE
Blender 2.79 nightly builds crashing on startup (Blender bug)

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids#379]
Hello everyone!

We have had a report that the FLIP Fluids addon is causing a crash during startup using the [Blender 2.79 nightly builds](https://builder.blender.org/download/). Disabling the addon by removing the _blender_flip_fluids_ folder from the Blender addons directory allows Blender to start up without crashes.

Is anyone else is experiencing this issue with the Blender 2.79 nightly builds? A simple **Yes** or **No** answer would greatly be appreciated!

If your answer is _**Yes**_, providing your system information could help us. Example:

- **Blender Version:** Blender 2.79 (5d8ac9)
- **FLIP Fluids Version:** 1.0.4
- **Operating System:** Windows 10
- **CPU:** Intel i7-7700 @ 3.60GHz
- **GFX:** GTX 1080, 8GB
- **RAM:** 32GB

**_Note:_** the Blender version hash (5d8ac9) can be found in the upper-right corner of the splash screen when you start up Blender. The addon version can be found in the Blender addon preferences menu.

**Comment by Corefrecs** [comment]
Yes, but after restarting my PC, everything seems to work again?  No Idea why...

-     Blender Version: Blender 2.79.6 (5e5f2ead437)
-     FLIP Fluids Version: 1.0.4a
-     Operating System: Windows 10
-     CPU: Intel i7-4790k @ 4.6GHz
-     GFX: GTX 1070, 8GB
-     RAM: 16GB

**Comment by rlguy** [comment]
Good news, I was able to reproduce the issue on one of my systems and narrow down what is causing the crash. This looks to be a bug within Blender that is triggered by saving icon images. When the FLIP Fluids addon starts up for the first time, it will generate a set of icon images to be used within the addon. I have filed a bug report here: https://developer.blender.org/T56610

Thanks @igarrison for letting me know that this worked on the unsupported 1.0.2 and not the current version. This made it much easier to narrow down what section of code was causing the crash.

Here is a simple script that will cause the nightly builds to crash:
```python
import bpy, os

icon_directory = os.path.join(bpy.context.user_preferences.filepaths.temporary_directory, "temp_icons")
os.makedirs(icon_directory, exist_ok=True)
for i in range(100):
    image = bpy.data.images.new("iconimg" + str(i), width=32, height=32)
    image.filepath_raw = os.path.join(icon_directory, str(i) + ".png")
    image.file_format = 'PNG'
    image.save()
```

Here is a .blend file that include the script. Press 'Run Script' to execute the script:
[bug_report_run_script.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2333989/bug_report_run_script.zip)

## How to reproduce crash

Here are the steps that I have found to reliably reproduce the crash:
1. Open nightly Blender build
2. Uninstall the FLIP Fluids addon
3. Restart nightly Blender build
4. Install the FLIP Fluids addon
5. Restart the Blender nightly build (crash)

_Note:_ Blender will sometimes successfully write the icon images on startup. Once the images are written, the addon will no longer need to run this section of code and Blender will stop crashing on subsequent startups. This could explain why the addon started successfully after a system restart.

## Workaround

It seems that the addon runs fine in the official Blender releases. So until Blender fixes this bug, a workaround to this issue is to initialize the addon using an official Blender build, and then run the addon using a nightly build.

1. Uninstall the FLIP Fluids addon
2. Open an official Blender build
3. Install the FLIP Fluids addon
4. Restart the official Blender build
5. Close the official Blender build
6. Open a Blender nightly build

\- Ryan

**Comment by rlguy** [comment]
The bug has now been fixed by Blender (in just over 12 hours!) and is now included in the latest nightly build. Just tested the build (**94ea566b5a1, Aug 31 2018 01:07:59**) and have confirmed that it works!

\- Ryan
