### ISSUE TITLE
Surface mesh bump artifacts on edges of domain

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids#380]
This bug could cause bumpy mesh artifacts on the edges of the domain boundary. This has been fixed and will be included in the next version (**1.0.5**).

![bump_artifacts](https://user-images.githubusercontent.com/4285191/44689318-fc5b3c80-aa0b-11e8-9db1-d94626f317b8.png)

This bug was caused by a less than optimal value set for a simulation tuning parameter. This value has been set to a more appropriate value.

**Comment by PascalSchimmler** [comment]
I have a very similar problem, it occured a couple of different times now, but I can't reproduce it on purpose. I tried like 15 different settings, whitewater no whitewater highres lowres fluid in domain, domain cutting into fluid, more subdivisions in the surface.. the only thing that stays constant are those bumps

Blender Version: Blender blender-2.80.0
FLIP Fluids Version: v9.0.5.3 Experimental 01-FEB-2019
Operating System: Windows 10
CPU: Intel i7-7700hq @ 3.80GHz
GFX: GTX 1070, 8GB
RAM: 16GB

![bug](https://user-images.githubusercontent.com/28070935/53293282-495c7780-37d1-11e9-9d0c-8c4a9d358d85.png)

[rip3.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2897465/rip3.zip)

**Comment by rlguy** [comment]
Hi PascalSchimmler,

Thanks for the .blend file! I just had a chance to test this out and it looks like the problem is the [Particle Scale](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Surface-Settings#parameters) value in the FLIP Fluid Surface panel which was set to 0.50. In most cases I would not recommend setting this value less than 1.0. Values smaller than 1.0 can make the particles too small to generate a proper mesh. Setting this value to the default 1.0 seems to generate a better mesh in the scene.

\- Ryan

**Comment by PascalSchimmler** [comment]
That worked on my side too, thanks!
