### ISSUE TITLE
Flip fluid - particles going out from obstacles

### ISSUE THREAD

**Issue by ArturoDoman** [rlguy/Blender-FLIP-Fluids#383]
#### System Information

**Blender Version 3,79 (f4dc9f9d68b)
**FLIP Fluids Version:1,04
**Operating System: Win10
**CPU: Intel - i7- 47771
**GFX: geforce GTX 1070
**RAM: 8GB

#### Describe the bug

Provide a clear and concise description of what the actual bug/issue is that you are experiencing.

#### To Reproduce

I do domain, obstacle bottle and fluid ainside the obstacle gbottle.
When the obstacle bottle has thin wall the fluid is going through the obstacle glass.
when I make the fat wall . The fluid is not goin through the wall but some particles is going out from obstacle bottle.

#### Expected Behaviour

what I should do to dont let go the particles from obstacle?

#### Actual Behaviour

Anyway the addon is the best i have seen, from i use blender.
I work for company wich is producting the water staff. 
That is a reason to buy this addon.

#### Screenshots

![flip fluid- particles going out from obstacle froom wall](https://user-images.githubusercontent.com/43038003/45162009-566ab780-b1ed-11e8-886e-3e502651a1c5.jpg)

**Comment by rlguy** [comment]
See documentation on how to resolve issues with leaking obstacles on this page: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#thin-obstacles-leaking-fluid

For further help with scene issues, see our guidelines on requesting scene troubleshooting support here: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Requesting-Scene-Troubleshooting-Help
