### ISSUE TITLE
[Requires Documentation] Whitewater panel UI update: Basic/Advanced settings modes

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids#384]
The current FLIP Fluid Whitewater panel (v1.0.4a) has an overwhelming number of parameters for whitewater simulation customization. This can make it difficult/confusing for a user to figure out what settings are most important for tuning the simulation.

For the next version (v1.0.5), the whitewater UI has been updated with an option to toggle between a _Basic_ settings view and an _Advanced_ settings view. The _Basic_ view mode will only show the most important parameters and hide advanced settings that are less likely to be used or to require tuning. The _Advanced_ view mode will display all whitewater parameters.

The [Whitewater Panel](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Whitewater-Settings) documentation should be updated to mark which settings are advanced before the release of v1.0.5.

Here are screenshots of the new Whitewater panel UI:

![whitewater_basic](https://user-images.githubusercontent.com/4285191/45183606-71cbc780-b1d9-11e8-96fa-6f1adf7dc23f.jpg)

![whitewater_advanced](https://user-images.githubusercontent.com/4285191/45183611-74c6b800-b1d9-11e8-84a5-0e889d33a267.jpg)

![whitewater_advanced_highlight](https://user-images.githubusercontent.com/4285191/45183618-78f2d580-b1d9-11e8-9a3c-952753d32718.jpg)

**Comment by ArturoDoman** [comment]
:-)

**Comment by rlguy** [comment]
Added documentation for this here: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Whitewater-Settings
