### ISSUE TITLE
[Feature Request] Integrate Alembic export into the addon

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids#389]
This is a popular feature request to in integrate [Alembic](http://www.alembic.io) directly into the addon codebase. This would allow the addon to bypass the Blender Alembic export system which can be buggy and does not offer much customizablity. Integrating Alembic into the addon would give us full control over how the fluid simulation would be exported, resulting in a much much faster export process and functionality to add customizations to export to other software. Having a complete Alembic export solution would also simplify the process of rendering a simulation on a render farm.

Our goal is to have this feature implemented for the next version update (**1.0.5**).

**Comment by NovioK** [comment]
It would be nice to have the ability to import an alembic and use it as an inflow object.  At the moment, we can export an alembic and bring it back in and make it an inflow object but the fluid only emits from whatever frame you are currently on as a static mesh and not an animated sequence where every frame is different.  Hope this makes sense.
In other words, I would like to use a baked out sim to generate another fluid sim on top of the baked one, but currently we can only do this on a fixed frame on the timeline where the baked sim acts like a static mesh.

**Comment by rlguy** [comment]
Hi NovioK,

If you are using an Alembic import as an inflow, you will need to enable the [Export Animated Mesh](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Inflow-Object-Settings#parameters) option in the Inflow object parameters.

Note that for objects to work correctly in the simulator, they must be both manifold and not change topology during an animation. Using a baked fluid simulation as an inflow would not be possible since the object mesh would have changing topology.

\- Ryan

**Comment by joostbouwer** [comment]
Is there any chance that this, a baked fluid sim obstacle, will come in a future version? Or would it be possible to use two different inflows with both there own viscosity??? It would be really great.
Thanks in advance.

Joost

**Comment by rlguy** [comment]
Hi Joost,

It could be possible to do this with Alembic export in the future, but I would not recommend handling multiple fluid interaction this way due to performance issues from using high-geometry fluid meshes as obstacles.

We do plan to support multiple viscosity and mixing fluids in the future (see this request #189), but at the moment this is not being actively worked on.

- Ryan

**Comment by JARINVER** [comment]
Is there a possibility that Alembic for particle export will supprot instance to mesh conversion? Novadays it export only "vertex cloud" ... it can be use for mesh instancing in external 3D software, but external rendering softwares don´t offer this function yet :( ... so the particles are invisibble because dont have any physical geometry ... Something as particle instances export implementatnion (or script) can be very nice feature... or some tutorial or documentation how to go around 

Thanks a lot,
Jaro

**Comment by rlguy** [comment]
Hi Jaro,

I'm sorry to say that this is not something we will know about and depends
on the Blender developers. We only develop the FLIP Fluids addon and do not
have control over Blender's development and what features they add for the
Alembic exporter. It may also depend on the developers of the external
software you are using.

\- Ryan

**Comment by rlguy** [comment]
My apologies for the ping on this issue thread, just cleaning up the FLIP Fluids GitHub issue tracker. 

The purpose of the FLIP Fluids GitHub issue tracker is for issues and bugs only. Feature development and requests are handled internally and requests can be made through alternative channels. See: [Guidelines for Feature Requests](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests)
