### ISSUE TITLE
Fluid volume increases during simulation

### ISSUE THREAD

**Issue by richardklingler** [rlguy/Blender-FLIP-Fluids#398]
#### System Information

**Blender Version: 2.79b 2018-11-16**
**FLIP Fluids Version: 1.04**
**Operating System: macOS 10.13.6**
**CPU: Intel i7-7700**
**GFX: GTX1080 Ti**
**RAM: 32GB**

#### Describe the bug

Using a cube as fluid with dimension 1.72 * 1.72 * 1.72 turns in the end to a fluid volume of around 2 * 2 * 2.2, wich is an increase of around 70%.

#### To Reproduce

Attached the blender file where the fluid runs through 25 holes in an invisible cube.

Video here: https://youtu.be/f1LEemJa4YA

#### Screenshots

Attached screenshots in ortho view to see the difference between start and end of simulation (side and front view).

![fluid_start](https://user-images.githubusercontent.com/11256235/49371276-3ae15100-f6f7-11e8-993c-681eed551302.png)
![fluid_end](https://user-images.githubusercontent.com/11256235/49371279-3f0d6e80-f6f7-11e8-8e20-f7b81f92049b.png)

[shower_test.blend.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2639244/shower_test.blend.zip)

**Comment by richardklingler** [comment]
The final volume is correct, when there is no obstacle the fluid has to run through...

When there is the obstacle, the final volume also depends on the viscosity setting, with no viscosity resulting in the biggest volume. See screenshots.
![fluid_end_no_viscosity](https://user-images.githubusercontent.com/11256235/49429605-2c537200-f7a9-11e8-9c82-6aa0e594f3f4.png)

![fluid_end_viscosity_0_01](https://user-images.githubusercontent.com/11256235/49429619-37a69d80-f7a9-11e8-8bdf-eb8271b31762.png)
![fluid_end_viscosity_0_1](https://user-images.githubusercontent.com/11256235/49429624-3c6b5180-f7a9-11e8-95af-4fdc5020a367.png)

**Comment by rlguy** [comment]
Hi Richard,

Thanks for the report and tests! I had some time to investigate this issue over the past week. The reasons for the volume gain can be found in this issue: #326

The fluid through a grate simulation is actually a worst case scenario for this type of simulator. When fluid passes through the grate, the motion becomes very chaotic and leads to large increases in volume. Fluid particles become split up and recombine immediately after passing through the holes which creates larger packets of fluid. When there is viscosity added to the fluid, the particle motion becomes more orderly and less chaotic leading to better volume conservation.

I have run tests in the new experimental version (v9.0.5.0) and unfortunately it seems that the problem of volume increase has become worse. Some stability improvements are in the experimental version which help with the problem of volume loss, but these changes have made the problem of volume increase worse. I'll need to experiment further and perhaps revert some changes to find a compromise between fixing volume increase and volume loss.

I'll close this issue and reference this update in issue #326
