### ISSUE TITLE
CLI output argument

### ISSUE THREAD

**Issue by laurence-trippen** [rlguy/Blender-FLIP-Fluids#399]
Hi, I'm Laurence.

First of all, FLIP Fluids is great!

I have a question about the CLI of FLIP Fluids.
Is it possible to define an output argument for the FLIP Fluids CLI?

In Blender for example:
blender -b foobar.blend -o //render_ -F PNG -x 1 -a

Blender has the "-o" or "--render-output=" argument.
Is it possible to specify this for the FLIP Fluids CLI?

Thanks in advance.

Many greetings,
Laurence

**Comment by rlguy** [comment]
Hi Laurence,

Do you mean that you would like to set the FLIP Fluids cache directory through the command line? Let me know if I misunderstood the question.

As far as I know, you won't be able to pass custom arguments through to the simulation script. It will result in a Blender **```unknown argument```** error. 

A workaround could be to modify the simulation script. Here is how you can set the cache directory within the **run_simulation.py** script described in the [CLI Baking Documentation](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Baking-from-the-Command-Line):

```python
import bpy

script_cache_directory = "//simulation_cache_directory"
domain_properties = bpy.context.scene.flip_fluid.get_domain_properties()
domain_properties.cache.cache_directory = script_cache_directory 

bpy.ops.flip_fluid_operators.bake_fluid_simulation_cmd()
```

This will set the cache directory to be saved in ```//simulation_cache_directory``` before baking the simulation.

Hope this helps!

\- Ryan

**Comment by laurence-trippen** [comment]
Hi Ryan,

that helps me.
Thank you very much!

Best regards,
Laurence
