### ISSUE TITLE
Needs upgrade for Blender 2.8 beta

### ISSUE THREAD

**Issue by Ergonomicmike** [rlguy/Blender-FLIP-Fluids#402]
Am sure you know this - just tried the Demo with Blender 2.8 beta. Get an Alert that the addon needs to be updated.

**Comment by rlguy** [comment]
Hi Ergonomicmike,

We're actually right in the process of updating the FLIP Fluids addon to Blender 2.80 and are [hoping to have a working experimental build available on Dec 14th](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Frequently-Asked-Questions#do-you-plan-to-support-blender-28).

As for the demo, it might take a while longer to update this to Blender 2.8. We will need to create an entirely new demo addon to add 2.8 support.

\- Ryan

**Comment by Ergonomicmike** [comment]
Thanks. Didn't see the FAQs - and even after you pointed me to it, I still had trouble finding it. (Didn't know I needed to go to the Wiki first.) Perhaps might want to add a link to the FAQ on the top github page, under the readme?
