### ISSUE TITLE
Missing features in Blender 2.80

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids#404]
The first iteration of the Blender 2.80 experimental build (**v9.0.5.1**) will be missing features from the Blender 2.79 version and will be disable until they are fully implemented. These are the current missing features:

1. **FLIP Fluids Toolshelf Menu** - Blender 2.80 removed the toolshelf of 2.79. We will need to find an alternative interface area to place our FLIP Fluids toolshelf features.
2. **[Grid Display](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Debug-Settings#grid-display-settings) and [Particle Debugging](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Debug-Settings#fluid-particle-display-settings)** - These features require custom drawing that has changed in Blender 2.80. We will first need to learn how to integrate these changes into the FLIP Fluids addon until we can add these features. Note: custom drawing in 2.80 has greatly improved and will be very useful for the Particle Debugging feature which was slow in 2.79.
3. **Fluid mesh organization in outliner** - In Blender 2.79, fluid meshes were children of the domain object and were contained in the domain hierarchy. Blender 2.80 removes functionality to organize objects in a parent/child hierarchy and has replaced this with a new 'collections' system which is similar to a filefolder/directory organization. We will need to decide how we want to organize our meshes in the outliner. For now, simulation meshes will be located in the base scene collection: 
![mesh_storage](https://user-images.githubusercontent.com/4285191/49965890-53115700-fed3-11e8-819e-fcfd918a3ea6.jpg)

**Comment by rlguy** [comment]
Suggestion for how to organize collections:

> What do you think about automatically adding all fluid sim objects to a collection called 'FLIP Fluids'? Objects can be in multiple collections and this would be a cool way to organize the scene. As a reference, The Grove 3D plugin creates a collection called 'Grove' by default.

**Comment by pskl** [comment]
Sounds good to me

**Comment by rlguy** [comment]
Compatibility for these features have been added and will be included in the next experimental (v9.0.5.3) or stable version of the addon (1.0.5).

### FLIP Fluids Toolshelf Menu

In Blender 2.7x this was located on the left side. This is now located on the right side of the viewport in Blender 2.8. Toolshelf menus in Blender 2.8 can be opened with the hotkey ```n```.

![helper_ui](https://user-images.githubusercontent.com/4285191/51353894-c83df200-1a66-11e9-8fba-c9e1fb1ec0be.jpg)

### Grid Display and Particle Debugging

These features have been added and are accessible through the [Debug Panel](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Debug-Settings).

[Custom viewport drawing is much faster in Blender 2.8](https://twitter.com/FlipFluids/status/1085723255305060353)

### Fluid mesh organization in outliner

FLIP objects and meshes are organized in FLIPFluids and FLIPMeshes collections:

![collections](https://user-images.githubusercontent.com/4285191/51354008-28349880-1a67-11e9-881a-fd5e0d92cd91.jpg)
