### ISSUE TITLE
Compile bug

### ISSUE THREAD

**Issue by Chongyao** [rlguy/Blender-FLIP-Fluids#407]
#### System Information

**Blender Version (including hash):2.79b
**FLIP Fluids Version:1.0.2
**Operating System:Mac OS Sierra
**CPU:Intel Core i5
**GFX:Intel Iris
**RAM:4GB
**Compiler: g++8.2

#### Describe the bug

Source code can't pass compile.
#### To Reproduce
mkdir build &&cd build && cmake ..&&make

#### Expected Behaviour

Successfully build.
#### Actual Behaviour

In file included from /Users/mac/projects/Blender-FLIP-Fluids-copy/src/engine/clscalarfield.h:30,
                 from /Users/mac/projects/Blender-FLIP-Fluids-copy/src/engine/clscalarfield.cpp:25:
/Users/mac/projects/Blender-FLIP-Fluids-copy/src/engine/arrayview3d.h: In member function 'void ArrayView3d<T>::getViewAsArray3d(Array3d<T>&)':
/Users/mac/projects/Blender-FLIP-Fluids-copy/src/engine/arrayview3d.h:193:16: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return view;
#### Screenshots

<img width="1141" alt="wx20181218-085619 2x" src="https://user-images.githubusercontent.com/30331053/50125225-cedc1c80-02a2-11e9-9309-563c23997ecf.png">

#### Solution
replace void with Array3d<T> in line 176 in function getViewArray3d in file arrayview3d.h

**Comment by rlguy** [comment]
Hi Chongyao,

Thanks for the report! We have actually already fixed this after this report: #367

Note: This repository is a few months out of date with our private development repository. We plan to update this repository once we finish the next version of the addon (v1.0.5).

\- Ryan
