### ISSUE TITLE
Issues installing Flip Fluids in 2.8 Beta - Recent Python API Change

### ISSUE THREAD

**Issue by originalClown** [rlguy/Blender-FLIP-Fluids#408]
#### System Information

**Blender Version (including hash):** Blender 2.8 4c5e76025d83
**FLIP Fluids Version:** flip_fluids_addon-9.0.5.1_experimental_13-dec-2018
**Operating System:** Windows 10 Pro 64 bit
**CPU:** Ryzen 7 1800X
**GFX:** GTX 1070 FE
**RAM:** 16 GB Kingston valueRAM DDR4 @2133mhz

#### Describe the bug

Can't install the 2.8 version of Flip Fluids with the 2.8 Beta. Get an attribute error

#### To Reproduce

I've reinstalled the latest versions of Flip Fluids and Blender 2.8 Beta and cleared the 2.8 roaming folder

#### Expected Behaviour

Installed addon from file, clicking enable addon should enable the addon

#### Actual Behaviour

Clicking the enable button brings up multiple errors

#### Screenshots

![screenshot 1](https://user-images.githubusercontent.com/36329721/50380240-46ba9600-0659-11e9-9d43-e07850e99328.png)

**Comment by rlguy** [comment]
Hi originalClown,

Thanks for the report! In the latest Blender 2.80 build (4c5e76025d83) there is a [Python API change](https://developer.blender.org/rB63fcbfc3a7325d79b9e916457d64c302ddfeadfa) that broke the FLIP Fluids addon along with many other addons. 

The API change renames _**user_preferences**_ to _**preferences**_. I suspect this is what is causing the addon to fail installation. If you look at earlier error messages in the Blender System Console (**Blender > Window > Toggle System Console**), you might find this error which is causing the installation to fail:

```AttributeError: ‘Context’ object has no attribute 'user_preferences’```

I'll try to get a new build out tomorrow to fix this.

\- Ryan

**Comment by originalClown** [comment]
Ah ok, thanks for the swift response :)

**Comment by rlguy** [comment]
This has been fixed and will be included in the next experimental version (9.0.5.2).
