### ISSUE TITLE
No documentation on installing the addon

### ISSUE THREAD

**Issue by cpellet** [rlguy/Blender-FLIP-Fluids#413]
The wiki doesn't include any documentation on how to compile and install the addon. Supposedly, Github only contains the 'source code' of the addon whereas the working version should be bought via Blender Market. However, it should be perfectly possible to benefit from the addon; the GitHub guidelines specifying that "For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software". Furthermore, Blender being an open-source software as well, it would be truly unappropriate to provide 'source code' without any explanations on how to run it whatsoever. Please fix your documentation accordingly.

**Comment by rlguy** [comment]
Hi cpellet,

I have updated the README.md to include build instructions beginning at this section: https://github.com/rlguy/Blender-FLIP-Fluids/blob/master/README.md#source-code-dependencies

\- Ryan
