### ISSUE TITLE
Debug Particles are drawn on all layers

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#416]
#### System Information

**Blender Version: 2.79b f4dc9f9d68b**
**FLIP Fluids Version: 9.0.5.2**
**Operating System: Windows 7 64 bit**
**CPU: A8 5600K 3.60GHz 4 Core**
**GFX: None**
**RAM: 8 GB**

#### Describe the bug

If you enable the Enable Fluid Particle Debugging option, then the fluid particles will draw on all layers of the scene, no matter which layer the domain is on.

#### To Reproduce
Open the blend file and bake the simulation. Then turn on only the empty layer of the scene, for example 2. And you will see particles of liquid, which should not be. Particles must be on a layer with a domain.
[fluid_particles_debug.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2793198/fluid_particles_debug.zip)

#### Expected Behaviour

Fluid particles should be drawn only on the layer of the stage where the domain is located. That is, if the layer with the domain is turned on, then the particles must be displayed, otherwise not to draw them.

#### Actual Behaviour

Debug Particles are drawn on all layers

#### Screenshots

![01](https://user-images.githubusercontent.com/7983249/51702940-21d58c00-2026-11e9-9310-a23ff3d0c51a.jpg)

**Comment by rlguy** [comment]
Hi PavelBlend,

Thanks for the report! I have added this functionality for both the particle debug drawing and grid debug drawing. This will be included in the next update available next Friday (Feb 1st).

\- Ryan
