### ISSUE TITLE
Boundary Friction does not work

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#418]
#### System Information

**Blender Version: 2.79b f4dc9f9d68b**
**FLIP Fluids Version: 9.0.5.2**
**Operating System: Windows 7 64 bit**
**CPU: A8 5600K 3.60GHz 4 Core**
**GFX: -**
**RAM: 8 GB**

#### Describe the bug

If you enable the viscosity parameter, then the Boudary Friction parameter will not work.
The fluid behaves as if the parameter Boundary Friction is always set to 1.0.

#### To Reproduce

[boundary_friction.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2796927/boundary_friction.zip)

#### Expected Behaviour

The fluid should not stick to the domain boundaries if the Boundary Friction parameter is 0.

#### Actual Behaviour

Fluid adheres to the boundaries of the domain:

#### Screenshots

![bug](https://user-images.githubusercontent.com/7983249/51758822-ae8c5280-20d7-11e9-8a15-ee3b79dcc873.jpg)
![0122](https://user-images.githubusercontent.com/7983249/51758827-b3e99d00-20d7-11e9-8d9e-35bcbb518585.jpg)

**Comment by rlguy** [comment]
Hi PavelBlend,

Thanks for the report! This is actually a limitation of the viscosity solver/method. The fluid will stick to the boundaries even at 0 friction. If I find a way to work around this limitation in the future, I'd like to fix this issue.

\- Ryan
