### ISSUE TITLE
Reload Frame does not work

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#419]
#### System Information

**Blender Version: 2.79b f4dc9f9d68b**
**FLIP Fluids Version: 9.0.5.2**
**Operating System: Windows 7 64 bit**
**CPU: A8 5600K 3.60GHz 4 Core**
**GFX: -**
**RAM: 8 GB**

#### Describe the bug

The Reload Frame button does not work.

#### To Reproduce

The button does not work in any scene.

#### Expected Behaviour

If the frame is baked, but not displayed, then when you press the button, the liquid should load from the cache into the blender.

#### Actual Behaviour

When pressed, nothing happens.

**Comment by rlguy** [comment]
Hi PavelBlend,

Thanks for the report! It looks like there was a logic error preventing the operator from reloading the frame. This has been fixed will be included in the next update available next Friday (Feb 1st).

\- Ryan
