### ISSUE TITLE
FLIP particles are not deleted after a cache reset

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#422]
#### System Information

**Blender Version: 2.79b f4dc9f9d68b**
**FLIP Fluids Version: 9.0.5.3**
**Operating System: Windows 7 64 bit**
**CPU: A8 5600K 3.60GHz 4 Core**
**GFX: -**
**RAM: 8 GB**

#### Describe the bug

If you clear the cache, Debug Particles will still be displayed in the 3D window. It is necessary to forcibly update the frame so that the particles disappear.

#### To Reproduce

Create a domain and source of fluid. Enable the Enable Fluid Particle Debugging option. Bake the liquid. Then reset the liquid and you will see that the debug particles remain in the 3D window.

#### Expected Behaviour

Debug particles must be removed.

#### Actual Behaviour

Debug particles remain visible. They disappear only after updating the frame.

#### Screenshots

https://youtu.be/RV0IxmqLiek

**Comment by rlguy** [comment]
Hey PavelBlend,

Thanks for the report! I have fixed this and this will be included in the next version (v1.0.5).

\- Ryan
