### ISSUE TITLE
Voxel color not valid

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#423]
#### System Information

**Blender Version: 2.79b f4dc9f9d68b**
**FLIP Fluids Version: 9.0.5.3**
**Operating System: Windows 7 64 bit**
**CPU: A8 5600K 3.60GHz 4 Core**
**GFX: -**
**RAM: 8 GB**

#### Describe the bug

The domain has a cube in the corner that shows the size of the voxel. If the domain object is active but not selected, then the color of this cube is not correct. It will have a yellow color, but must be black.

#### To Reproduce

Create an object and assign it as a domain. Make the domain active, and then deselect it with the A key. And you will see the wrong color at the voxel in the corner.
[voxel_color_test.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2824787/voxel_color_test.zip)

#### Expected Behaviour

The color of the voxel must be black when no domain object is selected.

#### Actual Behaviour

The color of the voxel is the same as if the object is selected (that is, the color of the voxel is yellow).

#### Screenshots

![01](https://user-images.githubusercontent.com/7983249/52168395-fe53c500-273a-11e9-9e53-febb008eb8c3.jpg)

**Comment by rlguy** [comment]
Hey PavelBlend,

Thanks for the report! I am actually going to remove this voxel drawing from the addon in the next version. There is not a simple way to determine what the voxel colour should be to match the domain object. There are some cases where it is complicated to match the colour correctly. Another example is translating/rotating/scaling the domain. The object wire turns white and we would need to keep track of when the user is doing this in the UI.

\- Ryan
