### ISSUE TITLE
Simulations longer than 300 frames crash - can't extend

### ISSUE THREAD

**Issue by TheModerator** [rlguy/Blender-FLIP-Fluids#424]
I have a simulation which should go for approximately 1000 frames, (starting at frame 760, ending at 1760) with the following parameters:

Grid resolution: 172 x 250 x 143
Grid Dimensions: 5.504m x 8m x 4.576m
Grid Cell Count: 6149000
Grid Cell Width: 0.031m

The scene contains two relatively complex (but 'watertight') solid obstacles inside of a domain with two inflows with animated (both animated movement, and animated inflow/velocity) parameters.

If I run a bake with 300 frames, it works fine. If I run the bake with 301 frames, it will export animation data, then crash without a prompt or any log files being made. I have Display Console Output checked, and it would appear it crashes after the fluid solve starts, but before it outputs any debug info for the first frame. Blender doesn't 'hang', it just closes itself. 

I've tried on another PC that has 2GB of RAM more than my main system (but is a way slower CPU) and I get about 350~370 frames out of that one, but in both cases, on the instances where it crashes, there's still plenty of RAM left, as it's sitting at 70% before dropping as blender exits.

I have tried extending the end time (i.e. baking from 760 to 1000, then 760 to 1200) etc... however the moment the total frame count goes over 300, it crashes. I've tried adjusting the start and end time (i.e. baking from 760 to 1000, then 1000 to 1200) however this produces weird results even when the total frame count doesn't exceed 300, but this seems like a totally separate and edge-case bug.

I appreciate that CFD isn't easy and this report alone probably doesn't narrow down where the error could come from - if there's additional diagnostic steps, let me know. If the answer is simply "get more RAM" I'm open to that too lol

System Spec:
Blender 2.79b
Tested in all versions from 9.0.5.0 to 9.0.5.3
AMD Ryzen 7 2700X, 16GB RAM, GTX 1080Ti, Windows 7

Also tested on an Intel i7 (mobile) 18GB RAM, GTX 970M, Windows 10, similar results, just a few more additional frames

**Comment by rlguy** [comment]
Hi TheModerator,

Thank you for the detailed report! I will be able to look into this issue after the weekend. 

Would it be possible for you to attach the .blend file? You may attach the file here or send it to us at flip.fluids@gmail.com. Here are some [.blend file guidelines that can help us test this issue](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Reporting-Bugs-and-Issues#scene-file-guidelines).

\- Ryan

**Comment by rlguy** [comment]
Hey, thanks for the update! That would explain the issue. Not dumb at all and an easy mistake to make! I would rather issues get reported and end up being related to user-error than for potential issues to go unreported.

\- Ryan
