### ISSUE TITLE
FBX export to unreal

### ISSUE THREAD

**Issue by SicroxArt** [rlguy/Blender-FLIP-Fluids#426]
Hello rlguy, i have a issue wen i want to export a fbx archive of flip fluids, then i import un unreal engine, the fbs doesnt work, i cant see te animation, can you give me a tip or a solve 

thanks for your attention, best wishes and awsome plug-in

**Comment by rlguy** [comment]
Hi SicroxArt,

This is an issue that will be unrelated to the FLIP Fluids addon. FBX file exporter features and how they create the files is a part of Blender and outside of our control.

You might have luck exporting simulations as an Alembic (.abc) cache if Unreal supports this. There is a workaround to do this here: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#export-to-alembic-cache-is-not-exporting-animated-meshes

\- Ryan

**Comment by SicroxArt** [comment]
thanks for you atencion, i trying this 

have a good weekend
