### ISSUE TITLE
Fixed Multi thread Issue 

### ISSUE THREAD

**Issue by vasanthart** [rlguy/Blender-FLIP-Fluids#429]
This issue tracker is not the correct place for questions/comments. See our [Technical Support Guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines) document for more information. Send us a message on the Blender Market for send us an email at flip.fluids@gmail.com if you would like to propose a discussion topic for this issue tracker.

**Comment by vasanthart** [comment]
Hi,

I am new to using flipfluid add-on and i have read all the documents in "frequently asked question" section about why the "CPU Usage running under 100%". My question is in the fixed multi threading section. 

In this case i need to bake large number of frames (approximately - 5000 Frames) in high resolution - 1000. So i decided to put the thread count to "30" in fixed multi threading option. Thereafter I checked my CPU performance, it will shows all the threads (48 threads) are starts to running and some of the threads 60% usage others below 10%. So no use of the thread counts and no difference in performance wise while changing the thread counts.

System Configuration:

"Ubuntu"
Release 18.04.2 LTS (Bionic Beaver) 64-bit
Kernal Linux 4.15.0-generic x86_64
MATE 1.20.1

Hardware:
Memory 39.2 GiB
Processor: Intel Xeon (R) CPU E5-2651 v2 @ 1.80GHZ * 48

System Status:
Available disk space: 92.6 GiB

Thanks,
Vasanth

**Comment by rlguy** [comment]
Hey Vasanth,

> The simulator may be running with too many threads enabled. It is possible that simulations could slow down from the overhead of running more threads than the simulator can handle efficiently. Some users with certain hardware (e.g. Intel Xeon CPU) may benefit from simulating with less threads enabled. You may experiment by changing the number of enabled threads in the FLIP Fluid Advanced Settings. Try using half the number of threads and test whether you experience a speed-up in baking times.

Although decreasing number of threads can improve performance, it is not always guaranteed to improve performance. Whether decreasing threads will benefit simulation times depends on many factors such as system hardware, OS and how the OS schedules tasks, and the many combinations of simulation setups/scenarios in your scene. The only way to find out if it result in a performance gain on your system is though testing different thread counts. If there is no perceivable difference, I would suggest using the highest thread count.

\- Ryan
