### ISSUE TITLE
FlipFluid silly artifacts on mac OSX

### ISSUE THREAD

**Issue by StephanVolk** [rlguy/Blender-FLIP-Fluids#432]
Hi there,

I hope, after hurdling all obstacles, I’m at the right place for a bug report here.

Blender version: 2.79b 2018-03-22
OSX: 10.9.2
Mac: 3,5 GHz 6-Core-Intel Xeon ES
16GB RAM

I just started with working through your Youtube-Tuts.
During rendering Animations sometimes appear silly artifacts, which I can not reproduce. The normal things like baking in different solutions, re-starting etc. I have done several times.
I try to add the blender file
And here you can find some rendered frames with those silly artifacts =>

![Renderfehler25](https://user-images.githubusercontent.com/48755207/54678516-90eece80-4b05-11e9-9223-ff19aaf597b6.png)
![Renderfehler](https://user-images.githubusercontent.com/48755207/54678517-90eece80-4b05-11e9-8b6d-af80c97d8c3c.png)

The attached blender-file is completely unstable and crashes suddenly during rendering.

I really tried out every thing I could imagine, e.g. rendering with CPU or GPU, different tile areas and so on.

The silly artifacts appear in other simulations, too.

I did not found anything about this in any bug report or FAQ.
Hope you can help.

Greetings from Germany (though I think, the guy who did the tutorials is German, too)

Stephan

**Comment by rlguy** [comment]
Greetings Stephan,

This issue can usually be resolved by setting the Blender render display to _fullscreen_ ([Described in this troubleshooting topic](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#blender-often-crashes-suddenly-or-does-not-apply-transforms-while-rendering)). 

Does this solution work for you?

\- Ryan

**Comment by StephanVolk** [comment]
Hi Ryan,

 

thanks for your fast reply – I just tried again, and it seems to work. Cool, thank you.

 

Sorry for your effort, I read about this solution, but only in order with large meshes.

There was no note for such daft artifacts.

 

All the same, I think you made a great job with your add-on and I hope to have a lot of fun with it :-)

 

Greetings and have a nice day,

 

Stephan
 

volkgrafikdesign
Tegernseer Straße 60
83734 Hausham
Telefon: 01 77 68 46 118
E-Mail: volkgrafikdesign@gmx.net

 
 

Gesendet: Mittwoch, 20. März 2019 um 17:10 Uhr
Von: "Ryan Guy" <notifications@github.com>
An: rlguy/Blender-FLIP-Fluids <Blender-FLIP-Fluids@noreply.github.com>
Cc: StephanVolk <volkgrafikdesign@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [rlguy/Blender-FLIP-Fluids] FlipFluid silly artifacts on mac OSX (#432)


Greetings Stephan,

This issue can usually be resolved by setting the Blender render display to fullscreen (Described in this troubleshooting topic).

Does this solution work for you?

- Ryan

**Comment by rlguy** [comment]
No problem, thanks for the update! Glad the workaround ended up fixing the problem. I have added some additional notes to the troubleshooting topic to better describe the issue.

**Comment by StephanVolk** [comment]
Dear Ryan,

after our little conversation yesterday, where you helped me with the tip to render in full-screen, I played a bit around.

What happened: first, after your tip, I rendered the scene in full-screen, and it worked (so I told you). After that, I baked the scene again, but in final resolution of 200. Baking went without problems, but after that the scene would not render at all. Not in cycles, not in blender render, not after restarting the whole system, other material, deleting caches and so on.

At this time this is completely no problem, as I’m just starting with FlipFluid, but if this would be a commercial job, it would be not so nice...

After that, I set up the scene completely new (without a material) and baked until resolution 125. This now works without problems.

I attach my »broken« blender-file, maybe you have an idea?

Sorry for that, I don’t want to annoy.


Viele Grüße, (greetings)

Stephan


    
  





volkgrafikdesign
Tegernseer Straße 60
83734 Hausham
Telefon: 01 77 68 46 11 8
E-Mail: volkgrafikdesign@gmx.net
www.volkgrafikdesign.de

**Comment by rlguy** [comment]
Hi Stephan,

It looks like the file did not attach to your comment. You may need to attach the file through the GitHub site. Or you may send the file to us at flip.fluids@gmail.com

Would you be able to describe what you mean by the scene not rendering? A few things I am wondering:
- Is Blender crashing? 
- Do you receive any error messages (can be found in **Blender > Window > Toggle System Console** on Windows)?
- Is the render result just a black image?

\- Ryan

**Comment by StephanVolk** [comment]
Hi Ryan,

thanks for you answer.I just tried to conctact you via mail, because I noticed you closed this thread.
Ok, here again: 
1st: I’m not so familiar with Mac's terminal, and this should be the only way to read any error messages on Mac (I can check it out the upcoming week-end, now I just have to work)
2nd: Blender is NOT crashing, just does not start rendering at all.
3rd: Yes, in one ore two cases the result has been a black image.

And: I tried out again several new files and the error does not appear again. Maybe it’s been only a silly newbie-mistake or it may depend on rendering NOT in fullscreen?

I will sent the original file via e-mail, as you recommended.

Thanks for your help,

Stephan

**Comment by rlguy** [comment]
Hi Stephan,

Thanks for sending the .blend file, I just had a chance to check it out! I tried rendering the animation and got an odd result: it was displaying an animation I had rendered yesterday in a different scene.

I noticed that the Blender sequence editor is loading a clip from my render output directory and that is what is being displayed as the render result.

![sequence_editor](https://user-images.githubusercontent.com/4285191/54845873-c7f4e980-4c97-11e9-8be7-d0e3a84c1bcb.jpg)

To be honest, I am not familiar with the Blender 'Video Sequence Editor' and am not sure how it works. After deleting the clip, the scene seems to render correctly.

Hope this helps!

\- Ryan

**Comment by StephanVolk** [comment]
Yeeeeeessss! That’s it. I can readjust, what you proposed, it was the same thing here on my computer. I deleted the wrong video sequence and tried again, with different resolutions in baking (the last with an amount of 200) and rendering animations.
Now it works, cool.
Have a good start in the upcoming week and I hope, you never will read anything from me :-) 

Greetings, Stephan
