### ISSUE TITLE
Simulation Attributes

### ISSUE THREAD

**Issue by gogobd** [rlguy/Blender-FLIP-Fluids#434]
It would be interesting to get access to some of the simulations internal variables through Attribute Nodes! Maybe this feature is a low-hanging fruit and could be implemented for a future version.

**Comment by rlguy** [comment]
Hi gogobd,

At the moment, this issue tracker will not be accepting feature requests. We have a large list of requested features and will need to work through the popular requests before we can accept new requests. See [Technical Support Guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines).

However, we do plan to experiment with exporting simulation attributes in the future as part of an implementation for a variable viscosity and material mixing feature: #189

**Comment by gogobd** [comment]
You’re awesome!
