### ISSUE TITLE
Update addon class naming conventions to be compatible with Blender 2.80

### ISSUE THREAD

**Issue by sorinv** [rlguy/Blender-FLIP-Fluids#437]
Blender started enforcing class naming conventions from the March 25th build. This makes the current 2.80 build of Flip Fluids incompatible with the latest Blender nightly build.

Checked with flip_fluids_addon-9.0.5.3_experimental_01-feb-2019.zip on Linux, gives the error:

`RuntimeError: Error: 'flip_fluid_menus.enable_whitewater_menu' doesn't contain '_MT_' with prefix & suffix`

**Comment by rlguy** [comment]
Hi sorinv,

Thanks for the report! We have just found out that the Blender developers have reverted this patch so that addon developers will have more time to fix this issue ([Discussion thread](https://developer.blender.org/rBb24a255ca67841ff2d6121327791e933ce8e3602)).

\- Ryan

**Comment by rlguy** [comment]
Update: The Blender developers plan to freeze the Python API sometime in the middle of May, so this may become an error again soon. We will be including these API updates in the next experimental version (9.0.5.4) which will be available near the end of next week.
