### ISSUE TITLE
Flip Fluids cannot find my gpus. It displays an error anytime i click  "search for gpu"

### ISSUE THREAD

**Issue by Blendry** [rlguy/Blender-FLIP-Fluids#438]
This issue tracker is not the correct place for questions/comments. See our [Technical Support Guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines) document for more information. Send us a message on the Blender Market for send us an email at flip.fluids@gmail.com if you would like to propose a discussion topic for this issue tracker.

**Comment by rlguy** [comment]
Please see this document for how to report an issue: [Technical Support Guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines).
