### ISSUE TITLE
Issues installing Addon Blender 2.8

### ISSUE THREAD

**Issue by Alkaris** [rlguy/Blender-FLIP-Fluids#443]
#### System Information

**Blender Version (including hash):** 2.80 - d1cda823e0a8
**FLIP Fluids Version:** 1.0.2 (compiled from git source)
**Operating System:** Linux Mint 19.1 64-bit
**CPU:** Intel® Core™ i7-7700K
**GFX:** Asus GTX 1070 Snow Edition OC (8GB)
**RAM:** Trident Z RGB 16GB

#### Describe the bug
I downloaded the git source and compiled the addon successfully without errors, and zipped up the compiled build and added it into Blender 2.8, while it did add successfully the plugin addon, it doesn't appear in the Physics tab where it should be. There were no errors in the console when it added it to Blender either. And yes before you ask, I did restart Blender.

#### Screenshots

![Shutter__2019-04-17__02_31_44_AM](https://user-images.githubusercontent.com/6682988/56229899-24da9880-60ba-11e9-831e-de5c6aaf3bc9.png)

**Comment by rlguy** [comment]
Hi,

The current version in the GitHub repository does not include support for Blender 2.80. We are currently testing support for Blender 2.80 in experimental versions of the addon available on the Blender Market and hope to update the repository once Blender 2.80 is stable and officially released (around July 2019).

\- Ryan
