### ISSUE TITLE
I cant find any Surface Tension and sheeting in my word panel. Flip fluid 

### ISSUE THREAD

**Issue by doman13** [rlguy/Blender-FLIP-Fluids#444]
#### System Information

**Blender Version (including hash):** 2,79 5bd8ac9
**FLIP Fluids Version:** 1.0.4
**Operating System:** win 10
**CPU:**
**GFX:**
**RAM:**

#### Describe the bug

on my documentation page i can see description of Surface Tension and sheeting in my word panel. But in my addon i cant see any of this.
![lost Surface Tension and sheeting](https://user-images.githubusercontent.com/36233259/56269055-1361b280-60f3-11e9-868b-4a194efafa48.jpg)

What i should do to have a Surface Tension and sheeting?

**Comment by rlguy** [comment]
Hi doman13,

The surface tension and sheeting features are only available in the experimental version of the addon. The latest experimental version of the addon can be found in the [Blender Market downloads](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/FLIP-Fluids-Downloads) and is labeled as **flip_fluids_addon-9.0.5.3_experimental_01-feb-2019.zip**.

Note: there are currently some issues with the surface tension feature. See this issue for more details: #420

Apologies for the confusing documentation. I have updated the documentation to mention that these features are only in the experimental version.

\- Ryan

**Comment by doman13** [comment]
Thank You for Your answer.

Dnia 17 kwietnia 2019 16:45:00 CEST, Ryan Guy <notifications@github.com> napisał(a):
>Hi doman13,
>
>The surface tension and sheeting features are only available in the
>experimental version of the addon. The latest experimental version of
>the addon can be found in the [Blender Market
>downloads](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/FLIP-Fluids-Downloads)
>and is labeled as
>**flip_fluids_addon-9.0.5.3_experimental_01-feb-2019.zip**.
>
>Note: there are currently some issues with the surface tension feature.
>See this issue for more details: #420
>
>Apologies for the confusing documentation. I have updated the
>documentation to mention that these features are only in the
>experimental version.
>
>\- Ryan
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rlguy/Blender-FLIP-Fluids/issues/444#issuecomment-484120950

--
Wysłane z aplikacji OnetPoczta
