### ISSUE TITLE
is there any way to use flip fluids simulation effect with cloth simulation?

### ISSUE THREAD

**Issue by eroswade** [rlguy/Blender-FLIP-Fluids#446]
until now, i can't find anything to do this. 
only find a solution on houdini with an opensource project
https://github.com/nepluno/libwetcloth

**Comment by rlguy** [comment]
Hi eroswade,

Blender simulations are not able to interact with each other in a way that supports 'two-way coupling'. Simulations in Blender need to be calculated independently and this limitation will only allow 'one-way coupling'.

For example, a cloth simulation can push around a fluid simulation, but the fluid simulation will not be able to push around the cloth simulation.

libWetCloth and Houdini are the only solution that I have heard that has good support for fluid and cloth simulation interaction.

\- Ryan

**Comment by eroswade** [comment]
thanks, rlguy. 
for days googling. i find the blender fractrure modiifier customer build, can do a little bit combine of cloth and fluid.
as using the fake fluid and fake cloth. but it's focus on fracture. 
another solution is using SPH partical.
