### ISSUE TITLE
Fluid Offset is not working properly

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#452]
#### System Information

**Blender Version: 2.79b (f4dc9f9d68b)**
**FLIP Fluids Version: 9.0.5.4**
**Operating System: Windows 7 64 bit**
**CPU: AMD A8 5600K**
**GFX: -**
**RAM: 8 GB**

#### Describe the bug

The fluid behaves the same, regardless of the type of offset.

#### To Reproduce

If you set the object to Fluid type and set Trigger to Frame Offset = 70 and then set the Timeline Offset to 70, the liquid will appear in the same frame.
[fluid_offset_test.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/3216535/fluid_offset_test.zip)

#### Expected Behaviour

In one case, the liquid should appear in frame 70, and in another case in frame 120 (see the blend scene)

#### Actual Behaviour

Fluid always appears in frame 120.

#### Screenshots

![01](https://user-images.githubusercontent.com/7983249/58323660-494e3100-7e2d-11e9-998a-92f5251e86ca.jpg)

**Comment by rlguy** [comment]
Hi PavelBlend,

Thanks for the report! It looks like there was a logic error in the code. I have fixed this and the fix will be included in the next version update (1.0.5).

\- Ryan
