### ISSUE TITLE
Two dots in the description

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#453]
#### System Information

**Blender Version: 2.79b (f4dc9f9d68b)**
**FLIP Fluids Version: 9.0.5.4**
**Operating System: Windos 7 64 bit**
**CPU: AMD A8 5600K**
**GFX: -**
**RAM: 8GB**

#### Describe the bug

In the description of the parameters there are two points at the end.
Here is a list of parameters (maybe not all):
Domain > Update Settings on resume
Domain > Enable Savestates
Domain > Delete outdated Savestates on resume

#### Screenshots

![01](https://user-images.githubusercontent.com/7983249/58324557-e1e5b080-7e2f-11e9-81ea-de69b707d79e.jpg)

**Comment by rlguy** [comment]
Hi PavelBlend,

Thanks for the report. There was a change between 2.79a and 2.79b where Blender started automatically adding a period at the end of the descriptions. I am not sure why this is done. So if we had a period at the end of our description, there would be two when displayed in the UI.

There seems to be a problem in Blender 2.79b with how they automatically add this period. If I delete my Blender configuration and reinstall the addon, these extra periods won't be added. This happens on Windows, but did not happen on Linux. The automatic period seems to be consistent within Blender 2.80, so I'll update the descriptions.

There are many descriptions like this in the addon and I found 77 of them, but I could have missed some. I have removed the ending period and these fixes will be included int he next update (1.0.5).

\- Ryan
