### ISSUE TITLE
I cant find the 1.0.5 Libs while compiling

### ISSUE THREAD

**Issue by thefudgeishot** [rlguy/Blender-FLIP-Fluids#465]
#### System Information

**Blender Version: 2.8**
**FLIP Fluids Version: 1.0.5**
**Operating System: Windows 10**
**CPU: Amd Ryzen 5 2600x Six-Core Processor**
**GFX: Rtx 2070**
**RAM: 16gb DDR4**

#### Describe the bug

When i compile the addon for blender 2.8 it cant find the pyfluid.dll

#### Expected Behaviour

Find the pyfluid.dll

#### Actual Behaviour

Not finding the pyfluid.dll

**Comment by rlguy** [comment]
Hi thefudgeishot,

This issue tracker is meant only for issues related to the product distributed on the Blender Market. We only have resources to support the official builds of the product and are unable to debug issues related to building the source on systems/compilers outside of our development environment. See https://github.com/rlguy/Blender-FLIP-Fluids/blob/master/CONTRIBUTING.md#using-the-issue-tracker

Instructions for building the source can be found in this section of the readme: https://github.com/rlguy/Blender-FLIP-Fluids/blob/master/README.md#source-code-dependencies
