### ISSUE TITLE
2.80 RC not compatible with Flip Fluids

### ISSUE THREAD

**Issue by AlainGon** [rlguy/Blender-FLIP-Fluids#466]
2,80 RC has been released but the Flip Fluids plugin does not function, any update available?

**Comment by rlguy** [comment]
Hi,

I am currently on vacation (#463) and am unable to test this directly. I will be able to look into this issue when I am available on the 23rd.

I have had a user confirm that the 2.80 RC release has been working with FLIP Fluids addon, however.

There is a possibility that you will need to wait for the next build of Blender 2.80 if you are using Mac Os. I have heard that there were some problems with the Blender 2.80 RC for MacOS.

**Comment by rlguy** [comment]
Hi,

I have been able to confirm with other users that there is a problem with the Blender 2.80 RC build on MacOS that will prevent the FLIP Fluids addon from loading. If you are using MacOS, you will need to install the latest experimental build of Blender 2.80: https://builder.blender.org/download/

If you are not using MacOS or are still encountering issues with the FLIP Fluids addon, please let me know and provide any error messages found in the Blender system console.

You may retrieve the full error message by opening the Blender System Console. You can open this in Windows with Blender > Window > Toggle System Console or on Linux/MacOS by running Blender from the terminal.
