### ISSUE TITLE
Gracefully ignored TypeError

### ISSUE THREAD

**Issue by gogobd** [rlguy/Blender-FLIP-Fluids#469]
I just successfully completed a simulation, but I got 

Exception ignored in: <bound method MeshObject.__del__ of <flip_fluids_addon.pyfluid.meshobject.MeshObject object at 0x7f20fb8940b8>>
Traceback (most recent call last):
  File ".../.config/blender/2.79/scripts/addons/flip_fluids_addon/pyfluid/meshobject.py", line 40, in __del__
TypeError: 'NoneType' object is not callable

Which won't do any harm, but since the overall quality of the addon is pretty awesome I thought you might want to know.

**Comment by rlguy** [comment]
Hi gogobd,

Thanks for the report! I just had a chance to check this out and have fixed this error.

\- Ryan
