### ISSUE TITLE
UV coordinates

### ISSUE THREAD

**Issue by EverSimo** [rlguy/Blender-FLIP-Fluids#471]
Hi! Is it possible to have UVs? Or some other kind of information or workaround to stick a texture to the fluid surface? Some coordinate that could be extracted internally from flip particles?

**Comment by rlguy** [comment]
Hi EverSimo,

There is not a feature to simulate the flow of UV coordinates in the simulator at the moment. We are not sure whether this will be added in the future as it is a complicated feature to get right in fluid simulation.

We might experiment with this feature while developing a variable viscosity and mixing fluids feature. We plan to start this work after we finish a fluid force field feature that is currently in progress.

For next time, please only use this issue tracker for bugs/issues. You may send questions to us through the Blender Market messaging system, email at flip.fluids@gmail.com, or on our [Facebook](https://www.facebook.com/FLIPFluids), [Twitter](twitter.com/flipfluids), and [BlenderArtists Thread](https://blenderartists.org/t/flip-fluids-addon-a-liquid-fluid-simulation-tool-for-blender). 

See our [technical support guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines) for more info.

- Ryan
