### ISSUE TITLE
Compilation fails because of return in void function

### ISSUE THREAD

**Issue by omgold** [rlguy/Blender-FLIP-Fluids#475]
#### System Information

* FLIP Fluids Version: 6445a1ee8ba637bc222212220886db98ff3e8dff
* Operating System: Linux
* Compiler: gcc 9.1.0

#### Describe the bug

Compilation fails with the follow error:

```
In file included from /tmp/Blender-FLIP-Fluids/src/engine/c_bindings/../clscalarfield.h:30,

                 from /tmp/Blender-FLIP-Fluids/src/engine/c_bindings/../fluidsimulation.h:44,
                 from /tmp/Blender-FLIP-Fluids/src/engine/c_bindings/fluidsimulation_c.cpp:25:
/tmp/Blender-FLIP-Fluids/src/engine/c_bindings/../arrayview3d.h: In member function ‘void ArrayView3d<T>::getViewAsArray3d(Array3d<T>&)’:
/tmp/Blender-FLIP-Fluids/src/engine/c_bindings/../arrayview3d.h:193:16: error: return-statement with a value, in function returning ‘void’ [-fpermissive]
  193 |         return view;
      |                ^~~~
```

IMHO a valid bug at the position in the code. The mentioned function is declared void.

#### To Reproduce

```
mkdir build
cd build
cmake <SRCDIR>
make
```

**Comment by rlguy** [comment]
Hi omgold,

Thanks for letting me know about this! It looks like we have this fixed in our private repository (issue #367) but there was a mistake where this fix was not included in the public repository update. I have updated the file by removing the return statement.

\- Ryan
