### ISSUE TITLE
Domain Bounds Color cannot be changed

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#476]
#### System Information

**Blender Version (including hash): 2.80 f6cb5f54494e**
**FLIP Fluids Version: 9.0.6.0**
**Operating System: Windows 7 64 bit**
**CPU: AMD A8 5600K**
**GFX: -**
**RAM: 8 GB**

#### Describe the bug

Cannot change the Domain Bounds Color parameter. To change it, you need to activate the Display Grid parameter. And you need the color to be available when the Display Bounds option is turned on.

#### To Reproduce

Create a domain and open the Domain Fluid Debugging tab and enable the Display Bounds option.

#### Expected Behaviour

You need to be able to change the border color when the Display Bounds parameter is enabled.

#### Actual Behaviour

The Bounds Color parameter does not become editable.

#### Screenshots

![01](https://user-images.githubusercontent.com/7983249/64880883-f90c1080-d661-11e9-9eb7-6037c4dbc151.jpg)

**Comment by rlguy** [comment]
Hi PavelBlend,

Thanks for the report! This is caused by a mistake in the UI and it has now been fixed. The fix will not be included in the next experimental version (9.0.6.1), but will be added to the version after (9.0.6.2).

\- Ryan

**Comment by PavelBlend** [comment]
It seems that this error was not fixed in 1.0.7.
Or were you planning on adding fixes to this version?

**Comment by rlguy** [comment]
This fix is contained in a development branch that was not included in the v1.0.7 stable release. The fix is located in a branch that adds a few features to the Debug Panel, but this branch was not ready to be merged into a stable branch yet.
