### ISSUE TITLE
I cant install this add-on. NO ERRORS!!!

### ISSUE THREAD

**Issue by Konstantin749** [rlguy/Blender-FLIP-Fluids#481]
I wanted to install flip fluid, did everything according to the instructions. Blender wrote " Modules Installed () from 'G:\\Blender-FLIP-Fluids-master.zip' into 'C:\\Users\\User\\AppData\\Roaming\\Blender Foundation\ \ Blender\\2.81\\scripts\ \ addons" ,and addon did not appear.(Yandex translator)

**Comment by rlguy** [comment]
Duplicate of #474
