### ISSUE TITLE
Is it at all possible to use this to make blood effects which could export to Unity?

### ISSUE THREAD

**Issue by MostHated** [rlguy/Blender-FLIP-Fluids#482]
Hey there,
    I am fairly new to dealing with fluid simulation, but I know Unity is capable of using Alembic, which I believe is something that might allow me to create things like fluid animations and then export them. Does this plugin happen to have the ability to to be controlled in such a way that I could position it on characters and have fluid simulated like blood effects? I am trying to find a way to make things a big more realistic and just over all nicer than what I have going on here https://i.imgur.com/3rZZOWF.mp4. So I am hoping that something like this might help.

Thanks,
-MH

**Comment by rlguy** [comment]
Hi MH,

Blender has an Alembic exporter, but there can be limitations when used with other software. See this documentation topic on Alembic support: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Alembic-Export-Support

I would suggest trying out the [FLIP Fluids Demo](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/FLIP-Fluids-Demo-Addon) to test if the Blender Alembic exporter works for your workflow.

Using a full fluid simulation for this type of effect could be overkill and more difficult to set up compared to other tools in Blender. The simulation meshes can be highly detailed with a large filesize, which could present problems if this is for real-time playback. It is not unusual for a detailed effect to be a few GB in mesh data for a few seconds of animation. The simulator is best used for pre-rendered effects.

You may be able to get a good effect in less time using a Blender Particle system with 'Metaballs' to convert particles to a mesh.

For next time, this issue tracker is generally only meant for posting issues and bugs. Questions should be directed to us on the [Blender Market](https://blendermarket.com/products/flipfluids) or to flip.fluids@gmail.com. The [Blender Artists forum](https://blenderartists.org/t/flip-fluids-addon-a-liquid-fluid-simulation-tool-for-blender/702503), [Facebook](https://www.facebook.com/FLIPFluids), and [Twitter](https://twitter.com/flipfluids) can also be a good place to ask questions.

\- Ryan
