### ISSUE TITLE
'Cannot find fluid engine library: libblpyfluid.dylib'. See system console for error info.

### ISSUE THREAD

**Issue by singulararmchair** [rlguy/Blender-FLIP-Fluids#493]
#### System Information

**Blender Version (including hash):**2.79b
**FLIP Fluids Version:**1.0.8
**Operating System:**OS X 10.10.5
**CPU:**2.5 GHz Intel Core i5
**GFX:**Intel HD Graphics 4000 1024 MB
**RAM:**8 GB 1600 MHz DDR3

#### Describe the bug

Error when clicking the `Bake` button:
`'Cannot find fluid engine library: libblpyfluid.dylib'. See system console for error info.`

#### To Reproduce

I'm just following the basic tutorial here
https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Creating-Your-First-FLIP-Fluids-Simulation

#### Build log

The libblpyfluid.dylib is indeed nowhere to be found. Does not generate when building.
Here's the log: 

> cmake ..
> -- The C compiler identification is AppleClang 7.0.2.7000181
> -- The CXX compiler identification is AppleClang 7.0.2.7000181
> -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
> -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
> -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/X/Downloads/Blender-FLIP-Fluids-master/build`
>

**Comment by singulararmchair** [comment]
nvm, wasn't doing all the steps

**Comment by ByteBeamer** [comment]
I know this may be outdated, but I was wondering how you ended fixing this? I've been getting a very similar error on the latest version when compiling.
