### ISSUE TITLE
[Discussion] Experimental Builds

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids#500]
We have just started releasing weekly experimental builds of the upcoming FLIP Fluids force field feature set! 

[Force Field Experimental Builds
](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Force-Field-Experimental-Builds)

You may use this thread for discussion, feedback, requests, and questions. We are in a busy period of development and may not have time to answer all questions or respond to feedback in a timely manner, but we will be closely monitoring the thread.

## Documentation and Info

- Please read this documentation page for more info about our force field experimental builds: [Force Field Experimental Builds
](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Force-Field-Experimental-Builds)
- [Force Field Object Settings](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Force-Field-Experimental-Builds)
- [FLIP Fluid World panel: Force Field Resolution](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-World-Settings#force-field-resolution)

## Bug Reports

Please report any bugs to this GitHub Issue Tracker by opening a new report. We are usually quite lenient with our bug reporting guidelines, but in order speed up development, we may be more strict with our guidelines for experimental builds. Please read our [Bug Reporting Guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Reporting-Bugs-and-Issues) carefully.

---

\- The FLIP Fluids Addon Development Team

**Comment by tobkum** [comment]
Those features aren't committed into the github repo (yet?), or am I mistaken?

**Comment by rlguy** [comment]
Hi Tobias,

The force field features have not yet been committed to this GitHub repository yet. We usually only update this repo for full version releases.

If you're interested in the source and have access to the force field experimental builds, the full source code can be found by unzipping the installation file (located in ```flip_fluids_addon/source/```).

\- Ryan

**Comment by rlguy** [comment]
My apologies for the ping on this issue thread, just cleaning up the FLIP Fluids GitHub issue tracker. Closing this issue thread as it is no longer needed. 

If there are issues specific to an [experimental build](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Experimental-Builds), they can be reported to this issue tracker. Or for troubleshooting support and feature requests, these can be made through our other regular channels: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines
