### ISSUE TITLE
Libblpy error

### ISSUE THREAD

**Issue by dogevspenguin** [rlguy/Blender-FLIP-Fluids#504]
#### System Information

**Blender Version (including hash):2.83.8
**FLIP Fluids Version:1.07
**Operating System:OSX EI capitan 10.11.6
**CPU:2.5 GHz Intel Core i5
**GFX:AMD Radeon HD 6750M 512 MB
**RAM:10 GB 1333 MHz DDR3

#### Describe the bug

So my computer can't use some compiler and also i found one on reddit and it work... till i bake then it says"'Cannot find fluid engine library: libblpyfluid.dylib'. See system console for error info."The reddit user on window so he has window python and i can't compile on my mac(I already restart blender)

#### To Reproduce

by a mac with OSX EI capitan 10.11.6
CPU:2.5 GHz Intel Core i5
GFX:AMD Radeon HD 6750M 512 MB
RAM:10 GB 1333 MHz DDR3
Download this
https://www.reddit.com/r/blender/comments/eb4ubd/compiled_flip_fluids_here/

#### Expected Behaviour
if you are on mac this should give you error and it dont start baking
#### Actual Behaviour

So it does bake the animation.But not the simulation,nor the white water.But it does create the fluid surface empty in your hierarchy 

#### Screenshot
https://ibb.co/rGdRPfG
https://ibb.co/K7tnq1d
https://ibb.co/9H4GV3r

**Comment by rlguy** [comment]
Hi,

The Reddit post states that the version distributed there is only for the Windows OS, so it will not work for MacOS. You will need to compile the FLIP Fluids addon for your MacOS system for the addon to work.

I am sorry to say that we are only able to provide support for versions the the addon that are distributed through the [Blender Market](https://www.blendermarket.com/products/flipfluids) and this issue tracker is only to be used for issues related to the Blender Market version of the addon.  See: [Guidelines for Reporting Bugs and Issues](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Reporting-Bugs-and-Issues).

\- Ryan
