### ISSUE TITLE
launch bake disabled on mac

### ISSUE THREAD

**Issue by luckychris** [rlguy/Blender-FLIP-Fluids#505]
i am using Flip Fluids on a mac and always the button "launch bake" is disabled. How can i use it? Also launch render doesn't do anything if i tap the button.

**Comment by rlguy** [comment]
Hi,

The Launch Bake/Render operators are only supported on Windows OS at the moment. We were unable to find a good consistent way to launch command line windows on MacOS/Linux ([Documentation](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Helper-Menu-Settings#command-line-tools)).

The copy to clipboard operators can be used to copy the command, and then you can open a MacOS terminal and paste the command, [or set up the command line bake manually](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Baking-from-the-Command-Line). Note: the .blend file will need to be saved for these operators to become available.

It looks like there is a bug where the render operator is displaying on MacOS when it should not. I will fix this.

Hope this helps!

**Comment by luckychris** [comment]
thank you! that works for me! unfortunately the copy-function doesn't work on mac too....but i did manually now and i am happy with it! THANKS!!

**Comment by luckychris** [comment]
just a question...did you try this? 

https://stackoverflow.com/questions/48408278/python-macos-open-new-terminal-window-from-python-passing-command-to-be-exec

**Comment by rlguy** [comment]
Thanks for letting me know about the copy function! I'll do some more testing on MacOS.

We tried the Appscript/Applescript module workaround, but we do not want to install modules on the user's system that are not already in the Python interpreter distributed by Blender.

**Comment by rlguy** [comment]
Had a chance to test and add some fixes for this issue which turned out to affect both MacOS and Linux. This fix is now available in [experimental version 9.0.9.11](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Release-Notes#experimental-versions-909x).
