### ISSUE TITLE
error when trying baking from command line on mac

### ISSUE THREAD

**Issue by luckychris** [rlguy/Blender-FLIP-Fluids#506]
i am trying to bake the simulation as you described here:

https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Baking-from-the-Command-Line

and got the error :

line 2, in <module>
    bpy.ops.flip_fluid_operators.bake_fluid_simulation_cmd()
  File "/Users/xyz/Downloads/Blender2.92alpha/Blender.app/Contents/Resources/2.92/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.flip_fluid_operators.bake_fluid_simulation_cmd" error, could not be found

what am i doing wrong?

**Comment by rlguy** [comment]
Hi luckychris,

What version of the FLIP Fluids addon are you using?

This error message means that the FLIP Fluids installation is missing the _bake_fluid_simulation_cmd_ operator for some reason or that the FLIP Fluids addon is not installed on this version of Blender. This operator should be available in versions **1.0.5 (Jun 04 2019)** and later. The current version is **1.0.9 (Nov 26 2020)**.

**Comment by rlguy** [comment]
Hi again, I just noticed you are using Blender 2.92. The FLIP Fluids addon has not been updated for Blender 2.92 yet. This could be a possible cause for the issue.

Blender 2.92 is still in early development and we need to wait closer to the release date for this version to become more stable until we can add support. The current release date for 2.92 is February 24, 2021.

**Comment by luckychris** [comment]
i tried the older Blender version -> works! Thank you! When will you update flip fluid for the newer Blender version?

**Comment by rlguy** [comment]
Thanks for the update! I will close this issue and have created issue #507 for tracking Blender 2.92 support.

We typically begin testing and adding support for new versions a few weeks prior to the Blender release. In early development, Blender can change rapidly which means if we add support today, it might not be supported tomorrow.
