### ISSUE TITLE
libblpyfluiddebug.dll is missing!

### ISSUE THREAD

**Issue by stefanosallemi** [rlguy/Blender-FLIP-Fluids#510]
#### System Information

**Blender Version (including hash):** 2.90.1
**FLIP Fluids Version:** 1.0.9
**Operating System:** Windows 10 x64
**CPU:** i7-8750H
**GFX:**
**RAM:** 16 GB

#### Describe the bug

when i try to bake the domain it tells me "error backing fluid simulation, cannot find libblpyfluiddebug.dll"

#### To Reproduce

press bake

#### Expected Behaviour

it should to bake it

#### Screenshots

Ihttps://user-images.githubusercontent.com/76653440/103173246-f125af00-4859-11eb-98a1-8f9ccc087784.png

**Comment by rlguy** [comment]
This error indicates that the program has not been fully compiled/built for your system. See [building instructions](https://github.com/rlguy/Blender-FLIP-Fluids#building). We are unable to provide support for building the addon and this tracker is meant to be used for bug reports related to the Blender Market product.
