### ISSUE TITLE
Error : CMake Error: The source directory "D:/Files/My dev/Flip fluids build/Blender-FLIP-Fluids" does not appear to contain CMakeLists.txt. Specify --help for usage, or press the help button on the CMake GUI.

### ISSUE THREAD

**Issue by YoussefHossam55** [rlguy/Blender-FLIP-Fluids#511]
I get an error when typing cmake .. -G "MinGW Makefiles" 
error : CMake Error: The source directory "C:/Users/User_name/Downloads/Blender-FLIP-Fluids-master" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by rlguy** [comment]
Hi,

Refer to the project README for the correct methods for how to build/compile the FLIP Fluids addon: https://github.com/rlguy/Blender-FLIP-Fluids#building

Please note that this issue tracker is only meant for issues/bugs related to the Blender Market version of the FLIP Fluids addon. We are also unable to provide support for building and diagnosing issues related to building the addon on the wide variety of systems and system setups.
