### ISSUE TITLE
Inflow Object it does not generate particles

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#512]
#### System Information

**Blender Version (including hash):** 2.90.1 (rB3e85bb34d0d7)
**FLIP Fluids Version:** v9.0.9.11
**Operating System:** Win 10 64 bit
**CPU:** AMD A8 5600K APU with Radeon HD Graphics 
**GFX:** -
**RAM:** 16 GB

#### Describe the bug

The inflow object does not create liquid particles.

#### To Reproduce

Bake the liquid in this scene.
[inflow_not_working.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/5793268/inflow_not_working.zip)
You will see that the `inflow` object does not create particles.

#### Expected Behaviour

The particles must be produced by this object.

#### Actual Behaviour

No particles are emitted.

#### Screenshots

![01](https://user-images.githubusercontent.com/7983249/104134603-bf553200-539b-11eb-86cb-8fd49c894bde.jpg)

**Comment by rlguy** [comment]
Hi PavelBlend,

Thanks for the report! It looks like this is a geometry issue with the inflow object. The mirror modifier is doubling all of the geometry, so there are duplicates for each vertex. This modifier is also creating non-manifold geometry. Doubled geometry is like having an object with infinitely thin walls and the object will be computed as empty.

If you apply the mirror modifier, you can merge the double geometry in edit mode to fix the issues:

![doubled_geometry](https://user-images.githubusercontent.com/4285191/104136428-d6b7ff00-534a-11eb-86f7-f70869e09cdd.jpg)

Hope this helps!

\- Ryan
