### ISSUE TITLE
New/

### ISSUE THREAD

**Issue by KIO04** [rlguy/Blender-FLIP-Fluids#514]
1) Lava preset and material. It would be very interesting and useful for simulating behaviour of lava, like in very high-cost fluid engines (FLIP Solver).

2) NO MORE FLIP. New technology of calculating fluid behaviour by each voxel itself.

3) New rigid bodies (simple) like wood, steel, rock. Like in tutorial, but more correctly.

Thanks in advance.

**Comment by rlguy** [comment]
Hi,

Thank you for your suggestions. We have noted these requests. Just letting you know that feature requests are not accepted on the GitHub issue tracker: [Guidelines For Feature Requests](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests).

\- Ryan
