### ISSUE TITLE
Error when pressing Bake Button in Flip Fluids | Blender 2.93 Alpha

### ISSUE THREAD

**Issue by Helpmehelpyou309** [rlguy/Blender-FLIP-Fluids#528]
#### System Information

**Blender Version: 2.93 Alpha**
**FLIP Fluids Version: 1.0.9**
**Operating System: Windows 10**
**CPU: I5 8400**
**GFX: GTX 1060 6GB**
**RAM: 24GB**

#### Describe the bug

I downloaded Flip Fluids version 1.0.9 today, it got installed and was showing up, however, whenever I tried to bake, it started to show an error message and wasn't stopping the bake too.

#### To Reproduce

Click on Bake on Domain Settings of Flip Fluids

#### Screenshots

![Screenshot 2021-04-08 141910](https://user-images.githubusercontent.com/71591835/113997046-67807700-9875-11eb-9388-58cd7ec6de4f.jpg)

**Comment by rlguy** [comment]
Hi,

See this issue thread for how to solve this error: #525 

The latest version of the FLIP Fluids addon, v1.0.9b on the Blender Market, adds compatibility fixes for Blender 2.93. The current source code on this repository also contains this fix.

Hope this info helps!

\- Ryan
