### ISSUE TITLE
Rigid bodies and fluid interaction

### ISSUE THREAD

**Issue by KIO04** [rlguy/Blender-FLIP-Fluids#532]
Good daytime! Will in future development be interaction rigid bodies and fluid (maybe custom). In my opinion it isn't a hard one task, and will be useful for the community of Flip Fluid. I would really appreciate your answer, thanks!

**Comment by rlguy** [comment]
Hi, we do not have plans to add this type of feature. A major limitation is that Bender's simulation systems cannot interact with each other at the same time ([See Limitations: Fluid and Rigid Body Interaction](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Limitations-of-the-FLIP-Fluids-addon#fluid-and-rigid-body-interaction)). Another issue is that this is a difficult topic in simulation and the complexity of implementing this type of system may be outside of the scope of the FLIP Fluids project.
