### ISSUE TITLE
[MacOS] Blender 2.93 Support for M1 MacOS ARM 64-bit build

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids#537]
This issue is to track support for the MacOS ARM 64-bit build for Blender 2.93. This Blender build adds native support for the Mac M1 processor and the daily builds can be downloaded at https://builder.blender.org/download/

At the moment, the FLIP Fluids addon is not supported on this build of Blender. The FLIP Fluids simulator is currently only supported on Intel/AMD 64-bit architecture and we will need to port the simulator to be supported for the ARM architecture.

Ideally, porting our simulator to ARM should be straightforward and accomplished by simply cross compiling to ARM on our Mac Intel system. However, it has been reported by two of our Mac M1 testers that a simple cross compilation of our simulator is resulting in intermittent baking crashes.

To create a functioning port we will need access to a Mac M1 system in order to use the debugger and solve the issue. At the moment we are looking into purchasing our own Mac M1 system.

This issue is currently a high priority and we hope to solve this issue before the release of Blender 2.93 (May 26, 2021).

**Comment by bluepuppy** [comment]
Thanks for the update.  Looking forward.

**Comment by rlguy** [comment]
[FLIP Fluids Experimental 9.0.9.21](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Experimental-Builds) adds preliminary support for the Apple Silicon M1 chip using the new Blender 2.93.0 Beta MacOS Arm 64 bit build.

The way that we build and package the MacOS side of the addon has changed and we are looking for feedback from those who have access to an Apple M1 system and also those using Apple Intel systems:
- Please let us know if you encounter any error messages.
- If you have access to a MacOS M1 system, feedback on whether you can run a simulation using this addon version and the Arm Blender version would be greatly appreciated.
- If you do not have access to an M1 system, we would also appreciate feedback on whether the simulator still runs on your MacOS Intel system on regular versions of Blender.
- A '_Yes, it runs_' answer is just as valuable to us as a '_No, it does not run_' answer.
- Feel free to let us know in this thread, or on the Blender Market, our social media pages, or through support at flipfluids.com.

[The Blender Arm 64bit build can be downloaded here](https://builder.blender.org/download/)

![macos_arm_64bit](https://user-images.githubusercontent.com/4285191/118166850-d738d300-b3da-11eb-8c91-d4589518ba6f.jpg)

**Comment by rlguy** [comment]
MacOS ARM will be officially supported in the next stable version of the FLIP Fluids addon (version after 1.0.9b). The ARM build of Blender 2.93 has been tested and is supported in FLIP Fluids Experimental 9.0.9.21 or later.
