### ISSUE TITLE
[Feature Request] Extended geometry attributes for procedural textures

### ISSUE THREAD

**Issue by Frautcres** [rlguy/Blender-FLIP-Fluids#538]
With the introduction of velocity and age as a geometry attribute, a long time silent wish of mine isn't that far from reach. I've had ambitions to have explicitly defined parameters 

Here are two examples in which I feel it could be used:
![image](https://user-images.githubusercontent.com/18382191/118001744-641d5700-b31d-11eb-9bac-08369509fe44.png)
Capturing total surface movement!
Pictured in this example is the initial Vertex color or UV coordinate input and geometry attribute output for a simulation, which could be stirred around however the user may like, for example the user could use this to project higher-frequency textures or rather algae on the surface of a lake.

![image](https://user-images.githubusercontent.com/18382191/118004794-2837c100-b320-11eb-9980-baa9dab148f6.png)
Toothpaste and other cycling patterns!
As shown here in this generic image I found 
![image](https://user-images.githubusercontent.com/18382191/118004946-51585180-b320-11eb-9dc2-eb6c21aa29f0.png) some toothpastes have cyclic patterns which could be rather complex to handle as multiple fluid materials mixed together, so I would suggest a more efficient alternative would be to texture the outside surface using an emitter which would capture the cyclic texture space, in the example that I have given you could use the geometry attribute as a texture coordinate to sample from a cross section of what the paste should look like.

The problems that I see as far as implementation is currently is a matter of interpreting and interpolating the input geometry as a continuum of channels, and how to make the interface usable, the first I lack experience in, the latter I'll give my current idea, however I haven't yet seen the latest build which may contain some interface for the new geometry attributes: I could see the geometry attributes being its own section, with settings and or toggles to enable each geometry attribute if needed/unneeded, with settings pertaining to units of measurement if scale is important, and I could see this being an important section for more advanced mixture settings if and when that feature becomes more useable.

**Comment by rlguy** [comment]
My apologies for the ping on this issue thread, just cleaning up the FLIP Fluids GitHub issue tracker. 

The purpose of the FLIP Fluids GitHub issue tracker is for issues and bugs only. Feature development and requests are handled internally and requests can be made through alternative channels. See: [Guidelines for Feature Requests](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests)
