### ISSUE TITLE
Flip Fluids for 3.0.0alpha

### ISSUE THREAD

**Issue by luckychris** [rlguy/Blender-FLIP-Fluids#539]
ok, maybe you don't support it yet ;)

I love FlipFluids and bought it long time ago. Question: is Blender 3.0.0alpha already supported?

I tried with the last stable build from april and also with the experimental build, but none of this worked. First i could install but got an error when using. Second i couldn't even install (without any error, but didn't appear in the list in preferences)

**Comment by rlguy** [comment]
Hi! We're tracking issues related to Blender 3.0 in this issue thread: #535 

I haven't tested a recent daily build of Blender 3.0 yet, but can tomorrow.

Would you be able to add the error message to the other thread and also attach your Blender system info file (Blender > Help > Save System Info).
