### ISSUE TITLE
Drag Force option (as in RealFlow)

### ISSUE THREAD

**Issue by antonzax36** [rlguy/Blender-FLIP-Fluids#540]
Hi everyone.
I just moved from RealFlow to FlipFluids and I can't find the Drag Force option as in RealFlow 
[video example](https://www.youtube.com/watch?v=ICkUTw-uRDU)

When my character goes to swimmingpool water simulates crazy, I did everything and read all the wiki but still... 
[photo 1](https://photos.app.goo.gl/ukJLvTPCe7dHfpuu8)
[photo 2](https://photos.app.goo.gl/x6Jr39DcZT2D5veL6)
[photo 3](https://photos.app.goo.gl/9PzaA1D69YFMk8YX8)
[photo 4](https://photos.app.goo.gl/G17QDxJdpRXZt98a7)

**Comment by rlguy** [comment]
Hi antonzax36,

Thanks for the report! Our FLIP Fluids addon is a separate software from RealFlow, does not intend to mimic every behaviour and setting of RealFlow, and will work differently, but maybe we can try to tackle this in future development.

From the images, this looks like an issue of scene scale and animation speed. And animation may be too fast for the simulation scale, causing a large splash. Note that 1 Blender Unit is equal to 1 meter in the simulator by default. See this topic for more information: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-World-Settings#world-size

This GitHub issue tracker is not currently accepting feature requests for scene troubleshooting requests. See this topic for more information on how to request technical support: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines

\- Ryan
