### ISSUE TITLE
Flip fluids seem to not be installing correctly, Is there a solution?

### ISSUE THREAD

**Issue by Yehonam** [rlguy/Blender-FLIP-Fluids#545]
**Blender Version (including hash):Blender 2.93
**FLIP Fluids Version: v1. 0.9
**Operating System: Windows 10
**CPU: Intel(R) Celeron(R) N4000
**GFX:**
**RAM: 4GB

Hi There,
I successfully compiled the addon due to a tip, but now my problem is that when I try to install the compiled addon into Blender, it tells me to restart so I do just that, but when I do it still tells me to restart and it doesn't change.

I expected it that as soon as I bring the compiled version into Blender, it accepts the addon and I can use it for my projects

It still stays there saying that I should restart Blender to complete installation of the Flip Fluids addon.

![Flip fluids not installing properly 2](https://user-images.githubusercontent.com/88112545/127480599-dfeb7e16-5b6b-41fc-bee7-a447c9385d50.png)
![Flip fluids not installing properly](https://user-images.githubusercontent.com/88112545/127480608-3225240f-4c80-460b-baa9-8ec3b530d5ce.png)

**Comment by Yehonam** [comment]
But for some reason when I try this on another computer it works, do you please have any answer to this?

**Comment by rlguy** [comment]
Hi, as mentioned in issue #544, this issue tracker is only meant for issues related to the full Blender Market version of the addon.

I would suggest verifying the installation and making sure that the addon has not been installed multiple times as well as that the addon is installed to a location that has permission to write files: [Addon Installation: Troubleshooting](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Addon-Installation-and-Uninstallation#troubleshooting).
