### ISSUE TITLE
Keeping the Last Frame of Fluid Bake

### ISSUE THREAD

**Issue by enzyme69** [rlguy/Blender-FLIP-Fluids#547]
Dear Flip Fluid developer,

Can we perhaps make the last frame of fluid sims that is baked = as the last mesh, instead of it's resetting to 1st frame?

**Comment by rlguy** [comment]
Hi, thanks for sending us a message! However, this issue tracker is only meant for bugs or issue reports and feature requests or questions are not accepted on the tracker. See this document for more information and for proper channels to contact us about feature requests: [Guidelines for Feature Requests](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests).

I am not sure if I understand what this request is. Would you be able to expand on what you mean by this? You may elaborate in this issue thread and we can make a note of the request.
