### ISSUE TITLE
Keyed Inflow becomes thinner and longer - Curve guide Force

### ISSUE THREAD

**Issue by sensenku** [rlguy/Blender-FLIP-Fluids#551]
Hi. I have a long Bezier curve around bottle. I use Inflow around the object and it has start and end keyframes. When keyframe ends after a few keyframes the liquid becomes thinner and longer than it was before. How can I make the liquid to preserve its shape?

**Comment by rlguy** [comment]
Hi, this issue tracker is only meant for bugs related to the FLIP Fluids addon and is not the correct place to request scene troubleshooting help. Please send us a message through the Blender Market and attach a .blend file.

See our [Scene Troubleshooting Guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Requesting-Scene-Troubleshooting-Help).

**Comment by sensenku** [comment]
Thanks for reply
