### ISSUE TITLE
Update FF does not work

### ISSUE THREAD

**Issue by luckychris** [rlguy/Blender-FLIP-Fluids#554]
if i try to update FF via the button i got this:

![image](https://user-images.githubusercontent.com/232549/132121859-8031fce9-069e-4db5-ba39-5286fc38a873.png)

Blender 2.92
FF 1.0.9

Macbook

Big Sur 11.4

**Comment by rlguy** [comment]
Hi, it looks like the website that serves the update file is currently down, but should be back up in the next few days.

Note that this operator does not update the addon, it only supplies a message whether there is an update or not:

![image](https://user-images.githubusercontent.com/4285191/132134574-92228c76-733f-4bca-a623-7afb14e76bf5.png)

The latest versions is FLIP Fluids v1.1.0. See this topic for how to download the FLIP Fluids addon from the Blender Market: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Frequently-Asked-Questions#how-do-i-download-the-flip-fluids-addon-from-the-blender-market

We will actually be removing this operator in the next update as it is a common source of confusion.
