### ISSUE TITLE
Error: 'Nonetype has no attribute to_struct' when FLIP Fluids object is a Text Object Type

### ISSUE THREAD

**Issue by luckychris** [rlguy/Blender-FLIP-Fluids#556]
happens in Blender 3.0 alpha and 2.92 and 2.93 as well

![image](https://user-images.githubusercontent.com/232549/132164520-8c8296fd-2b90-4d5b-a92b-34e2544da8a5.png)
![image](https://user-images.githubusercontent.com/232549/132164546-d6a9a916-ce9b-4a86-a50f-9f52274bfb50.png)

![image](https://user-images.githubusercontent.com/232549/132164637-f03c7a99-1ea9-4101-ad29-dd4e04dd4e17.png)

**Comment by luckychris** [comment]
you can checkout and reproduce the error with this blend file: https://www.dropbox.com/s/rxwa82or6gw0zwr/ff_bug.blend?dl=0

**Comment by luckychris** [comment]
system console output:

Traceback (most recent call last):
  File "/Users/c/Library/Application Support/Blender/3.0/scripts/addons/flip_fluids_addon/bake.py", line 2441, in bake
    __launch_bake(datafile, cache_directory, bakedata, savestate_id)
  File "/Users/c/Library/Application Support/Blender/3.0/scripts/addons/flip_fluids_addon/bake.py", line 2428, in __launch_bake
    __initialize_fluid_simulation(fluidsim, data, cache_directory, bakedata, savestate_id)
  File "/Users/c/Library/Application Support/Blender/3.0/scripts/addons/flip_fluids_addon/bake.py", line 1368, in __initialize_fluid_simulation
    data.force_field_objects = __add_force_field_objects(fluidsim, data, bakedata)
  File "/Users/c/Library/Application Support/Blender/3.0/scripts/addons/flip_fluids_addon/bake.py", line 1341, in __add_force_field_objects
    field_object.update_mesh_static(mesh)
  File "/Users/c/Library/Application Support/Blender/3.0/scripts/addons/flip_fluids_addon/pyfluid/forcefield.py", line 42, in update_mesh_static
    mesh_struct = mesh.to_struct()
AttributeError: 'NoneType' object has no attribute 'to_struct'
------------------------------------------------------------
SIMULATION TERMINATED DUE TO ERROR:
	'NoneType' object has no attribute 'to_struct'

Thank you for using FLIP Fluids!
------------------------------------------------------------

**Comment by rlguy** [comment]
Thanks for the report! I am able to reproduce the issue. 

The FLIP Fluid Volume Force type object (as well as Inflow/Outflow/Fluid/Obstacle) must be a Blender 'MESH' type object and this is what is causing the error. It looks like there is a bug that is causing a 'TEXT' type object to be able to be accepted  as a FLIP Fluid object type where this is not supported.

Until this issue is fixed, a workaround can be to convert this object to a 'MESH' type object:

![image](https://user-images.githubusercontent.com/4285191/132167703-90f99c77-16fa-4e60-bd0e-8ca19af6fc20.png)

**Comment by luckychris** [comment]
thanks for your fast answer. Yes, indeed, converting to mesh helps.

**Comment by rlguy** [comment]
This issue has been fixed and will be available in the next experimental release on September 17, 2021.

If a text type object is set to a FLIP Fluid object type, a popup error will be displayed:

![image](https://user-images.githubusercontent.com/4285191/132250363-f07699e0-80f1-4858-a917-c936e054cc17.png)

Popup windows will now be displayed for other unsupported object types as well: Metaballs, Fonts, Volumes, Armature Bones, Lights, Light Probes, Grease Pencils, Lattices, Cameras, and Speakers.
