### ISSUE TITLE
baking statistics not available

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#558]
@rlguy hello.

I noticed a problem like this:
when I start baking using the command line, baking statistics are not available to me.
I start baking with a button `Command Line Tools > Launch Bake` in the N panel.
I do bake a few times.
First, I bake the first 100 frames, then from 100 to 200 frames, and so on.
When the addon bakes 100 frames, I close the black cmd window.
After that I open the blender and I don't see the statistics.
Then I start baking again with cmd.
I start to bake from 100 frames to 200.
When the addon has baked 200 frames, I close the cmd window again.
Then I start the blender and see statistics only from the first bake for frames from 0 to 100.
I have come to the conclusion that baking statistics will be saved if the addon exits gracefully.
But I am not closing the bake correctly. I just close the cmd window and the addon does not save statistics.
I examined the cache folder.
I noticed that statistics for frames 100 to 200 are stored in the `temp` folder and not in the `flipstats.data` file.
Is it possible to make the addon always save statistics?

**Comment by rlguy** [comment]
Hi, thanks for the report! I just had a chance to look into this.

This looks like a bug where the statistics were not being updated when loading the .blend file. In older versions of the addon, when loading a .blend file, the stats in the ```temp``` folder would be processed and moved into the ```flipstats.data``` file. At some point in development, this functionality was accidentally removed.

This has been fixed and will be available in the next experimental version (9.1.2, release TBA). After this fix, the .blend file fill need to be reloaded for the statistics to be updated and saved.
