### ISSUE TITLE
Use more than one uv map on the generated fluid.

### ISSUE THREAD

**Issue by baronlanteigne** [rlguy/Blender-FLIP-Fluids#561]
Maybe there is a workaround to what I'm trying to do. I'm using UVproject modifiers and two cameras to create two looks. In the material, I cross fade from one to the other. It works if I use two different uv maps but whenever I load a new fluid mesh, (aka, change frame), it deletes all the uv maps meaning I'd have to recreate the uv maps and render each frame one by one during the transition. I understand each fluid mesh is a different object but because I don't manually edit the uv map and generate it using the modifier, all I would need is for the newly loaded mesh to not clear the existing uv map.. or maybe just be created with the two uv maps I need for the modifiers and material to work.

**Comment by rlguy** [comment]
For every frame, the object's data needs to be cleared, which includes UV maps and a few other items in the Object Data Properties. We use a workaround within the addon to transfer materials between frames (which are also stored in object data), so I'll see if this type of workaround works for transferring UV maps.

A workaround would be to [export the simulation to the Alembic (.abc) format](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Alembic-Export-Support), which will not clear object data between frames.

**Comment by rlguy** [comment]
We weren't able to transfer the UV Map layer objects exactly between frames, but we are able to initialize new UV layers when loading a new frame.

With this change, the addon should automatically create new UV layers with the same names, active layer, and active render status.

This functionality will be available in the next stable version of the FLIP Fluids addon (v1.2.0) to be released at the end of next week.

**Comment by baronlanteigne** [comment]
> we are able to initialize new UV layers when loading a new frame.
> 
> With this change, the addon should automatically create new UV layers with the same names, active layer, and active render status.

Wow yes! This is exactly what I would need! Thank you!
