### ISSUE TITLE
[FLIP Fluids v9.1.4] Fluid mesh generation error - invalid large mesh data generation

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#563]
#### System Information

**Blender Version (including hash):** 2.93.5, branch: master, commit date: 2021-10-05 12:04, hash: `rBa791bdabd0b2`
**FLIP Fluids Version:** 9.1.4
**Operating System:** Windows-10-10.0.19041-SP0 64 Bits
**CPU:** AMD A8 5600K
**GFX:** AMD Radeon HD 7560D ATI Technologies Inc. 4.5.13399 Core Profile Context 15.201.1151.1008
**RAM:** 16 GB

#### Describe the bug

No fluid mesh is created. I cannot see the fluid mesh in the `3D Viewport`. I examined the cache folder and saw that the `000000.bobj`, `000001.bobj`, `000002.bobj`... files exist. But the size of these files is extremely large. Domain resolution is 50. The file size is exactly `1 000 000 000` bytes:
![01](https://user-images.githubusercontent.com/7983249/142446665-3e516ea2-2719-42e1-b636-23e0705e03d2.jpg)

#### To Reproduce

Bake the simulation in this scene. You will notice very low performance in the 3D Viewport if animation is enabled (the spacebar is the default).

[flip_fluids_test.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/7564018/flip_fluids_test.zip)

**Comment by rlguy** [comment]
Thanks for the report! My apologies, it looks like I had uploaded the wrong branch build to the Blender Market files. The incorrect branch was for testing creation of large files in the cache (1 000 000 000 Byte surface files).

I have uploaded the correct 9.1.4 branch in the _Experimental_Builds_(unzip)_(18_nov_2021).zip_ package.
