### ISSUE TITLE
Jitter not working

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#564]
#### System Information

**Blender Version (including hash):** 2.93.5, branch: master, commit date: 2021-10-05 12:04, hash: `rBa791bdabd0b2`
**FLIP Fluids Version:** 9.1.4 (18 november)
**Operating System:** Windows-10-10.0.19041-SP0 64 Bits
**CPU:** AMD A8 5600K
**GFX:** AMD Radeon HD 7560D ATI Technologies Inc. 4.5.13399 Core Profile Context 15.201.1151.1008
**RAM:** 16 GB

#### Describe the bug

The `Particle Jitter` parameter does not work if the `Jitter Surface Particles` checkbox is disabled.

#### To Reproduce

Bake this scene:
[jitter_test.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/7565461/jitter_test.zip)

#### Screenshots
Bug:
![01](https://user-images.githubusercontent.com/7983249/142483242-c994e367-a875-46ff-b0d6-39bbdf007664.jpg)

Correct:
![02](https://user-images.githubusercontent.com/7983249/142483295-c5a39193-e2da-49e9-8c09-a34de96a34da.jpg)

**Comment by rlguy** [comment]
Thanks for the report! Looks like this bug was caused by incorrect math. This has been fixed and will be available in the next version (v1.2.0).

![jitter_correction](https://user-images.githubusercontent.com/4285191/142493437-5b47a0e4-12a9-4333-ae70-685f3c09b318.jpg)
