### ISSUE TITLE
Color Attribute is not active

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#565]
#### System Information

**Blender Version (including hash):** 2.93.5, branch: master, commit date: 2021-10-05 12:04, hash: `rBa791bdabd0b2`
**FLIP Fluids Version:** 9.1.4 (18 november)
**Operating System:** Windows-10-10.0.19041-SP0 64 Bits
**CPU:** AMD A8 5600K
**GFX:** AMD Radeon HD 7560D ATI Technologies Inc. 4.5.13399 Core Profile Context 15.201.1151.1008
**RAM:** 16 GB

#### Describe the bug

The `Color Attribute` parameter for the fluid object is inactive even if the `Generate Color Attributes` checkbox for domain is enabled.
For the `Color Attribute` parameter to become active, you must additionally enable the `Generate Source ID Attributes` checkbox.
There is currently no way to enable the `Color Attribute` independently of the other attributes.

#### Screenshots

No active color:
![01](https://user-images.githubusercontent.com/7983249/142574606-c9d4828e-00f2-47dc-aa04-347a477e0808.jpg)
![02](https://user-images.githubusercontent.com/7983249/142574624-303054fb-f6df-4968-b394-1caba1235c26.jpg)

Active color:
![03](https://user-images.githubusercontent.com/7983249/142574637-9b806623-9c84-4224-a260-c9aeedc9ed29.jpg)
![04](https://user-images.githubusercontent.com/7983249/142574643-32ad8d8f-2633-4afc-9b17-a90349023f99.jpg)

**Comment by rlguy** [comment]
Thanks for the report! It looks like this bug was caused by a logic error in the UI display for fluid and inflow objects. This has been fixed and will be available in the next version (v1.2.0).
