### ISSUE TITLE
Pyhton: Error (Python: Traceback)

### ISSUE THREAD

**Issue by zbob90** [rlguy/Blender-FLIP-Fluids#570]
Hello,
I just added the addon. Whenever I try to bake this error message pops up. I tried changing the cache location, but this message keeps appearing. Can somebody help me please?

![IMG_0188](https://user-images.githubusercontent.com/82236930/149560598-c954677e-0d93-4d02-957c-0b7d9ab79f7c.jpg)

**Comment by rlguy** [comment]
Hi, this error can happen if the addon version is not compatible with the Blender version or if the addon has not been installed correctly. For Blender 3.0, make sure you are using at least FLIP Fluids version 1.2.0.

Make sure to follow the installation instructions: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Addon-Installation-and-Uninstallation

And if the issue still persists, check the installation troubleshooting page: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Addon-Installation-Troubleshooting
