### ISSUE TITLE
Baking on multiple computers 

### ISSUE THREAD

**Issue by TIANMINGSHI** [rlguy/Blender-FLIP-Fluids#575]
I have a lot of computers, 2700x 2600 i7, yes, I have 3 computers, my question is, how can I use three computers to bake fluids in a scene at the same time, kind of like distributed rendering, it can speed up my baking Speed and rendering speed, I haven't found a similar introduction on the Internet. Is there an official answer in this regard?

**Comment by rlguy** [comment]
Hi, there is not a distributed computing benefit from using this type of simulator. Unlike rendering, many physics simulation computations are sequential in nature (each frame depends on the previous frame) and this simulator is not highly parallelizable. See this topics for more info: [Limitations of the FLIP Fluids addon: Distributed Computing](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Limitations-of-the-FLIP-Fluids-addon#distributed-computing).
