### ISSUE TITLE
Gumroad Flipfluid file will not install. Windows can not open the file either and presents the error message - compressed zip folder is invalid

### ISSUE THREAD

**Issue by Zephers-X** [rlguy/Blender-FLIP-Fluids#576]
#### System Information

**Blender Version (including hash):** 3.1.0
**FLIP Fluids Version:** 1.3.0
**Operating System:** Windows 11 Home
**CPU:** 11th Gen Intel(R) Core(TM) i7-11370H 
**GFX:** RTX 3050ti Laptop
**RAM:** 32

#### Describe the bug

Windows says the installation zip file is empty or corrupted. Blender will install the file, but can not read it. The file can not be unzipped either.

#### To Reproduce

Download the FLIP_Fluids_addon_1.3.0_stable_(11_mar_2022) file from Gumroad and try to install/ view contents

#### Expected Behaviour

Unzipping will lead to this error message: 
<img width="301" alt="image" src="https://user-images.githubusercontent.com/88756787/158919898-2706cbc8-d002-43e5-adf7-dd93d5809127.png">

Trying to open will lead to this error message: 
<img width="297" alt="image" src="https://user-images.githubusercontent.com/88756787/158919950-4e2ade68-0f86-4d27-a1b1-a1d6ca23e672.png">

#### Actual Behaviour

A description of what actually happened.

**Comment by rlguy** [comment]
Hi, I just had a chance to take a look at the file and can verify that the Gumroad installation file is correct and functional.

I would suggest re-downloading the file and installing again. The file may not have fully downloaded or may have become corrupted during download.

Methods to verify the installation file and installation within Blender can be found in this topic: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Addon-Installation-Troubleshooting

Let us know if the issue has been solved or if the issue still persists.

**Comment by Zephers-X** [comment]
Hi,
Thanks, 

I did a reinstall now and its working as intended. Not sure what was going on before, I had downloaded the file 2 times on my desktop and laptop. All good now though, thanks.
