### ISSUE TITLE
Domain cache path ending in backslash on Linux causes simulation not to work

### ISSUE THREAD

**Issue by mariusiatan** [rlguy/Blender-FLIP-Fluids#577]
#### System Information

**Blender Version (including hash):** 3.1.0
**FLIP Fluids Version:** 1.3.0
**Operating System:** Linux 64-bit
**CPU:** Intel Xeon E5-2670
**GFX:** N/A
**RAM:** 32 GB

#### Describe the bug

A Blender project using a FLIP cache, transferred from Windows to Linux, doesn't work unless the trailing ```\``` from the domain cache path is removed. This issue has been present in previous Blender/FLIP Fluids versions as well. It happens when rendering the project from the command line in Linux.

#### To Reproduce

1. Create a Blender project on a Windows machine and bake the FLIP cache. The domain cache path will have a trailing ```\```
2. Transfer the project to a Linux machine
3. Attempt to render the project, using Blender's command line mode

#### Expected Behaviour

The project should render normally

#### Actual Behaviour

The project doesn't render correctly, the FLIP cache isn't loaded. Removing the trailing ```\``` from the domain cache path solves the issue.

**Comment by rlguy** [comment]
Thanks for the report! I am able to reproduce this issue and this seems to affect both Linux and MacOS. This issue will prevent the cache from being correctly loaded in both the viewport and render.

It looks like backslashes can cause this issue on Linux/MacOS if the filepath contains a backslash, including a trailing backslash and  paths with mixed forward/backslashes. Ex:
- ```//cache_directory\```
- ```//cache\directory```
- ```//path/to\cache/directory```

I have fixed this for the next version of the FLIP Fluids addon (release TBD). 

Until this fix is available, the workaround would be to manually correct the cache directory to only include forward slashes when the .blend file is saved on Windows.
