### ISSUE TITLE
Flip Fluids getting stuck at "calculating time remaining" and causing blender to be very unresponsible/laggy

### ISSUE THREAD

**Issue by gluttonium** [rlguy/Blender-FLIP-Fluids#579]
I installed the **lastest release of Flip Fluids**  and ran into a problem causing some **major problems** with the _addon and my system_.

Since I installed the latest release **(march 30th 2022 ver. 1.3.1)** I can't bake the simulations.
The previous release version **(ver. 1.3.0)** works just fine without any problems but the lastest release can't bake a simulation without being stuck at "calculating remaining time" and making blender _very laggy and unrespondable/running slow_ and using up to _80-90% of my ram (16GB in total: 2x8GB 2666 MHz)_. Also trying to quit the attempted baking process fails all the time being stuck "calculating time remaining" and not actually getting the process to quit properly.
Sometimes closing and restarting blender will quit the baking process, sometimes it's still stuck at "calculating time remaining".
If my system becomes _too unrespondable_ and _I can't use the curser to get anywhere and can't even open up the task manager_ I have to _turn off my device and reboot_ it. Then the baking process is finally quit properly and my device is working fine again but baking the simulation still doesn't work...

### System information

Blender Version: 3.1.0, master, 2022-03-08 18:16, c77597cd0e15
Addon Version: A FLIP Fluid Simulation Tool for Blender (v1.3.1 Stable 30-MAR-2022)
OS: Windows-10-10.0.19044-SP0
GPU: NVIDIA GeForce GTX 1050/PCIe/SSE2 2GB VRam NVIDIA Corporation 4.5.0 NVIDIA 512.15
CPU: Intel(R) Core(TM) i5-8400 CPU 6 cores @ 2.80GHz
RAM: (1/2) KINGSTON ValueRam KVR26N19S6 8 GB DDR4 2666MHz (not pre-installed, ordered+installed on Dec. 2021)
(2/2) 8GB DDR4 2666MHz ECC Unbuffered DIMM CL19 1Rx8 1.2V (looks pretty much like the one that's pre-installed, from 2018)

Drivers: latest Nvidia Geforce Experience installed, reinstalling them did not solve the problem
additional: latest Python version (3.10.4 from https://www.python.org/downloads) is installed

### blend file download

https://drive.google.com/file/d/1LeBFooEbfPI_iikWR3XbW2ab_MrfVO6Z/view?usp=sharing

### Video

https://user-images.githubusercontent.com/98273272/164896775-e661b855-b3fb-41de-98e7-1777766a7c84.mp4

**Comment by gluttonium** [comment]
Update: I tried to install version **1.2.0 ,1.1.0 and 1.0.0** but the same issue remains. It's still stuck at calculating the time and can't be quit properly. All versions cause the same problems as stated above.

**Comment by rlguy** [comment]
Hi, thanks for the detailed report and .blend file! 

I just had a chance to run some tests and I am getting an "Out of Memory" type error and this may be what is causing the issue.

It looks like the **floor** obstacle object may be causing the issue. It is okay for an obstacle to be larger than the domain, but if it is very large compared to the domain, this can cause out of memory issues or other performance issues (Related documentation: [Does my obstacle object need to be completely contained by the domain?](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Obstacle-Object-Settings#does-my-obstacle-object-need-to-be-completely-contained-by-the-domain)).

To fix this, I would suggest creating a smaller floor obstacle or removing this object from the simulation if it is not needed. After removing this object from the simulation set up, the simulation seems to run properly. Does this fix the issue for you as well?

**Comment by gluttonium** [comment]
I put the new boundary completely inside the domain and made it smaller/thinner. Now the only obstacles in the scene that stick out of the domain are the rocks.

The problem is finally solved, it takes like 10 to 15 seconds to calculate the remaining time and the simulation can be baked without any problems.

Thanks!

**Comment by rlguy** [comment]
Thanks for the update! Great to hear that the issue has been solved.
