### ISSUE TITLE
Compiling the addon does not produce the required dll(.a) files for the engine to work.

### ISSUE THREAD

**Issue by leonthelionanimations** [rlguy/Blender-FLIP-Fluids#583]
#### System Information

**Blender Version (including hash):** N/A
**FLIP Fluids Version:** 1.3.0
**Operating System:** Windows 11
**CPU:** Intel Core I5 8th gen mobile
**GFX:** Intel UHD 620
**RAM:** 8Gb 2666 Mhz Sodimm

#### Describe the bug
When compiling the addon from source, the following files fail to generate properly 
Software used : CMake. MinGW64 version 1.8.0(specifically the posix sjhj version). visual studios for Vcvars to convert gnu to microsoft libraries)
Provide a clear and concise description of what the actual bug/issue is that you are experiencing.

#### To Reproduce
Software used : CMake. MinGW64 version 1.8.0(specifically the posix sjhj version). visual studios for Vcvars to convert gnu to microsoft libraries)
Follow the instructions provided on the main code page, and place the Cmakelists.txt file into the root directory, in this case in the Main folder for flip fluids containing the src, cmake, and .github folders, then create a build folder just underneath through the use of commands (https://hdrmaps.com/blog/compiling-flip-fluids-add-on-on-windows/ (following these instructions) the end result should generate the critical dll's for the simulation engine library 
Provide descriptive instructions for how to reproduce the issue or how to use your .blend file.

#### Expected Behaviour
the fluid engine library dll's should generate along with the addon and pyfluid module when all the criteria for compiling the addon is met.

#### Actual Behaviour
they do not in fact appear to generate in the specified folder and searching through shows that both libpyflipfluidrelease(and debug).dll(.a) fail's while the rest of the addon does generate as expected, it fails to generate the expected dll's. 
A description of what actually happened.

**Comment by rlguy** [comment]
Hi, please note that this issue tracker is only meant for issues/bugs related to the Blender Market version of the FLIP Fluids addon. We are also unable to provide support for building and diagnosing issues related to building the addon on the wide variety of systems and system setups.

You may have encountered an error which prevented the build process from completing and generating the DLL files. Not all compilers may be supported such as posix sjhj version.
