### ISSUE TITLE
Fluid disappears at frame 650

### ISSUE THREAD

**Issue by AlphaZero666** [rlguy/Blender-FLIP-Fluids#584]
System Information

Blender Version (including hash):3.1.2
FLIP Fluids Version:1.3.0
**Operating System:Windows 11
**CPU:i5
**GFX:what is gfx? Graphics card? GTX 1060 6GB
**RAM: 32GB

#### Describe the bug

Provide a clear and concise description of what the actual bug/issue is that you are experiencing.
At frame 650 the fluid glitched and kinda went underground and i tried rebaking and still the same so i tried rebaking from frame 600 and now its from frame 600
#### To Reproduce

Provide descriptive instructions for how to reproduce the issue or how to use your .blend file.
Well since this happened on frame 650 and now 600 i have no idea i just want to fix it
#### Expected Behaviour

A description of what you expected to happen.
It is supposed to be a river and it should just flow down
#### Actual Behaviour

A description of what actually happened.
The water suddenly disappears and goes into the mesh, i will attach 

#### Screenshots

Im writing this on phone and i dont see any button so ill just send links to the image on blender discord server
https://media.discordapp.net/attachments/869803682231906314/980237195107512380/unknown.png
https://media.discordapp.net/attachments/869803682231906314/980237252376539247/unknown.png
You can also contact me on discord [D3ATH] ;)#7798

**Comment by rlguy** [comment]
Hi, thanks for the report! Please attach or link to a .blend file that reproduces the issue, which is required for bug reports ([See guidelines here](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Reporting-Bugs-and-Issues#attach-a-blend-file)).

For this issue, please also attach a .zip of the simulation log files which can be found in the ```cache_directory/logs``` folder. This will help us better understand how the simulation was running on your system.

If you are able to attach a render or a quick viewport animation to show how the liquid is disappearing into the mesh, we may be able to resolve this issue more quickly.

**Comment by AlphaZero666** [comment]
okay, here it is
the blend file: https://www.transfernow.net/dl/20220530vOn3FaDN

[logs.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/8799552/logs.zip) 
this log?

https://user-images.githubusercontent.com/106467397/171026783-be716d6b-8c12-4e56-9a6f-e189a93b5dee.mp4
it is really short because it takes really long to preview render

**Comment by AlphaZero666** [comment]
okay, thank you so much, one more question, if i somehow remove the geometry issues, do i have to rebake the whole simulation?

**Comment by rlguy** [comment]
I think you should be able to resume the simulation from a point before the failure (such as from 600 instead of the beginning). When resuming a simulation, the obstacle geometry will be updated and re-exported to the simulator by default ([More Info](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Simulation-Settings#settings-and-mesh-export)).

**Comment by AlphaZero666** [comment]
yes i managed to resume, but i got another question :D why cant i choose from which frame i want to resume but only from 50 100 150 etc or the latest one?

**Comment by rlguy** [comment]
The savestate interval can be set in the **FLIP Fluid Simulation > More Bake Settings** section: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Simulation-Settings#savestates

The interval value must be set before baking. Increased frequency of savestates will increase cache size.

**Comment by AlphaZero666** [comment]
so i might have another question, do you have any idea how to sudden appearance of the whitewater might have happened?
https://www.transfernow.net/dl/20220530LGms34rz
