### ISSUE TITLE
Preset panel not showing up

### ISSUE THREAD

**Issue by miruedits** [rlguy/Blender-FLIP-Fluids#587]
#### System Information

**Blender Version:** 3.2.0, master, 2022-06-08 10:22, e05e1e369187
**Addon Version:** A FLIP Fluid Simulation Tool for Blender (v1.4.0 Stable 07-JUN-2022)
**OS:** Windows-10-10.0.19043-SP0
**GPU:** NVIDIA GeForce GTX 1650/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 511.79
**CPU:** Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
**RAM:** Unknown (fill in)

#### Describe the bug

My preset panel isn't there even though I can see the folder that says "presets" in the zip file, its clearly there and its just not working when I installed the zip in blender.

#### To Reproduce

I dont really know if it can be reproduce but what I did was open blender after buying the addon then I went to preferences and installed "FLIP_Fluids_addon_1.4.0_stable_07_jun_2022.zip" then saved preferences and closed blender then reopened it. I'm trying to use the ocean preset for my scene but found that my whole preset panel was not there after modifying everything else.

#### Expected Behaviour

I expected that when I installed the addon for blender that the preset panel would show up.

#### Actual Behaviour

When I try looking for the panel its not there but everything seems to be working, the materials, and all the other panels

#### Screenshots

![image](https://user-images.githubusercontent.com/108705030/177233518-6494ef31-d581-4e27-8b73-4864a68baa87.png)

![image](https://user-images.githubusercontent.com/108705030/177233590-a7646272-bf22-45a9-9102-d864e420d528.png)

![image](https://user-images.githubusercontent.com/108705030/177233632-4a4e7050-abca-491b-803b-814e18be1bfc.png)

![image](https://user-images.githubusercontent.com/108705030/177233664-1983d88f-42fe-4104-8bca-c00cfcc6af5c.png)

**Comment by rlguy** [comment]
Hi, thanks for the report! However, the presets system and feature had been removed as a supported feature from the addon in November 2020. More information on the reasons in this topic, but the main issue was that the preset system was not able to be supported in newer versions of Blender 2.81 or later: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Preset-Settings

The new work-in-progress preset system is not integrated into the addon, but is currently a .zip file containing .blend files of common setups. This file can be found in the addon downloads as the Preset_Scenes.zip file: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/FLIP-Fluids-Downloads
