### ISSUE TITLE
Record vector field

### ISSUE THREAD

**Issue by bkfichter** [rlguy/Blender-FLIP-Fluids#591]
Thinking out loud and I haven't fully thought this through. I'm wondering if there is a way to get a vector field snapshot for each (or some multiple) voxel per frame. Store along side the bake file. Maybe that can be used in geo nodes to apply a force to meshes to simulate buoyancy. When physics are added to geo nodes, all of this could work together. In the meantime, a file that contains the array for the vector field (per frame) could be fun to use in python to works towards something. Thoughts?

**Comment by rlguy** [comment]
Hi, at the moment there is not a way for addons to import vector field data into Blender. The FLIP Fluids addon does not export this data as there is not a use for it yet.

We will need to wait and see how physics and nodes develop in Blender and if addons will have access to this system.

Please note that this issue tracker is only meant for bugs and issues related to the FLIP Fluids addon. See our support guidelines for where to field questions and feature requests here: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines

**Comment by bkfichter** [comment]
Sorry I thought I was posting under feature request. Plus that's why I was suggesting exporting a vector field file next to bake file. Then that data could be used.
