### ISSUE TITLE
Baking crashes blender

### ISSUE THREAD

**Issue by roelten** [rlguy/Blender-FLIP-Fluids#597]
#### System Information

**Blender Version (including hash): k-cycles 3.3.0 db724322d7d1 & blender v2.83.19**
**FLIP Fluids Version: 1.5.0**
**Operating System: windows 10**
**CPU: ryzen 9 3900xt**
**GFX: nvidia 3090**
**RAM: 32gb**

#### Describe the bug
Every time i try and bake a simulation it crashes after a few seconds. ive tried diffrent blender versions and diffrent test files aswell as the included examples, it also doesnt leave a crashlog in the temp folder. i also tried a clean install of blender with only the flip addon enabled, aswell as using diffrent dictories

#### To Reproduce

i think the issues lies in my setup, rather than a scene/ or file. 

#### Expected Behaviour

a cube of fluid falling in a domain

#### Actual Behaviour

it crashes a few seconds after pressing bake

**Comment by roelten** [comment]
problem -> me

**Comment by zoltan025** [comment]
I'm having the same problem. How could you solve it?

**Comment by rlguy** [comment]
Hi zoltan025,

If you are experiencing this issue, this may be caused by a recent NVIDIA RTX series driver update. Refer to issue #599 for more information and a solution.

**Comment by roelten** [comment]
my problem solved after a fresh install of blender/ the addon

> I'm having the same problem. How could you solve it?

**Comment by zoltan025** [comment]
Okay. understood.. Thanks for the help! :)

**Comment by zoltan025** [comment]
It actually worked. Nice! Thanks a lot!!!
