### ISSUE TITLE
[Solution] Frequent Baking Crashes related to NVIDIA GeForce RTX drivers

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids#599]
This issue thread was created to update you with a solution to a recent issue that has been causing frequent Blender crashes when running simulations with the FLIP Fluids Addon. This issue is relevant to artists that run systems containing NVIDIA GeForce RTX series video cards. In this post we will detail the issue and the current solution to this problem.

The fix for this issue is to update your NVIDIA GeForce RTX drivers to the "Studio Driver" version: https://www.nvidia.com/en-us/geforce/drivers/

## Issue Symptoms and Patterns

- Frequent baking crashes closing Blender, typically within a few frames of beginning or resuming a simulation.
- Issue began appearing in October 2022 or early November 2022.
- System containing a NVIDIA GeForce RTX series video card.
- Issue occurs on all versions of Blender and the FLIP Fluids addon.
- Issue occurs in all Blend files: older files, newly created files, example files.

## Issue Summary

Beginning in early November, we were made aware of an issue where baking a simulation using the FLIP Fluids addon was resulting in frequent Blender crashes. Over the past few days we had received a large number of reports of this issue. While troubleshooting the problem and gathering feedback, it was found that this issue was not related to updating to a newer version of the addon or Blender, but was being caused by a change external to Blender. This change suddenly began causing crashes across all version of Blender and the FLIP Fluids addon.

After troubleshooting, it has been found that this issue was being caused by a recent NVIDIA GeForce RTX driver update. Specifically, the "Game Ready Driver" version was determined to be the cause of the issue. This issue was causing an interaction between the addon and the Blender UI/Viewport that would trigger a crash - typically within a few frames after beginning a simulation.

## Issue Solution

The current solution to this issue is to update your NVIDIA GeForce RTX drivers to the "Studio Driver" version which is typically more stable for content creation software. You will be able to download the latest NVIDIA drivers and specify the "Studio Driver" download type in the manual driver search here: https://www.nvidia.com/en-us/geforce/drivers/

![studio_driver](https://user-images.githubusercontent.com/4285191/201758027-fcce1f7d-006c-4802-8afb-7fdf63e62c29.jpg)

### How can I check which driver version I have installed?

Refer to [NVIDIA Customer Help: Is there any way to determine whether the installed driver is a NVIDIA Studio Driver or Game Ready Driver?](https://nvidia.custhelp.com/app/answers/detail/a_id/4848/~/is-there-any-way-to-determine-whether-the-installed-driver-is-a-nvidia-studio)

## Issue Workaround

If you are unable to update to the NVIDIA Studio Drivers, a workaround is to bake the simulation from the command line. The FLIP Fluids addon contains a tool to automatically launch a command line baking process in the FLIP Fluids sidebar menu ([See Documentation](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Helper-Menu-Settings#command-line-tools)).

---

If you are affected by this issue and this solution does not fix the problem, or if you have any questions at all, please reach out to us here or by sending us an email at support@flipfluids.com.

This issue thread my be used to discuss the issue or to report more information/findings about the issue. We will be leaving this issue open for some time to increase visibility of this issue.

We apologize for the inconvenience that this issue has caused. Thank you for your patience and for supporting our FLIP Fluids addon.

\- The FLIP Fluids Addon Development Team

**Comment by dannyflax** [comment]
> This issue was causing an interaction between the addon and the Blender UI/Viewport that would trigger a crash - typically within a few frames after beginning a simulation.

Super curious how you debugged this, do you have a sample crash log that you wouldn’t mind sharing?

**Comment by rlguy** [comment]
Hi, we were not able to obtain any crash logs. This issue was debugged through user feedback and it seemed that Blender would not generate a crash report.

We're not sure of the exact cause of the issue, but It was assumed that the crashes were related to an interaction between graphics drivers, the addon, and the viewport based on troubleshooting results:
- The issue would only occur on the latest Game Ready Driver version at the time and would not happen on earlier driver versions.
- The issue would only occur when the viewport was being updated (the addon may trigger frequent viewport updates during simulation). The crashes would be triggered earlier if the addon triggered viewport updates more frequently. The issue would not occur if the Blend file did not have a 3D viewport window/panel open.

**Comment by dannyflax** [comment]
Got it, thanks for the info!

**Comment by rlguy** [comment]
Closing this issue now as this is no longer a problem. Not too long after this issue thread was created, NVIDIA released a new Game Ready Driver version where this issue was fixed.

At this point I think it's safe to assume that users and artists have updated their drivers by now and that we can remove the warnings in the UI for the next version of the FLIP Fluids addon.
