### ISSUE TITLE
Blender Crash when I run the simulation.

### ISSUE THREAD

**Issue by Oscar12pr** [rlguy/Blender-FLIP-Fluids#601]
Hi there,

I just bought the Flip Fluid add-on and when I try to do any simulation with default settings it crashes. It doesn't matter if it is a  complex simulation or a very simple one. How do I fix it?

**Comment by rlguy** [comment]
Hi, could this be related to this recent NVIDIA Driver issue: #599?

Let me know if this fixes the issue or if the issue still persists.

**Comment by Oscar12pr** [comment]
It worked. Thank you very much.

**Comment by rlguy** [comment]
Thanks for the update, that's good to hear.
