### ISSUE TITLE
issue with baking 

### ISSUE THREAD

**Issue by Jeff1254221542** [rlguy/Blender-FLIP-Fluids#603]
When i try to bake this happen  ![Untitled](https://user-images.githubusercontent.com/108340552/209563447-7c91c5fc-003c-468b-9a6f-bdcc25680cd4.jpg) , how do i fix that issue?

**Comment by rlguy** [comment]
Hi Jeff1254221542, thanks for the report!

Does restarting Blender and trying again solve the issue?

What version of the FLIP Fluids addon do you have installed? This error can be triggered if using an incompatible version of the addon. FLIP Fluids 1.5.0 or later is required for compatibility with Blender 3.3.

Let me know if you have any questions of if you find any more information about the issue.

**Comment by Jeff1254221542** [comment]
No, doesn't solve the issue

I'm using the Flip Fluids v1.0.9b version

**Comment by rlguy** [comment]
Hi, FLIP Fluids 1.0.9b is only compatible with up to Blender 2.92. You will need to update to at least FLIP Fluids 1.5.0 for Blender 3.3 to avoid this type of error.

[Installation Instructions: Updating the FLIP Fluids addon](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Addon-Installation-and-Uninstallation#updating-the-flip-fluids-addon)

**Comment by Jeff1254221542** [comment]
Alright thanks for helping me out!
