### ISSUE TITLE
Cannot find fluid engine libraries...

### ISSUE THREAD

**Issue by Tomeccx** [rlguy/Blender-FLIP-Fluids#610]
#### System Information

**Blender Version (including hash):** 3.14
**FLIP Fluids Version:** Latest Github
**Operating System:** Ubuntu x64
**CPU:** Ryzen 5 5600x
**GFX:** Nvidia GTX 1060
**RAM:** 16 gigs of 3200mhz

Provide a clear and concise description of what the actual bug/issue is that you are experiencing.
    Hello! So I recently I switched over to ubuntu, and decided to download blender. I'm using what I believe to be the latest github version for flip fluids, I used the same .zip for windows and I have been making stuff for the past 2 weeks. However, when I switch over and install the .zip onto blender for ubuntu. I'm getting the following error when pressing the bake button.
   'Cannot find fluid engine libraries: <libblpyfluiddebug.so> <libblpyfluidrelease.so> '. See system console for error info.

A description of what you expected to happen. Liquid be baked

A description of what actually happened. Liquid not get baked, I get an error.
 'Cannot find fluid engine libraries: <libblpyfluiddebug.so> <libblpyfluidrelease.so> '. See system console for error info.

**Comment by D3vArt** [comment]
Same exact issue
