### ISSUE TITLE
Nothing is baking

### ISSUE THREAD

**Issue by BAP00tato** [rlguy/Blender-FLIP-Fluids#613]
I'm new using this (I use the demo version), but when I bake there's no fluid animation at all. I have a domain and a Inflow. What am I doing wrong? I've search for answers but can't find anything, I tried everything in Scene Troubleshooting and it's still not working.

I apologise if this is a waste of time

**Comment by clankill3r** [comment]
Can it be that you are following this?
https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Creating-Your-First-FLIP-Fluids-Simulation

Cause that documentation is **_missing a really important step_**.
The result is in a collection that is hidden by default...

![Screenshot 2023-04-18 205724](https://user-images.githubusercontent.com/738650/232878001-5f9514fd-c22a-438e-9144-513e13bdebae.png)

**Comment by rlguy** [comment]
Hi, which step in the documentation is this related to? I took a quick glance, but was not able to notice which area was affecting collection visibility. The FLIPFluids and FLIPMeshes collections should be generated to be visible by default.

**Comment by BAP00tato** [comment]
I uploaded my blend file

https://www.mediafire.com/file/ge8qhror64msd0u/tents+slimy.blend/file

**Comment by rlguy** [comment]
Thanks for the Blend file, I just had a chance to take a look at the set up. Just two small modifications are needed:

Enabled **[Export Animated Mesh](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Inflow-Object-Settings#mesh-data-export)** on the Inflow object. This is required for animation that is more complex than just keyframed location/rotation/scale such as armatures.

![export_animated_mesh](https://user-images.githubusercontent.com/4285191/232958170-9f845000-0deb-4ad9-a6d0-c289245b37dc.jpg)

The Inflow object geometry is also non-manifold which will cause problems with emitting liquid. To fix this, an endcap needs to be filled in on the inflow object to close the mesh. For more information on non-manifold geometry and how to detect/debug geometry issues, see this topic: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Manifold-Meshes

![add_endcap](https://user-images.githubusercontent.com/4285191/232958188-faeb627d-afcd-4316-ad36-0c08fbd75c25.jpg)

After making these changes, the object will emit liquid:

![image](https://user-images.githubusercontent.com/4285191/232958593-30613106-04b5-4da0-8221-ccb002070609.png)

Attached is a Zip archive of the revised Blend file.
[tents_slimy-revised.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/11268167/tents_slimy-revised.zip)

Hope this info helps!

**Comment by BAP00tato** [comment]
This worked, thanks alot. But I got another problem.

If I hit render the domain cube is visible.

**Comment by rlguy** [comment]
Great, glad to help. The visibility of objects in the viewport/render can be set with these icons in the outliner:

![image](https://user-images.githubusercontent.com/4285191/232979525-97ca7d75-ff33-4a24-a8e7-de11e0fb6e75.png)
