### ISSUE TITLE
Error Baking Fluid Simulation: `Cannot find fluid engine libraries: <libblpyfluiddebug.dll> <libblpyfluidrelease.dll>` after building from source

### ISSUE THREAD

**Issue by rgri** [rlguy/Blender-FLIP-Fluids#623]
#### System and Blend File Information

**Blender Version:** 3.6.1, blender-v3.6-release, 2023-07-17 12:50, 8bda729ef4dc
**Addon Version:** A FLIP Fluid Simulation Tool for Blender (v1.7.1 GitHub Release 25-JUL-2023)
**OS:** Windows-10-10.0.22621-SP0
**GPU:** AMD Radeon RX 6950 XT ATI Technologies Inc. 4.5.0 Core Profile Context 23.7.2.230718
**CPU:** AMD Ryzen 7 3700X 8-Core Processor             
**CPU Threads:** 16
**RAM:** Unknown 32 GB

**Blender Binary:** C:\Program Files\Blender Foundation\Blender 3.6\blender.exe
**Addon Path:** C:\Users\rjgri\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\flip_fluids_addon
**Renderer:** BLENDER_EEVEE
**Cycles Device:** N/A
**Viewport Modes:** SOLID
**Objects:** 5
**FLIP Objects:** 2
**FLIP Domains:** Cube.001 <scene: Scene>
**Obstacle Objects:** 0
**Fluid Objects:** 1 <Export Animated: 0> <Skip Re-export: 0>
**Inflow Objects:** 0
**Outflow Objects:** 0
**Force Objects:** 0
**Cache Path:** C:\Users\rjgri\scratch\org\.attach\1f\52cdc6-2784-4c24-ad27-d32504b2b3c8\fliptest_flip_fluid_cache
**Cache Exists:** True
**Cache Logs:** 0
**Simulation Visibility:** <Viewport: Enabled> <Render: Enabled>
**Surface Visibility:** <Viewport: DISPLAY_FINAL> <Render: DISPLAY_FINAL>
**Whitewater Visibility:** N/A
**Enabled Features:** Default
**Enabled Attributes:** N/A
**Lock Interface:** Enabled
**Cycles Persistent Data:** Disabled
**Developer Tools:** Disabled
**Mixbox Plugin:** Not Installed
**Enabled Addons:** FLIP Fluids 1.7.1

#### Describe the bug

Clicking "Bake" in any FLIP fluid domain yields the error `Cannot find fluid engine libraries:`, missing the .dlls:
- <libblpyfluiddebug.dll>
- <libblpyfluidrelease.dll>
#### To Reproduce

Provide descriptive instructions for how to reproduce the issue or how to use your .blend file.

FLIP Fluids cloned from master ([rev](e95317dc04513eeb4ac0a58a8ece32a45e62060c)) and built with Python 3.9.12, `make 4.2.1, cmake 3.16.3`. 
[Toy blend file.](https://drive.google.com/file/d/1qQBo7AZyPi2ZvkkN6TZH089-dSeSvkG7/view?usp=sharing)
Just click "Bake" in the FLIP Fluid Simulation physics properties on Cube.001.
#### Expected Behaviour

There is no error, the simulation bakes.

#### Actual Behaviour

A description of what actually happened.
 `Cannot find fluid engine libraries: <libblpyfluiddebug.dll> <libblpyfluidrelease.dll>. See system console for error info.`
#### Screenshots

N/A

**Comment by rlguy** [comment]
Hi, it looks like the addon has not been completely compiled. The fluid engine libraries are generated after compiling the program.

Please note that this issue tracker is only meant for issues/bugs related to the [marketplace version of the FLIP Fluids addon](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Official-Marketplaces-of-the-FLIP-Fluids-Addon). We are also unable to provide support for building and diagnosing issues related to building the addon on the wide range of systems, system setups, and builder experience.

Build/compile instructions can be found here: https://github.com/rlguy/Blender-FLIP-Fluids#building

If you are looking for a more detailed process building the addon on Windows, this is a good post by HDRMaps: https://hdrmaps.com/compiling-flip-fluids-add-on-on-windows/

**Comment by BlackPaw21** [comment]
been trying to fix the same issue for the past 40 minutes.... any updates or do i need to sell a kidney for the market version?

**Comment by rgri** [comment]
Hi @BlackPaw21, feel free to add me on Discord at shortcut5449 and I can help you get it running.

As Ryan mentioned, this is not actually an issue- it is just caused by trying to build the addon _for_ Windows, _from_ Linux.

**Comment by BlackPaw21** [comment]
> Hi @BlackPaw21, feel free to add me on Discord at shortcut5449 and I can help you get it running.
> 
> As Ryan mentioned, this is not actually an issue- it is just caused by trying to build the addon _for_ Windows, _from_ Linux.

thanks, but i just got it to work this second! after a lot of testing i figured out the version need to be changed :)
