### ISSUE TITLE
Documentation Error: Creating Your First FLIP Fluids Simulation

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#632]
I found a small typo on this page:
https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Creating-Your-First-FLIP-Fluids-Simulation
```
In the Type dropdown list, select _Domain__. This will activate the object as a domain object.
```
There are extra underlines: `_Domain__`

**Comment by rlguy** [comment]
Thanks for letting us know! The formatting has been fixed.
