### ISSUE TITLE
Error when finishing installation and baking

### ISSUE THREAD

**Issue by chair-man-f** [rlguy/Blender-FLIP-Fluids#633]
#### System Information

**Blender Version (including hash):**
**FLIP Fluids Version:** 1.7.4
**Operating System:** macos
**CPU:** Apple M1 pro
**GFX:** Apple M1 pro
**RAM:** 16 GB

#### Describe the bug

Error when finishing installation and error when pressing bake

#### To Reproduce

Compile the addon, set up scene, press bake

#### Expected Behaviour

The fluids to bake 

#### Actual Behaviour

Error "unable to load fluid engine libraries"

#### Screenshots

looks like some files were missing when compared to demo

I compiled this with 4 terminal commands

brew install cmake

brew install make

cd /Users/jackief/Downloads/Blender-FLIP-Fluids-master

python3 build.py

Cmake and gnu make are both present

<img width="434" alt="Screenshot 2024-02-12 at 16 28 41" src="https://github.com/rlguy/Blender-FLIP-Fluids/assets/117324349/83e35616-ba31-43d3-858c-9f2d556f754d">
<img width="731" alt="Screenshot 2024-02-12 at 16 29 07" src="https://github.com/rlguy/Blender-FLIP-Fluids/assets/117324349/d6c737ec-4070-4832-a68d-4e0698c73a6f">

**Comment by rlguy** [comment]
Hi, please note that this issue tracker is only meant for issues/bugs related to the marketplace version of the FLIP Fluids addon. We are also unable to provide support for building and diagnosing issues related to building the addon on the wide variety of systems and system setups.

Make sure that you are running the correct version of Blender that the addon has been compiled for (Intel or Apple Silicon version).

**Comment by chair-man-f** [comment]
Ok sorry, but am I able to specify whether I want arm64 or not? And here is what happens when I press finish installation

Could you at least point me in the right direction? thanks
<img width="947" alt="Screenshot 2024-02-13 at 09 28 31" src="https://github.com/rlguy/Blender-FLIP-Fluids/assets/117324349/a9274e2c-d305-48e9-8d7b-d23178a8b73d">

**Comment by rlguy** [comment]
Hey, check out the ```python build.py --help``` menu:

```
usage: build.py [-h] [-build-directory BUILD_DIRECTORY] [-darwin-arch DARWIN_ARCH] [-library-suffix LIBRARY_SUFFIX] [-cmake-path CMAKE_PATH] [-make-path MAKE_PATH] [--clean] [-no-compile]

FLIP Fluids Addon build and compile script

options:
  -h, --help            show this help message and exit
  -build-directory BUILD_DIRECTORY
                        Path to destination build directory
  -darwin-arch DARWIN_ARCH
                        Target architecture to set for CMAKE_OSX_ARCHITECTURES
  -library-suffix LIBRARY_SUFFIX
                        Specify suffix to add to the generated library name
  -cmake-path CMAKE_PATH
                        Specify path to CMake binary (www.cmake.org)
  -make-path MAKE_PATH  Specify path to GNU Make binary (www.gnu.org/software/make)
  --clean               Clear generated files in the build directory before building
  -no-compile           Do not compile libraries
```

The ```[-darwin-arch DARWIN_ARCH]``` option flag can be used to override the target [CMAKE_OSX_ARCHITECTURES](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html) cmake variable.

So the architecture can be specified like this:

```
# For the Apple Silicon version of Blender
python build.py -darwin-arch arm64

# For the Intel version of Blender:
python build.py -darwin-arch x86_64

# Or for both the Intel and Apple Silicon version of Blender:
python build.py -darwin-arch arm64;x86_64
```

Note: the compiler will need to support these options.

I am sorry to say that we are unable to provide further support for building/compiling the FLIP Fluids addon.

**Comment by chair-man-f** [comment]
Wow thanks, I'm so sorry that I'm not able to support your work


thanks for your help
