### ISSUE TITLE
Flip Fluids doesn't support mesh with animations (rigged)

### ISSUE THREAD

**Issue by salmazov** [rlguy/Blender-FLIP-Fluids#635]
#### System Information

**Blender Version (including hash):**
Blender 4.0 release / windows

**FLIP Fluids Version:**
1.7.5 / compiled from source

**Operating System:**
macOS

**CPU:**
mbp 16 m1 max
**RAM:**
32gb

#### Describe the bug
Flip Fluids 1.7.5 with Mesh (rigged) doesn't interact while animation.
Flip Fluids takes into consideration 1st frame, but not 2nd, 3rd... e.t.c. from the animation

#### To Reproduce
Create domain / box
Create box fluid at the bottom of domain
Create simple mesh / ctrl+r 3 divisions
Add it to the domain area / inside it
Add simple rig
Add 3-4 bones
Attach to our box mesh / automatic weights
Make a basic animation - 60-90 frames using pose
Bake Flip Fluids

#### Expected Behaviour
After baking mesh interacts with water surface while animation

#### Actual Behaviour
After baking mesh doesn't interact with water surface while animation, only 1st frame affects water surface, animation doesn't affect it

A description of what actually happened.

**Comment by salmazov** [comment]
Found settings

**Comment by rlguy** [comment]
Great to see that you have solved the issue. 

For any others that come across this issue, the solution is to enable the **FLIP Object > Export Animation Mesh** option:

![image](https://github.com/rlguy/Blender-FLIP-Fluids/assets/4285191/01ef7df4-5f0a-4b43-9e06-559ed642f537)

This option is required for any animation that is more complex than keyframed location, rotation, or scale.
