### ISSUE TITLE
Alembic export fails due to '&' character in filepath

### ISSUE THREAD

**Issue by GuyJan** [rlguy/Blender-FLIP-Fluids#640]
#### System and Blend File Information

**Blender Version:** 4.1.1, blender-v4.1-release, 2024-04-15 15:11, e1743a0317bc
**Addon Version:** A FLIP Fluid Simulation Tool for Blender (v1.8.1 Release 16-JUL-2024)
**OS:** Windows-10-10.0.22631-SP0
**GPU:** NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 NVIDIA Corporation 4.6.0 NVIDIA 556.12
**CPU:** Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz
**CPU Threads:** 16
**RAM:** Unknown (fill in)

**Blender Binary:** C:\Program Files\Blender Foundation\Blender 4.1\blender.exe
**Addon Path:** C:\Users\Guyml\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\flip_fluids_addon
**Renderer:** CYCLES
**Cycles Device:** GPU
**Viewport Modes:** SOLID
**Objects:** 38
**FLIP Objects:** 11
**FLIP Domains:** DomainCube <scene: Scene>
**Obstacle Objects:** 7 <Export Animated: 2> <Skip Re-export: 0>
**Fluid Objects:** 1 <Export Animated: 0> <Skip Re-export: 0>
**Inflow Objects:** 1 <Export Animated: 0> <Skip Re-export: 0>
**Outflow Objects:** 1 <Export Animated: 0> <Skip Re-export: 0>
**Force Objects:** 0
**Cache Path:** H:\Stoommachine\Corliss\3D_Model\Condenser

launchin Alembic export fails, with following massage in the system console:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 496, in disable
    mod.unregister()
  File "C:\Users\Guyml\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\flip_fluids_addon\__init__.py", line 234, in unregister
    bpy.app.handlers.depsgraph_update_post.remove(scene_update_post)
ValueError: list.remove(x): x not in list
P2076:10:41:21:megaddon:ERROR: Asked to unregister addon 'materialiq5_full' but addon with this module name was not found!

Blender quit
```

please help

Guy

**Comment by GuyJan** [comment]
disabling polygoniq in preferences does not help.

herewith the full message:

Blender 4.1.1 (hash e1743a0317bc built 2024-04-15 23:33:30)
Read prefs: "C:\Users\Guyml\AppData\Roaming\Blender Foundation\Blender\4.1\config\userpref.blend"
Info: Registering operator class: 'OBJECT_OT_AlignOperator', bl_idname 'object.align' has been registered before, unregistering previous
register_class(...):
Info: Registering operator class: 'OBJECT_OT_AlignOperator', bl_idname 'object.align' has been registered before, unregistering previous
Reloading external rigs...
Reloading external metarigs...
DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:PyProj unavailable
DEBUG:BlenderGIS-master.core.checkdeps:Pillow unavailable
DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available
Error: Cannot read file "H:\Stoommachine\Corliss\3D_Model\Condenser": No such file or directory
Exception in module unregister(): 'C:\\Users\\Guyml\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\addons\\extreme_pbr\\__init__.py'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 496, in disable
    mod.unregister()
  File "C:\Users\Guyml\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\extreme_pbr\__init__.py", line 120, in unregister
    unregister_handlers()
  File "C:\Users\Guyml\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\extreme_pbr\handlers\persistent_handlers.py", line 195, in unregister_handlers
    bpy.app.handlers.depsgraph_update_post.remove(update_material_utility)
ValueError: list.remove(x): x not in list
Exception in module unregister(): 'C:\\Users\\Guyml\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\addons\\flip_fluids_addon\\__init__.py'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 496, in disable
    mod.unregister()
  File "C:\Users\Guyml\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\flip_fluids_addon\__init__.py", line 234, in unregister
    bpy.app.handlers.depsgraph_update_post.remove(scene_update_post)
ValueError: list.remove(x): x not in list

Blender quit

C:\Program Files\Blender Foundation\Blender 4.1>

**Comment by rlguy** [comment]
Thanks for the report!

It looks like there are error messages from other addons (Blender GIS, Extreme PBR), but I am not sure if they are related to the Alembic launch failure.

Would you be able to test the issue within a factory clean Blender environment? This test involves temporarily renaming your Blender userdata folder:

`C:\Users\Guyml\AppData\Roaming\Blender Foundation\Blender\4.1`

Instructions can be found here: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Addon-Installation-Troubleshooting#create-a-clean-installation-of-blender

Does the Alembic launch still fail in a factory environment? If so, what is the full message that is displayed?

**Comment by GuyJan** [comment]
Hi Guy,

I followed your instructions and create a clean version of blender 4.1,  and opened the file:

"H:\Stoommachine\Corliss\3D_Model\Condenser&AirPump\AirPumpV2.blend", which was already baked, and launched Alembixc export.

I received following error message:

Blender 4.1.1 (hash e1743a0317bc built 2024-04-15 23:33:30)

Error: Cannot read file "H:\Stoommachine\Corliss\3D_Model\Condenser": No such file or directory

 

Blender quit

So I re-created the “condenser” directory, and launched Alembic export, an received following message:

Blender 4.1.1 (hash e1743a0317bc built 2024-04-15 23:33:30)

Error: Cannot read file "H:\Stoommachine\Corliss\3D_Model\Condenser": Permission denied

 

Blender quit

 

C:\Program Files\Blender Foundation\Blender 4.1>

 

Then I saved the file in the “condenser” directory, and the path became now:

"H:\Stoommachine\Corliss\3D_Model\Condenser\AirPumpV2.blend"

I adapted the cache directory to use the already baked cache:



 

The bake still worked correctly (FLIPMeshes/whitewater_bubble selected):



 

After relaunching Alembic export, I received following error message:

Blender 4.1.1 (hash e1743a0317bc built 2024-04-15 23:33:30)

Read blend: "H:\Stoommachine\Corliss\3D_Model\Condenser\AirPumpV2.blend"

Traceback (most recent call last):

  File "C:\Users\Guyml\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\flip_fluids_addon\resources\command_line_scripts\alembic_export.py", line 416, in <module>

    dprops = bpy.context.scene.flip_fluid.get_domain_properties()

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'Scene' object has no attribute 'flip_fluid'

 

Blender quit

 

C:\Program Files\Blender Foundation\Blender 4.1>

 

So I suspect the bug is nevertheless within the FlipFluids addon.

Why, as mentioned in the first error message, the path still points to a “Condenser” directory while its name was since long changed into “Condenser&AirPump” ??

 

Best regards,

Guy

**Comment by GuyJan** [comment]
Hi Guy,

I changed the name of the directory “Condenser&Airpump” into “Condenser_Airpump” and now the button “Launch Alembic Export” worked, and produced an xxx.abc file that perfectly could be imported into an other .blend file, although the materials were missing – bt that problem can be easily solved.

 

So the “&” character, although accepted by blender, is indigestible for FlipFluid or Alembic.

 

My problem is solved, even within my original blender-presets environment with all addons enabled.

 

However, for your info, herewith the error messages at the end of the run:

 

WARN (io.alembic): C:\Users\blender\git\blender-v410\blender.git\source\blender\io\alembic\exporter\abc_writer_abstract.cc:105 update_bounding_box: Bounding box is null!

Alembic export of 'H:\Stoommachine\Corliss\3D_Model\Condenser_AirPump\Alembic\AirPump_V2.abc' took 391.6 s (0H:6m:31s)

Exception in module unregister(): 'C:\\Users\\Guyml\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\addons\\extreme_pbr\\__init__.py'

Traceback (most recent call last):

  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 496, in disable

    mod.unregister()

  File "C:\Users\Guyml\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\extreme_pbr\__init__.py", line 120, in unregister

    unregister_handlers()

  File "C:\Users\Guyml\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\extreme_pbr\handlers\persistent_handlers.py", line 195, in unregister_handlers

    bpy.app.handlers.depsgraph_update_post.remove(update_material_utility)

ValueError: list.remove(x): x not in list

Exception in module unregister(): 'C:\\Users\\Guyml\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\addons\\flip_fluids_addon\\__init__.py'

Traceback (most recent call last):

  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 496, in disable

    mod.unregister()

  File "C:\Users\Guyml\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\flip_fluids_addon\__init__.py", line 234, in unregister

    bpy.app.handlers.depsgraph_update_post.remove(scene_update_post)

ValueError: list.remove(x): x not in list

P24956:08:43:57:megaddon:ERROR: Asked to unregister addon 'materialiq5_full' but addon with this module name was not found!

 

Blender quit

 

C:\Program Files\Blender Foundation\Blender 4.1>

 

Best regards,

 

Guy

**Comment by rlguy** [comment]
Thanks for all of the troubleshooting! My apologies for the delayed response, I was away on holidays and am now back to development on a regular schedule.

I think we should be able to fix and avoid this issue. We have had a few similar bugs in the past related to special characters in filepaths.

**Comment by GuyJan** [comment]
Thanks you for your response.

I have however still a question: after importing the Alembic file, made by FlipFluids, into the final .blend file, the whitewater bubbles, foam etc. appeared to be only vertices, no mesh, so I still had to transform these into icospheres and apply the corresponding shaders. Is this normal?

Br,

Guy

**Comment by rlguy** [comment]
Hi, that is normal and it is optimal for the Alembic whitewater to be mesh vertex data. The FLIP Fluids addon automatically sets up the whitewater vertices for rendering, but you will need to do this manually when it is an Alembic mesh. More info: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Alembic-Export-Support#rendering-alembic-whitewater

**Comment by rlguy** [comment]
A workaround to this issue has been added for the next FLIP Fluids version 1.8.2 (release date TBA).

The workaround will be applied only in the case that a Windows filepath contains an ampersand (&) in the filepath. At the moment, there are not any other known special characters that may cause this type of issue.
