### ISSUE TITLE
bl_info error so can't export/import  alembic

### ISSUE THREAD

**Issue by lucianopetrigh** [rlguy/Blender-FLIP-Fluids#641]
#### System and Blend File Information

**Blender Version:** 4.2.2 LTS, blender-v4.2-release, 2024-09-23 12:18, c03d7d98a413
**Addon Version:** A FLIP Fluid Simulation Tool for Blender (v1.8.1 GitHub Release 16-JUL-2024)
**OS:** Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
**GPU:** Mesa Intel(R) HD Graphics 520 (SKL GT2) Intel 4.6 (Core Profile) Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
**CPU:** Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
**CPU Threads:** 4
**RAM:** Unknown (fill in)

#### Describe the bug

Blender Version: 4.2.2 LTS, blender-v4.2-release, 2024-09-23 12:18, c03d7d98a413
Addon Version: A FLIP Fluid Simulation Tool for Blender (v1.8.1 GitHub Release 16-JUL-2024)
OS: Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
GPU: Mesa Intel(R) HD Graphics 520 (SKL GT2) Intel 4.6 (Core Profile) Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
CPU Threads: 4
RAM: Unknown (fill in)

Blender Binary: /home/luciano/Downloads/Programs/blender-4.2.2 aces/blender
Addon Path: /home/luciano/.config/blender/4.2/extensions/user_default/flip_fluids_addon
Renderer: CYCLES
Cycles Device: GPU
Viewport Modes: SOLID
Objects: 28
FLIP Objects: 4
FLIP Domains: domain <scene: Scene>
Obstacle Objects: 0
Fluid Objects: 0
Inflow Objects: 1 <Export Animated: 0> <Skip Re-export: 0>
Outflow Objects: 1 <Export Animated: 0> <Skip Re-export: 0>
Force Field Objects: 1 <Export Animated: 0> <Skip Re-export: 0>
Cache Path: /home/luciano/Pictures/creative district/dyva/dyva blends/dyva-cranberry_flip_fluid_cache
Cache Exists: True
Cache Logs: 16
Simulation Visibility: <Viewport: Enabled> <Render: Enabled>
Surface Visibility: <Viewport: DISPLAY_FINAL> <Render: DISPLAY_FINAL>
Whitewater Visibility: <Viewport: DISPLAY_FINAL> <Render: DISPLAY_FINAL>
Enabled Features: Default
Enabled Attributes: N/A
Lock Interface: Enabled
Cycles Persistent Data: Disabled
Developer Tools: Disabled
Mixbox Plugin: Not Installed
Enabled Addons: Unknown (Blender 4.2)
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1360 pyrna_enum_to_py: current value '0' matches no enum in 'DomainPresetsProperties', '', 'current_package'
Traceback (most recent call last):
  File "/home/luciano/.config/blender/4.2/extensions/user_default/flip_fluids_addon/presets/preset_library.py", line 104, in get_current_package_preset_enums
    if package_info["use_custom_icons"]:
       ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
File "/home/luciano/.config/blender/4.2/extensions/user_default/flip_fluids_addon/presets/preset_library.py", line 79, in get_current_package_preset_enums
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1360 pyrna_enum_to_py: current value '0' matches no enum in 'DomainPresetsProperties', '', 'current_preset'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1360 pyrna_enum_to_py: current value '0' matches no enum in 'DomainPresetsProperties', '', 'current_package'
Error in bpy.app.handlers.load_post[1]:
Traceback (most recent call last):
  File "/home/luciano/.config/blender/4.2/extensions/user_default/flip_fluids_addon/properties/domain_presets_properties.py", line 133, in check_preset_enums
    self.current_package = self.current_package
    ^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luciano/.config/blender/4.2/extensions/user_default/flip_fluids_addon/__init__.py", line 155, in load_post
    properties.load_post()
  File "/home/luciano/.config/blender/4.2/extensions/user_default/flip_fluids_addon/properties/__init__.py", line 62, in load_post
    object_properties.load_post()
  File "/home/luciano/.config/blender/4.2/extensions/user_default/flip_fluids_addon/properties/object_properties.py", line 589, in load_post
    domain_properties.load_post()
  File "/home/luciano/.config/blender/4.2/extensions/user_default/flip_fluids_addon/properties/domain_properties.py", line 468, in load_post
    dprops.load_post()
  File "/home/luciano/.config/blender/4.2/extensions/user_default/flip_fluids_addon/properties/domain_properties.py", line 423, in load_post
    self.presets.load_post()
  File "/home/luciano/.config/blender/4.2/extensions/user_default/flip_fluids_addon/properties/domain_presets_properties.py", line 125, in load_post
    self.check_preset_enums()
  File "/home/luciano/.config/blender/4.2/extensions/user_default/flip_fluids_addon/properties/domain_presets_properties.py", line 136, in check_preset_enums
    self.current_package = enums[0][0]
                           ~~~~~^^^
IndexError: list index out of range


P259971:10:41:27:mapr:INFO: Logger for "mapr" initialized in "/home/luciano/.config/blender/4.2/scripts/addons/botaniq_full/python_deps/mapr/__init__.py" -----
botaniq install dir autodetected as /home/luciano/.config/blender/4.2/scripts/addons/botaniq_full (big zip embedded)
register
Add-on not loaded: "flip_fluids_addon", cause: No module named 'flip_fluids_addon'
Warning: add-on missing 'bl_info', this can cause poor performance!: '/home/luciano/.config/blender/4.2/scripts/addons/generic_node_operators/__init__.py'
Warning: add-on missing 'bl_info', this can cause poor performance!: '/home/luciano/.config/blender/4.2/scripts/addons/menus/__init__.py'
Warning: add-on missing 'bl_info', this can cause poor performance!: '/home/luciano/.config/blender/4.2/scripts/addons/msg_bus/__init__.py'
Warning: add-on missing 'bl_info', this can cause poor performance!: '/home/luciano/.config/blender/4.2/scripts/addons/panels/__init__.py'
Warning: add-on missing 'bl_info', this can cause poor performance!: '/home/luciano/.config/blender/4.2/scripts/addons/properties/__init__.py'
Warning: add-on missing 'bl_info', this can cause poor performance!: '/home/luciano/.config/blender/4.2/scripts/addons/utils/__init__.py'
*** Copied system and Blend file info to clipboard: ***
Blender Version: 4.2.2 LTS, blender-v4.2-release, 2024-09-23 12:18, c03d7d98a413
Addon Version: A FLIP Fluid Simulation Tool for Blender (v1.8.1 GitHub Release 16-JUL-2024)


#### To Reproduce

Provide descriptive instructions for how to reproduce the issue or how to use your .blend file.

#### Expected Behaviour

A description of what you expected to happen.

#### Actual Behaviour

A description of what actually happened.

#### Screenshots

If applicable, add screenshots to help explain your problem.

**Comment by rlguy** [comment]
Hey, FLIP Fluids version 1.8.1 is not supported in Blender 4.2 as and extension. You will need to install the latest FLIP Fluids 1.8.2 in Blender 4.2 to avoid these types of errors.

**Comment by lucianopetrigh** [comment]
ok thank u .. will install version 1.8.1

**Comment by rlguy** [comment]
Oh, sorry you are correct, I was mistaken and had the versioning mixed up. FLIP Fluids 1.8.1 is the most recent version and is supported in Blender 4.2.

I was confused about the ```Warning: add-on missing 'bl_info', this can cause poor performance!``` error originally. It looks like this is actually coming from a few other addons outside of the FLIP Fluids addon.

There may some issues related to how the GitHub release of the FLIP Fluids addon was compiled and/or your Blender userdata. Here are some things to troubleshoot:
- Delete the addon build folder and fully re-compile the addon - this will avoid mixing up files from previous addon version which can be the cause of errors.
- Test within a factory clean Blender userdata folder - this will avoid conflics from other addons that may not be supported in Blender 4.2. This can be tested temporarily by baking up the ```/home/luciano/.config/blender/4.2``` folder. When starting Blender, a new 4.2 folder will be generated which you can work with when testing.
