### ISSUE TITLE
[Feature Request] Add a 'distance' setting for when whitewater 'behaviour at boundary' is set to 'kill'

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids#76]
**Problem**

When the whitewater **behaviour at boundary** settings for foam/bubble/spray particles is set to **kill**, the particles may not be killed at a distance far enough from the boundary that the user desires.

[Whitewater Settings Documentation](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Domain-Whitewater-Settings)

**Solution**

Add a **distance** setting to the foam/bubble/spray kill settings. This will allow the user to specify a distance from the boundary for the particle 'killing' to begin taking effect.

**Comment by dafassi** [comment]
This is very useful in a later post-process.
Another "issue" with the domain´s boundary is the fluidsurface itself.
When it comes to place a simulation into footage i always have the problem with waves that are generated on the domain´s boundary.
I don´t know what would be a good solution for this. Fading out using a feather mask looks unrealistic.
Is "damping near boundary" possible? Or anyone with ideas about this?

**Comment by rlguy** [comment]
My apologies for the ping on this issue thread, just cleaning up the FLIP Fluids GitHub issue tracker. 

The purpose of the FLIP Fluids GitHub issue tracker is for issues and bugs only. Feature development and requests are handled internally and requests can be made through alternative channels. See: [Guidelines for Feature Requests](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests).
