### ISSUE TITLE
[Feature Request] Add functionality set the amount of fluid that an inflow emits instead of only having on/off

### ISSUE THREAD

**Issue by HEEROCKSS** [rlguy/Blender-FLIP-Fluids#90]
How can i change the Water Amount that gets generated by an Inflow Object? I thought over Velocity but thats actually all at 0.0

If there is right now no such Option, i think that would be a good one and even better if we could animate it.
Thanks for your hard Work!
Heerockss

**Comment by rlguy** [comment]
Hey HEEROCKSS,

Increasing the velocity vector should control the fluid amount for an inflow. Is this working for you?

This property is also animatable. Tip: nearly all settings/properties in the domain and simulation objects are animatable.

**Comment by HEEROCKSS** [comment]
My bad, i meant stopping or lowering. In Phoenix FD for example, you can go from a Value of 0 to 9999 which allows you to fine control the Inflow Amount. If i would now just animate the "Enabled" Checkbox, it would kind of cut the Animation.

**Comment by rlguy** [comment]
Do you have any videos showing this feature or examples of what you hope to achieve? This sounds interesting and maybe seeing it in an animation would help me think of a way to implement this feature.

**Comment by HEEROCKSS** [comment]
![pfd emitter 1](https://user-images.githubusercontent.com/26044943/36468222-cec7207a-16e2-11e8-9fcd-b01d25dc6245.JPG)
![pfd emitter 2](https://user-images.githubusercontent.com/26044943/36468223-cee1036e-16e2-11e8-9d06-248ae8a6d909.JPG)
Its actually the same Name (Velocity) but if its set to 0 it will stop from emitting and so you can do a smooth start or stop or just emit extremely small amounts of fluid.

**Comment by HEEROCKSS** [comment]
Heres a short video i made, using Phoenix FD`s Velocity Option. The first 15 Frames Emit no Liquid at all, after Frame 15 it starts to increase.
https://youtu.be/riXEnuzxixc

**Comment by rlguy** [comment]
Thanks for the video! I'll keep this feature in mind and think of a good way to implement this.

**Comment by rlguy** [comment]
An option has been added to the Inflow setting to constrain fluid velocities to match the inflow object velocity. When this setting is enabled, low emission velocities will have the effect of slowing down fluid emission. This feature will be included in the next version update (**1.0.4**).

![constrain_inflow](https://user-images.githubusercontent.com/4285191/41320506-eadabd52-6e54-11e8-9413-f1cfe6ca54a1.jpg)
